import 'reflect-metadata';
import { describe, it } from 'vitest';
import { FINANCE_CLIENT_SERVICES_MODULE, FINANCE_EXPENSE_PLANS_MODULE } from '@nbos/shared';
import { ClientServicesController } from '../client-services/client-services.controller';
import { ExpensePlansController } from '../expenses/expense-plans.controller';
import { ExpensesController } from '../expenses/expenses.controller';
import { InvoicesController } from './invoices/invoices.controller';
import { expectHandlerAllowed, expectHandlerDenied } from './finance-permission-test-support';

const CS_VIEW = { [`${FINANCE_CLIENT_SERVICES_MODULE}_VIEW`]: 'ALL' };
const PLANS_VIEW = { [`${FINANCE_EXPENSE_PLANS_MODULE}_VIEW`]: 'ALL' };
const EXPENSES_VIEW = { FINANCE_EXPENSES_VIEW: 'OWN' };
const INVOICES_VIEW = { FINANCE_INVOICES_VIEW: 'ALL' };
const CS_NONE = { [`${FINANCE_CLIENT_SERVICES_MODULE}_VIEW`]: 'NONE' };
const PLANS_NONE = { [`${FINANCE_EXPENSE_PLANS_MODULE}_VIEW`]: 'NONE' };

const CS_MUTATIONS = [
  'create',
  'update',
  'cancel',
  'remove',
  'checkRegistry',
  'createInvoice',
  'createExpense',
  'createExpensePlan',
  'createTask',
] as const;

const PLAN_MUTATIONS = [
  'create',
  'update',
  'updateStatus',
  'remove',
  'generateCard',
  'autoGenerateDue',
] as const;

describe('isolated finance grants', () => {
  it('lets a client-services-only viewer read that registry and nothing else', () => {
    expectHandlerAllowed(ClientServicesController, 'findAll', CS_VIEW);
    expectHandlerAllowed(ClientServicesController, 'findOne', CS_VIEW);
    expectHandlerDenied(ExpensePlansController, 'findAll', CS_VIEW);
    expectHandlerDenied(ExpensesController, 'findAll', CS_VIEW);
    expectHandlerDenied(InvoicesController, 'findAll', CS_VIEW);
  });

  it('lets an expense-plans-only viewer read plans and nothing else', () => {
    expectHandlerAllowed(ExpensePlansController, 'findAll', PLANS_VIEW);
    expectHandlerAllowed(ExpensePlansController, 'findOne', PLANS_VIEW);
    expectHandlerDenied(ClientServicesController, 'findAll', PLANS_VIEW);
    expectHandlerDenied(ExpensesController, 'findAll', PLANS_VIEW);
    expectHandlerDenied(InvoicesController, 'findAll', PLANS_VIEW);
  });

  it('does not grant the new areas from FINANCE_EXPENSES alone', () => {
    expectHandlerAllowed(ExpensesController, 'findAll', EXPENSES_VIEW);
    expectHandlerDenied(ExpensePlansController, 'findAll', EXPENSES_VIEW);
    expectHandlerDenied(ClientServicesController, 'findAll', EXPENSES_VIEW);
  });

  it('rejects VIEW-only callers on every client-service mutation', () => {
    for (const name of CS_MUTATIONS) {
      expectHandlerDenied(ClientServicesController, name, CS_VIEW);
    }
  });

  it('rejects VIEW-only callers on every expense-plan mutation', () => {
    for (const name of PLAN_MUTATIONS) {
      expectHandlerDenied(ExpensePlansController, name, PLANS_VIEW);
    }
  });

  it('rejects scope NONE on a guessed client-service id', () => {
    expectHandlerDenied(ClientServicesController, 'findOne', CS_NONE);
    expectHandlerDenied(ClientServicesController, 'findOne', {});
  });

  it('rejects scope NONE on a guessed expense-plan id', () => {
    expectHandlerDenied(ExpensePlansController, 'findOne', PLANS_NONE);
    expectHandlerDenied(ExpensePlansController, 'findOne', {});
  });

  it('does not treat invoices VIEW as a client-services grant', () => {
    expectHandlerAllowed(InvoicesController, 'findAll', INVOICES_VIEW);
    expectHandlerDenied(ClientServicesController, 'findAll', INVOICES_VIEW);
  });

  it('rejects invoices VIEW on mark-paid money status and allows EDIT', () => {
    expectHandlerDenied(InvoicesController, 'updateMoneyStatus', INVOICES_VIEW);
    expectHandlerAllowed(InvoicesController, 'updateMoneyStatus', {
      FINANCE_INVOICES_EDIT: 'ALL',
    });
  });
});
