-- Expand ProductTypeEnum with Code product kinds (decision 1.23).
-- Existing values stay. MOBILE_APP and SAAS remain for legacy cards.

ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'PRODUCT_CATALOG';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'BLOG';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'NEWS_MEDIA_PORTAL';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'EVENT_WEBSITE';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'MARKETPLACE';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'B2B_COMMERCE_PORTAL';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'BOOKING_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'TICKETING_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'POS';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'HRM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'LMS';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'TASK_MANAGEMENT_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'HELP_DESK_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'REGISTRATION_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'EVENT_MANAGEMENT_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'DOCUMENT_MANAGEMENT_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'INVENTORY_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'KNOWLEDGE_BASE';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'INDUSTRY_OPERATIONS_SYSTEM';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'BOS';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'CUSTOMER_PORTAL';
ALTER TYPE "ProductTypeEnum" ADD VALUE IF NOT EXISTS 'PARTNER_PORTAL';
