export const WHATSAPP_PRODUCT_GROUPS_QUEUE_NAME = 'whatsapp.product-groups';
export const WHATSAPP_PRODUCT_GROUP_JOB_NAME = 'whatsapp.product-group.operation';

export const WHATSAPP_OUTBOUND_QUEUE_NAME = 'whatsapp.outbound-messages';
export const WHATSAPP_OUTBOUND_JOB_NAME = 'whatsapp.outbound.send';
/** Pause after each outbound WhatsApp send so WAHA is not treated as a burst bot. */
export const WHATSAPP_OUTBOUND_GAP_MS = 2000;
export const WHATSAPP_OUTBOUND_WAIT_TIMEOUT_MS = 60_000;

export const WHATSAPP_GATEWAY_REQUEST_TIMEOUT_MS = 30_000;
export const WHATSAPP_GATEWAY_CONNECT_TIMEOUT_MS = 10_000;
export const WHATSAPP_GROUP_NAME_MAX_LENGTH = 100;
export const WHATSAPP_GATEWAY_DIRECTORY_PAGE_SIZE = 20;
export const WHATSAPP_GATEWAY_DIRECTORY_PAGE_SIZE_MAX = 50;
export const WHATSAPP_GATEWAY_DIRECTORY_SEARCH_MAX_LENGTH = 100;

export const WHATSAPP_AUDIT_ENTITY_GATEWAY = 'whatsapp_gateway';
export const WHATSAPP_AUDIT_ENTITY_PRODUCT_GROUP = 'product_whatsapp_group';
export const WHATSAPP_AUDIT_ENTITY_DEAL_GROUP = 'deal_whatsapp_group';

export const WHATSAPP_AUDIT_GATEWAY_CONFIGURED = 'whatsapp.gateway_configured';
export const WHATSAPP_AUDIT_GATEWAY_TOKEN_CHANGED = 'whatsapp.gateway_token_changed';
export const WHATSAPP_AUDIT_GATEWAY_DISCONNECTED = 'whatsapp.gateway_disconnected';
export const WHATSAPP_AUDIT_GROUP_REQUESTED = 'whatsapp.product_group_requested';
export const WHATSAPP_AUDIT_GROUP_CREATED = 'whatsapp.product_group_created';
export const WHATSAPP_AUDIT_GROUP_FAILED = 'whatsapp.product_group_failed';
export const WHATSAPP_AUDIT_GROUP_OUTCOME_UNKNOWN = 'whatsapp.product_group_outcome_unknown';
export const WHATSAPP_AUDIT_GROUP_BOUND = 'whatsapp.product_group_bound';
export const WHATSAPP_AUDIT_GROUP_REPLACED = 'whatsapp.product_group_replaced';
export const WHATSAPP_AUDIT_PARTICIPANT_ADDED = 'whatsapp.product_group_participant_added';
export const WHATSAPP_AUDIT_PARTICIPANT_SKIPPED = 'whatsapp.product_group_participant_skipped';
export const WHATSAPP_AUDIT_PARTICIPANT_FAILED = 'whatsapp.product_group_participant_failed';
export const WHATSAPP_AUDIT_INVITE_SENT = 'whatsapp.product_group_invite_sent';
export const WHATSAPP_AUDIT_INVITE_FAILED = 'whatsapp.product_group_invite_failed';
export const WHATSAPP_AUDIT_MANUAL_RETRY = 'whatsapp.product_group_manual_retry';

export const WHATSAPP_ERROR = {
  GATEWAY_NOT_CONFIGURED: 'WHATSAPP_GATEWAY_NOT_CONFIGURED',
  GATEWAY_UNAVAILABLE: 'WHATSAPP_GATEWAY_UNAVAILABLE',
  GATEWAY_UNAUTHORIZED: 'WHATSAPP_GATEWAY_UNAUTHORIZED',
  NOT_CONNECTED: 'WHATSAPP_NOT_CONNECTED',
  PRODUCT_GROUP_NOT_FOUND: 'WHATSAPP_PRODUCT_GROUP_NOT_FOUND',
  PRODUCT_GROUP_CREATING: 'WHATSAPP_PRODUCT_GROUP_CREATING',
  PRODUCT_GROUP_CREATE_FAILED: 'WHATSAPP_PRODUCT_GROUP_CREATE_FAILED',
  PRODUCT_GROUP_OUTCOME_UNKNOWN: 'WHATSAPP_PRODUCT_GROUP_OUTCOME_UNKNOWN',
  GROUP_ALREADY_ASSIGNED: 'WHATSAPP_GROUP_ALREADY_ASSIGNED',
  INVALID_GROUP_ID: 'WHATSAPP_INVALID_GROUP_ID',
  INVALID_PHONE: 'WHATSAPP_INVALID_PHONE',
  NO_VALID_INTERNAL_PARTICIPANTS: 'WHATSAPP_NO_VALID_INTERNAL_PARTICIPANTS',
  PARTICIPANT_SYNC_FAILED: 'WHATSAPP_PARTICIPANT_SYNC_FAILED',
  CLIENT_CONTACT_NOT_FOUND: 'WHATSAPP_CLIENT_CONTACT_NOT_FOUND',
  CLIENT_PHONE_INVALID: 'WHATSAPP_CLIENT_PHONE_INVALID',
  CLIENT_INVITE_FAILED: 'WHATSAPP_CLIENT_INVITE_FAILED',
  CLIENT_INVITE_OUTCOME_UNKNOWN: 'WHATSAPP_CLIENT_INVITE_OUTCOME_UNKNOWN',
  DEAL_PRODUCT_NOT_READY: 'DEAL_PRODUCT_NOT_READY',
  DEAL_CONTACT_REQUIRED: 'DEAL_CONTACT_REQUIRED',
  DEAL_TYPE_NOT_ELIGIBLE: 'DEAL_TYPE_NOT_ELIGIBLE',
  DEAL_GROUP_NOT_FOUND: 'DEAL_WHATSAPP_GROUP_NOT_FOUND',
  ACCOUNTING_GROUP_NOT_SET: 'WHATSAPP_ACCOUNTING_GROUP_NOT_SET',
  OUTBOUND_QUEUE_UNAVAILABLE: 'WHATSAPP_OUTBOUND_QUEUE_UNAVAILABLE',
} as const;

export type WhatsAppErrorCode = (typeof WHATSAPP_ERROR)[keyof typeof WHATSAPP_ERROR];
