export {
  TYPE_TINTED_BOARD_CARD_ACCENT_BAR_CLASS as DELIVERY_BOARD_CARD_ACCENT_BAR_CLASS,
  TYPE_TINTED_BOARD_CARD_BODY_STACK_CLASS as DELIVERY_BOARD_CARD_BODY_STACK_CLASS,
  TYPE_TINTED_BOARD_CARD_DATE_ICON_SIZE as DELIVERY_BOARD_CARD_DATE_ICON_SIZE,
  TYPE_TINTED_BOARD_CARD_DATE_LABEL_CLASS as DELIVERY_BOARD_CARD_DATE_LABEL_CLASS,
  TYPE_TINTED_BOARD_CARD_DIVIDER_BASE_CLASS as DELIVERY_BOARD_CARD_DIVIDER_BASE_CLASS,
  TYPE_TINTED_BOARD_CARD_META_ICON_BASE_CLASS as DELIVERY_BOARD_CARD_META_ICON_BASE_CLASS,
  TYPE_TINTED_BOARD_CARD_META_ROW_CLASS as DELIVERY_BOARD_CARD_META_ROW_CLASS,
  TYPE_TINTED_BOARD_CARD_SHELL_CLASS as DELIVERY_BOARD_KANBAN_CARD_SHELL_CLASS,
} from '@/components/shared/kanban/type-tinted-board-card-ui.constants';

/** Circular kind icon (closed / non-minimal cards). */
export const DELIVERY_BOARD_CARD_KIND_ICON_CLASS =
  'flex h-10 w-10 shrink-0 items-center justify-center rounded-full';

export const DELIVERY_BOARD_CARD_DATE_ROW_CLASS =
  'flex items-center gap-1.5 text-sm font-semibold tabular-nums text-green-600 dark:text-green-400';
