'use client';

import { Download, Loader2, Wand2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageSettingsSheet } from '@/components/shared/PageSettingsSheet';
import { useExpensePlansT } from './expense-plan-message-keys';

export interface ExpensePlansPageSettingsSheetProps {
  exportDisabled: boolean;
  exportInProgress: boolean;
  autoGenerateDisabled: boolean;
  autoGenerateInProgress: boolean;
  onExportCsv: () => void | Promise<void>;
  onRunAutoGenerateDue: () => void | Promise<void>;
}

export function ExpensePlansPageSettingsSheet({
  exportDisabled,
  exportInProgress,
  autoGenerateDisabled,
  autoGenerateInProgress,
  onExportCsv,
  onRunAutoGenerateDue,
}: ExpensePlansPageSettingsSheetProps) {
  const t = useExpensePlansT();
  return (
    <PageSettingsSheet
      title={t('settings.title')}
      description={t('settings.description')}
      triggerAriaLabel={t('settings.triggerAria')}
    >
      <Button
        type="button"
        variant="outline"
        className="justify-start gap-2"
        disabled={exportDisabled}
        onClick={() => void onExportCsv()}
      >
        {exportInProgress ? (
          <Loader2 className="size-4 shrink-0 animate-spin" aria-hidden />
        ) : (
          <Download className="size-4 shrink-0" aria-hidden />
        )}
        {t('settings.exportCsv')}
      </Button>
      <Button
        type="button"
        variant="outline"
        className="justify-start gap-2"
        disabled={autoGenerateDisabled}
        onClick={() => void onRunAutoGenerateDue()}
      >
        {autoGenerateInProgress ? (
          <Loader2 className="size-4 shrink-0 animate-spin" aria-hidden />
        ) : (
          <Wand2 className="size-4 shrink-0" aria-hidden />
        )}
        {t('settings.runAutoGenerate')}
      </Button>
    </PageSettingsSheet>
  );
}
