'use client';

import { FINANCE_EXPENSE_PLANS_MODULE } from '@nbos/shared';
import { usePermission } from '@/lib/permissions';

/** Expense plan action visibility derived from the RBAC matrix. */
export function useExpensePlanPermissions() {
  const { can } = usePermission();

  const canAdd = can('ADD', FINANCE_EXPENSE_PLANS_MODULE);
  const canEdit = can('EDIT', FINANCE_EXPENSE_PLANS_MODULE);
  const canDelete = can('DELETE', FINANCE_EXPENSE_PLANS_MODULE);
  // Expense card creation requires FINANCE_EXPENSES EDIT per the expenses API.
  const canCreateExpenseCard = canEdit && can('EDIT', 'FINANCE_EXPENSES');
  const canRunAutoGenerateDue = canCreateExpenseCard;

  return {
    canAdd,
    canEdit,
    canDelete,
    canCreateExpenseCard,
    canRunAutoGenerateDue,
  };
}
