import { Injectable, Inject, NotFoundException, BadRequestException } from '@nestjs/common';
import { Decimal, PrismaClient, type Prisma, type ExpenseCategoryEnum } from '@nbos/database';
import { PRISMA_TOKEN } from '../../database.module';
import { pickExpenseCategoryFilter } from './expense-query-enum-guards';
import { endOfUtcDayUtc } from './expense-plan-auto-due-scope';
import { planNextDueAfterOccurrence } from './expense-plan-next-due';
import {
  requireExpenseCategory,
  resolveExpenseFrequency,
} from './expense-mutation-enum-validators';
import { normalizeExpenseListPage, normalizeExpenseListPageSize } from './expenses-list-pagination';
import { ExpensesService } from './expenses.service';

const EXPENSE_PLAN_SORT_FIELDS = new Set(['createdAt', 'nextDueDate', 'amount', 'name']);

export interface ExpensePlanQueryParams {
  page?: number;
  pageSize?: number;
  projectId?: string;
  category?: string;
  search?: string;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface CreateExpensePlanBody {
  name: string;
  category: string;
  amount: number;
  frequency?: string;
  nextDueDate?: string | null;
  provider?: string | null;
  projectId?: string | null;
  clientServiceRecordId?: string | null;
  autoGenerate?: boolean;
  notes?: string | null;
}

export type UpdateExpensePlanBody = Partial<CreateExpensePlanBody>;

export interface AutoGenerateDuePlansResult {
  asOfInclusiveEndUtc: string;
  eligibleCount: number;
  created: Array<{ planId: string; expenseId: string }>;
  failures: Array<{ planId: string; message: string }>;
}

function toAmountDecimal(amount: number): Decimal {
  if (!Number.isFinite(amount) || amount <= 0) {
    throw new BadRequestException('Amount must be a positive number');
  }
  return new Decimal(amount);
}

function serializePlanRow<T extends { amount: Decimal | unknown }>(row: T) {
  return {
    ...row,
    amount: String(row.amount),
  };
}

@Injectable()
export class ExpensePlansService {
  constructor(
    @Inject(PRISMA_TOKEN) private readonly prisma: InstanceType<typeof PrismaClient>,
    private readonly expensesService: ExpensesService,
  ) {}

  async findAll(params: ExpensePlanQueryParams) {
    const page = normalizeExpenseListPage(params.page);
    const pageSize = normalizeExpenseListPageSize(params.pageSize);
    const safeCategory = pickExpenseCategoryFilter(params.category);
    const where: Prisma.ExpensePlanWhereInput = {
      ...(safeCategory ? { category: safeCategory as ExpenseCategoryEnum } : {}),
      ...(params.projectId?.trim() ? { projectId: params.projectId.trim() } : {}),
      ...(params.search?.trim()
        ? {
            OR: [
              { name: { contains: params.search.trim(), mode: 'insensitive' } },
              { provider: { contains: params.search.trim(), mode: 'insensitive' } },
            ],
          }
        : {}),
    };

    const orderBy = this.buildOrderBy(params.sortBy, params.sortOrder);

    const [items, total] = await Promise.all([
      this.prisma.expensePlan.findMany({
        where,
        include: {
          project: { select: { id: true, code: true, name: true } },
          _count: { select: { expenses: true } },
        },
        orderBy,
        skip: (page - 1) * pageSize,
        take: pageSize,
      }),
      this.prisma.expensePlan.count({ where }),
    ]);

    return {
      items: items.map((row) => serializePlanRow(row)),
      meta: { total, page, pageSize, totalPages: Math.ceil(total / pageSize) },
    };
  }

  async findById(id: string) {
    const row = await this.prisma.expensePlan.findUnique({
      where: { id },
      include: {
        project: { select: { id: true, code: true, name: true } },
        _count: { select: { expenses: true } },
      },
    });
    if (!row) throw new NotFoundException('Expense plan not found');
    return serializePlanRow(row);
  }

  async create(body: CreateExpensePlanBody) {
    const name = body.name?.trim();
    if (!name) throw new BadRequestException('Name is required');
    const category = requireExpenseCategory(body.category);
    const frequency = resolveExpenseFrequency(body.frequency);
    const amount = toAmountDecimal(body.amount);
    const projectId = await this.resolveProjectIdOrThrow(body.projectId);

    const row = await this.prisma.expensePlan.create({
      data: {
        name,
        category: category as Prisma.ExpensePlanCreateInput['category'],
        amount,
        frequency: frequency as Prisma.ExpensePlanCreateInput['frequency'],
        nextDueDate: body.nextDueDate ? new Date(body.nextDueDate) : null,
        provider: body.provider?.trim() || null,
        projectId,
        clientServiceRecordId: body.clientServiceRecordId?.trim() || null,
        autoGenerate: Boolean(body.autoGenerate),
        notes: body.notes?.trim() || null,
      },
      include: {
        project: { select: { id: true, code: true, name: true } },
        _count: { select: { expenses: true } },
      },
    });
    return serializePlanRow(row);
  }

  async update(id: string, body: UpdateExpensePlanBody) {
    await this.ensureExists(id);
    const data: Prisma.ExpensePlanUpdateInput = {};

    if (body.name !== undefined) {
      const n = body.name.trim();
      if (!n) throw new BadRequestException('Name cannot be empty');
      data.name = n;
    }
    if (body.category !== undefined) {
      data.category = requireExpenseCategory(
        body.category,
      ) as Prisma.ExpensePlanUpdateInput['category'];
    }
    if (body.amount !== undefined) {
      data.amount = toAmountDecimal(body.amount);
    }
    if (body.frequency !== undefined) {
      data.frequency = resolveExpenseFrequency(
        body.frequency,
      ) as Prisma.ExpensePlanUpdateInput['frequency'];
    }
    if (body.nextDueDate !== undefined) {
      data.nextDueDate = body.nextDueDate ? new Date(body.nextDueDate) : null;
    }
    if (body.provider !== undefined) {
      data.provider = body.provider?.trim() || null;
    }
    if (body.projectId !== undefined) {
      const pid = await this.resolveProjectIdOrThrow(body.projectId);
      data.project = pid ? { connect: { id: pid } } : { disconnect: true };
    }
    if (body.clientServiceRecordId !== undefined) {
      data.clientServiceRecord = body.clientServiceRecordId?.trim()
        ? { connect: { id: body.clientServiceRecordId.trim() } }
        : { disconnect: true };
    }
    if (body.autoGenerate !== undefined) {
      data.autoGenerate = Boolean(body.autoGenerate);
    }
    if (body.notes !== undefined) {
      data.notes = body.notes?.trim() || null;
    }

    const row = await this.prisma.expensePlan.update({
      where: { id },
      data,
      include: {
        project: { select: { id: true, code: true, name: true } },
        _count: { select: { expenses: true } },
      },
    });
    return serializePlanRow(row);
  }

  async delete(id: string) {
    await this.ensureExists(id);
    await this.prisma.expensePlan.delete({ where: { id } });
  }

  /**
   * Creates a plan-linked **Expense** (card) and advances `nextDueDate` when the plan is recurring.
   */
  async generateCard(planId: string, body?: { dueDate?: string | null }) {
    const plan = await this.prisma.expensePlan.findUnique({ where: { id: planId } });
    if (!plan) throw new NotFoundException('Expense plan not found');

    const fromBody = body?.dueDate?.trim() ? new Date(body.dueDate) : null;
    const occurrence = fromBody ?? plan.nextDueDate;
    if (!occurrence) {
      throw new BadRequestException('Set next due on the plan or pass dueDate to generate a card.');
    }

    const amount = new Decimal(plan.amount).toNumber();
    const expense = await this.expensesService.create({
      name: plan.name,
      type: 'PLANNED',
      category: plan.category,
      amount,
      frequency: 'ONE_TIME',
      dueDate: occurrence.toISOString(),
      status: 'THIS_MONTH',
      projectId: plan.projectId ?? undefined,
      notes: plan.provider ? `From plan. Provider: ${plan.provider}` : 'From expense plan',
      expensePlanId: planId,
      clientServiceRecordId: plan.clientServiceRecordId ?? undefined,
    });

    const nextDue = planNextDueAfterOccurrence(occurrence, plan.frequency);
    await this.prisma.expensePlan.update({
      where: { id: planId },
      data: { nextDueDate: nextDue },
    });

    return expense;
  }

  /**
   * For every plan with `autoGenerate` and `nextDueDate` on or before end-of-day UTC (for `asOf` or today),
   * generates a card via {@link generateCard} (same rules as manual). Intended for finance ops or a future scheduler.
   */
  async autoGenerateDuePlans(params?: { asOf?: string }): Promise<AutoGenerateDuePlansResult> {
    const reference = this.parseAsOfOptional(params?.asOf);
    const cutoff = endOfUtcDayUtc(reference);
    const plans = await this.prisma.expensePlan.findMany({
      where: {
        autoGenerate: true,
        nextDueDate: { not: null, lte: cutoff },
      },
      orderBy: { nextDueDate: 'asc' },
      select: { id: true },
    });

    const created: AutoGenerateDuePlansResult['created'] = [];
    const failures: AutoGenerateDuePlansResult['failures'] = [];

    for (const row of plans) {
      try {
        const expense = await this.generateCard(row.id, {});
        created.push({ planId: row.id, expenseId: expense.id });
      } catch (caught: unknown) {
        const message =
          caught instanceof Error ? caught.message : 'Unknown error while generating card';
        failures.push({ planId: row.id, message });
      }
    }

    return {
      asOfInclusiveEndUtc: cutoff.toISOString(),
      eligibleCount: plans.length,
      created,
      failures,
    };
  }

  private parseAsOfOptional(asOf?: string): Date {
    if (!asOf?.trim()) {
      return new Date();
    }
    const parsed = new Date(asOf.trim());
    if (Number.isNaN(parsed.getTime())) {
      throw new BadRequestException('Invalid asOf; use an ISO-8601 date or datetime.');
    }
    return parsed;
  }

  private buildOrderBy(
    sortBy?: string,
    sortOrder?: 'asc' | 'desc',
  ): Prisma.ExpensePlanOrderByWithRelationInput {
    const dir = sortOrder === 'asc' ? ('asc' as const) : ('desc' as const);
    const field = sortBy && EXPENSE_PLAN_SORT_FIELDS.has(sortBy) ? sortBy : 'createdAt';
    return { [field]: dir } as Prisma.ExpensePlanOrderByWithRelationInput;
  }

  private async ensureExists(id: string): Promise<void> {
    const n = await this.prisma.expensePlan.count({ where: { id } });
    if (!n) throw new NotFoundException('Expense plan not found');
  }

  private async resolveProjectIdOrThrow(
    projectId: string | null | undefined,
  ): Promise<string | null> {
    if (projectId === undefined || projectId === null || projectId === '') return null;
    const id = projectId.trim();
    const p = await this.prisma.project.findUnique({ where: { id }, select: { id: true } });
    if (!p) throw new BadRequestException('Project not found');
    return id;
  }
}
