import { ForbiddenException } from '@nestjs/common';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FINANCE_EXPENSE_PLANS_MODULE } from '@nbos/shared';
import { financePermissionUser } from '../finance/finance-permission-test-support';
import { ExpensePlansController } from './expense-plans.controller';

const PLANS_EDIT = { [`${FINANCE_EXPENSE_PLANS_MODULE}_EDIT`]: 'ALL' };

describe('expense-plan cross-entity conjunctions', () => {
  let plans: {
    generateCard: ReturnType<typeof vi.fn>;
    autoGenerateDuePlans: ReturnType<typeof vi.fn>;
  };
  let controller: ExpensePlansController;

  beforeEach(() => {
    plans = {
      generateCard: vi.fn().mockResolvedValue({ id: 'exp-1' }),
      autoGenerateDuePlans: vi.fn().mockResolvedValue({ created: [] }),
    };
    controller = new ExpensePlansController(plans as never);
  });

  it('blocks card generation without FINANCE_EXPENSES EDIT', async () => {
    await expect(
      controller.generateCard(
        financePermissionUser({ ...PLANS_EDIT, FINANCE_EXPENSES_VIEW: 'ALL' }),
        'plan-1',
        {},
      ),
    ).rejects.toBeInstanceOf(ForbiddenException);
    expect(plans.generateCard).not.toHaveBeenCalled();
  });

  it('generates a card when both rights are present', async () => {
    const user = financePermissionUser({ ...PLANS_EDIT, FINANCE_EXPENSES_EDIT: 'OWN' });
    await expect(controller.generateCard(user, 'plan-1', {})).resolves.toEqual({ id: 'exp-1' });
    expect(plans.generateCard).toHaveBeenCalledOnce();
  });

  it('blocks auto-generate-due without FINANCE_EXPENSES EDIT', async () => {
    await expect(
      controller.autoGenerateDue(
        financePermissionUser({ ...PLANS_EDIT, FINANCE_EXPENSES_ADD: 'ALL' }),
      ),
    ).rejects.toBeInstanceOf(ForbiddenException);
    expect(plans.autoGenerateDuePlans).not.toHaveBeenCalled();
  });

  it('auto-generates due cards when both rights are present', async () => {
    const user = financePermissionUser({ ...PLANS_EDIT, FINANCE_EXPENSES_EDIT: 'ALL' });
    await expect(controller.autoGenerateDue(user)).resolves.toEqual({ created: [] });
    expect(plans.autoGenerateDuePlans).toHaveBeenCalledOnce();
  });

  it('treats a NONE expenses grant as missing', async () => {
    await expect(
      controller.generateCard(
        financePermissionUser({ ...PLANS_EDIT, FINANCE_EXPENSES_EDIT: 'NONE' }),
        'plan-1',
        {},
      ),
    ).rejects.toBeInstanceOf(ForbiddenException);
    expect(plans.generateCard).not.toHaveBeenCalled();
  });
});
