import type { FinanceScopedAccessContext } from '../finance/finance-scoped-access';

export interface ExpensePlanWriteAccess {
  plan?: FinanceScopedAccessContext;
  expense?: FinanceScopedAccessContext;
}

export interface AutoGenerateDuePlansResult {
  asOfInclusiveEndUtc: string;
  eligibleCount: number;
  created: Array<{ planId: string; expenseId: string }>;
  failures: Array<{ planId: string; message: string }>;
}

export interface CreateExpensePlanBody {
  name: string;
  category: string;
  amount: number;
  frequency?: string;
  nextDueDate?: string | null;
  productId?: string | null;
  credentialId?: string | null;
  clientServiceRecordId?: string | null;
  autoGenerate?: boolean;
  notes?: string | null;
}

export type UpdateExpensePlanBody = Partial<CreateExpensePlanBody>;
