import 'reflect-metadata';
import { describe, expect, it } from 'vitest';
import { FINANCE_EXPENSE_PLANS_MODULE } from '@nbos/shared';
import type { RequiredPermission } from '../../common/decorators/require-permission.decorator';
import { handlerNames, permissionOf } from '../finance/finance-permission-test-support';
import { ExpensePlansController } from './expense-plans.controller';

/**
 * This controller shipped without permission decorators, which the global `PermissionGuard`
 * treats as open. The map pins the closed surface after the FINANCE_EXPENSE_PLANS split.
 */
const EXPECTATIONS: Record<string, RequiredPermission> = {
  findAll: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'VIEW' },
  getGrid: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'VIEW' },
  findOne: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'VIEW' },
  create: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'ADD' },
  update: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'EDIT' },
  updateStatus: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'EDIT' },
  generateCard: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'EDIT' },
  autoGenerateDue: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'EDIT' },
  remove: { module: FINANCE_EXPENSE_PLANS_MODULE, action: 'DELETE' },
};

const MUTATIONS = Object.entries(EXPECTATIONS)
  .filter(([, requirement]) => requirement.action !== 'VIEW')
  .map(([name]) => name);

describe('Expense plans permission wiring', () => {
  it.each(Object.entries(EXPECTATIONS))('requires %s', (name, expected) => {
    const handler = (ExpensePlansController.prototype as Record<string, unknown>)[name];
    expect(handler, `missing handler ${name}`).toBeTypeOf('function');
    expect(permissionOf(handler)).toEqual(expected);
  });

  it('leaves no handler open', () => {
    const open = handlerNames(ExpensePlansController).filter(
      (name) => !permissionOf((ExpensePlansController.prototype as Record<string, unknown>)[name]),
    );
    expect(open).toEqual([]);
  });

  it('does not treat VIEW as sufficient for any mutation', () => {
    for (const name of MUTATIONS) {
      expect(
        permissionOf((ExpensePlansController.prototype as Record<string, unknown>)[name]),
      ).not.toEqual({ module: FINANCE_EXPENSE_PLANS_MODULE, action: 'VIEW' });
    }
  });
});
