import {
  Controller,
  Get,
  Post,
  Put,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { FINANCE_EXPENSE_PLANS_MODULE } from '@nbos/shared';
import { CurrentUser, type CurrentUserPayload, RequirePermission } from '../../common/decorators';
import {
  financeExpenseAccessFromUser,
  financeExpensePlanAccessFromUser,
} from '../finance/finance-module-access';
import { assertCallerHasPermission } from '../../common/authorization/caller-permission';
import { ExpensePlansService } from './expense-plans.service';

const FINANCE_EXPENSES_MODULE = 'FINANCE_EXPENSES';

/**
 * FINANCE_EXPENSE_PLANS action map: reads (list, grid, get-by-id) → VIEW; POST create → ADD;
 * update / status / generate-card / auto-generate-due → EDIT; DELETE → DELETE.
 * Generate-card and auto-generate-due also require FINANCE_EXPENSES EDIT (ExpensesController
 * gates card create on EDIT). Machine callers must use POST /scheduler/expense-plan-auto-due.
 */
@ApiTags('Expense plans')
@ApiBearerAuth()
@Controller('expense-plans')
export class ExpensePlansController {
  constructor(private readonly expensePlansService: ExpensePlansService) {}

  @Get()
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'VIEW')
  @ApiOperation({ summary: 'List expense plans (paged)' })
  @ApiQuery({ name: 'page', required: false })
  @ApiQuery({ name: 'pageSize', required: false })
  @ApiQuery({ name: 'projectId', required: false })
  @ApiQuery({ name: 'productId', required: false })
  @ApiQuery({ name: 'category', required: false })
  @ApiQuery({
    name: 'status',
    required: false,
    description: 'ACTIVE, CANCELLED, or comma list. Omit for all.',
  })
  @ApiQuery({
    name: 'frequency',
    required: false,
    description: 'MONTHLY, QUARTERLY, YEARLY, WEEKLY, MULTI_YEAR, or ONE_TIME. Omit for all.',
  })
  @ApiQuery({ name: 'search', required: false })
  @ApiQuery({ name: 'sortBy', required: false })
  @ApiQuery({ name: 'sortOrder', required: false, enum: ['asc', 'desc'] })
  async findAll(
    @CurrentUser() user: CurrentUserPayload,
    @Query('page') page?: string,
    @Query('pageSize') pageSize?: string,
    @Query('projectId') projectId?: string,
    @Query('productId') productId?: string,
    @Query('category') category?: string,
    @Query('status') status?: string,
    @Query('frequency') frequency?: string,
    @Query('search') search?: string,
    @Query('sortBy') sortBy?: string,
    @Query('sortOrder') sortOrder?: 'asc' | 'desc',
  ) {
    return this.expensePlansService.findAll({
      page: page ? parseInt(page, 10) : undefined,
      pageSize: pageSize ? parseInt(pageSize, 10) : undefined,
      projectId,
      productId,
      category,
      status,
      frequency,
      search,
      sortBy,
      sortOrder,
      access: financeExpensePlanAccessFromUser(user),
    });
  }

  @Get('grid')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'VIEW')
  @ApiOperation({
    summary: 'Expense plans calendar grid for a year (rows × months)',
  })
  @ApiQuery({
    name: 'year',
    required: false,
    description: 'Calendar year (defaults to current UTC year)',
  })
  @ApiQuery({ name: 'projectId', required: false })
  @ApiQuery({ name: 'productId', required: false })
  @ApiQuery({ name: 'category', required: false })
  @ApiQuery({
    name: 'status',
    required: false,
    description: 'ACTIVE, CANCELLED, or comma list. Omit for all.',
  })
  @ApiQuery({
    name: 'frequency',
    required: false,
    description: 'MONTHLY, QUARTERLY, YEARLY, WEEKLY, MULTI_YEAR, or ONE_TIME. Omit for all.',
  })
  @ApiQuery({ name: 'search', required: false })
  async getGrid(
    @CurrentUser() user: CurrentUserPayload,
    @Query('year') year?: string,
    @Query('projectId') projectId?: string,
    @Query('productId') productId?: string,
    @Query('category') category?: string,
    @Query('status') status?: string,
    @Query('frequency') frequency?: string,
    @Query('search') search?: string,
  ) {
    const parsedYear = year ? parseInt(year, 10) : undefined;
    return this.expensePlansService.getGrid({
      year: Number.isFinite(parsedYear) ? parsedYear : undefined,
      projectId,
      productId,
      category,
      status,
      frequency,
      search,
      access: financeExpensePlanAccessFromUser(user),
    });
  }

  @Post('actions/auto-generate-due')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'EDIT')
  @ApiOperation({
    summary:
      'Generate cards for plans with auto-generate enabled and next due on or before end of UTC day (for asOf or today)',
  })
  @ApiQuery({
    name: 'asOf',
    required: false,
    description: 'ISO-8601 instant; defaults to now. Comparison uses end of that UTC calendar day.',
  })
  async autoGenerateDue(@CurrentUser() user: CurrentUserPayload, @Query('asOf') asOf?: string) {
    assertCallerHasPermission(user, FINANCE_EXPENSES_MODULE, 'EDIT');
    return this.expensePlansService.autoGenerateDuePlans({
      asOf,
      access: {
        plan: financeExpensePlanAccessFromUser(user),
        expense: financeExpenseAccessFromUser(user),
      },
    });
  }

  @Post(':id/cards')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'EDIT')
  @ApiOperation({
    summary: 'Generate an expense (card) from a plan and advance plan next due when recurring',
  })
  async generateCard(
    @CurrentUser() user: CurrentUserPayload,
    @Param('id') id: string,
    @Body() body?: { dueDate?: string | null },
  ) {
    assertCallerHasPermission(user, FINANCE_EXPENSES_MODULE, 'EDIT');
    return this.expensePlansService.generateCard(id, body, {
      plan: financeExpensePlanAccessFromUser(user),
      expense: financeExpenseAccessFromUser(user),
    });
  }

  @Get(':id')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'VIEW')
  @ApiOperation({
    summary: 'Get expense plan by id',
    description: 'Read-only plan row with project and linked expense count (Finance plan detail).',
  })
  async findOne(@CurrentUser() user: CurrentUserPayload, @Param('id') id: string) {
    return this.expensePlansService.findById(id, financeExpensePlanAccessFromUser(user));
  }

  @Post()
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'ADD')
  @ApiOperation({ summary: 'Create expense plan' })
  async create(
    @Body()
    body: {
      name: string;
      category: string;
      amount: number;
      frequency?: string;
      nextDueDate?: string | null;
      productId?: string | null;
      credentialId?: string | null;
      autoGenerate?: boolean;
      notes?: string | null;
    },
  ) {
    return this.expensePlansService.create(body);
  }

  @Patch(':id/status')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'EDIT')
  @ApiOperation({
    summary: 'Change expense plan status',
    description:
      'ACTIVE → CANCELLED stops auto-generate and forecast. CANCELLED → ACTIVE resumes the plan.',
  })
  async updateStatus(
    @CurrentUser() user: CurrentUserPayload,
    @Param('id') id: string,
    @Body() body: { status: string },
  ) {
    return this.expensePlansService.updateStatus(
      id,
      body.status,
      financeExpensePlanAccessFromUser(user),
    );
  }

  @Put(':id')
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'EDIT')
  @ApiOperation({ summary: 'Update expense plan' })
  async update(
    @CurrentUser() user: CurrentUserPayload,
    @Param('id') id: string,
    @Body()
    body: {
      name?: string;
      category?: string;
      amount?: number;
      frequency?: string;
      nextDueDate?: string | null;
      productId?: string | null;
      credentialId?: string | null;
      autoGenerate?: boolean;
      notes?: string | null;
    },
  ) {
    return this.expensePlansService.update(id, body, financeExpensePlanAccessFromUser(user));
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @RequirePermission(FINANCE_EXPENSE_PLANS_MODULE, 'DELETE')
  @ApiOperation({ summary: 'Delete expense plan' })
  async remove(@CurrentUser() user: CurrentUserPayload, @Param('id') id: string) {
    await this.expensePlansService.delete(id, financeExpensePlanAccessFromUser(user));
  }
}
