import { Injectable, Inject, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaClient, type Prisma, type ExpensePlanStatusEnum } from '@nbos/database';
import { PRISMA_TOKEN } from '../../database.module';
import { assertExpensePlanEmptyDeletable } from '../../common/lifecycle/finance-record-lifecycle-guards';
import {
  mergeFinanceWhere,
  type FinanceScopedAccessContext,
} from '../finance/finance-scoped-access';
import {
  requireExpensePlanCategory,
  resolveExpenseFrequency,
} from './expense-mutation-enum-validators';
import { normalizeExpenseListPage, normalizeExpenseListPageSize } from './expenses-list-pagination';
import { ExpensesService } from './expenses.service';
import { resolveExpenseLinks } from './expense-link-resolve';
import { EXPENSE_PLAN_DETAIL_INCLUDE } from './expense-relation-include';
import { buildExpensePlanGridPayload } from './expense-plan-grid';
import {
  assertExpensePlanStatus,
  assertExpensePlanStatusTransition,
  expensePlanStatusUpdateData,
} from './expense-plan-status';
import {
  assertExpensePlanAccessible,
  resolveExpensePlanParticipationWhere,
} from './expense-plan-access.op';
import { generateExpenseCardFromPlan } from './expense-plan-generate';
import { endOfUtcDayUtc } from './expense-plan-auto-due-scope';
import {
  buildExpensePlanListWhere,
  buildExpensePlanOrderBy,
  type ExpensePlanQueryParams,
} from './expense-plan-query.where';
import { serializeExpensePlanRow, toExpensePlanAmountDecimal } from './expense-plan-serialize';
import { buildExpensePlanUpdateData } from './expense-plan-update.data';
import type {
  AutoGenerateDuePlansResult,
  CreateExpensePlanBody,
  ExpensePlanWriteAccess,
  UpdateExpensePlanBody,
} from './expense-plans.types';

export type { ExpensePlanQueryParams };
export type {
  AutoGenerateDuePlansResult,
  CreateExpensePlanBody,
  ExpensePlanWriteAccess,
  UpdateExpensePlanBody,
};

const EXPENSE_PLAN_GRID_MAX_ROWS = 300;

@Injectable()
export class ExpensePlansService {
  constructor(
    @Inject(PRISMA_TOKEN) private readonly prisma: InstanceType<typeof PrismaClient>,
    private readonly expensesService: ExpensesService,
  ) {}

  async findAll(params: ExpensePlanQueryParams) {
    const page = normalizeExpenseListPage(params.page);
    const pageSize = normalizeExpenseListPageSize(params.pageSize);
    const where = await this.scopedListWhere(params);
    const orderBy = buildExpensePlanOrderBy(params.sortBy, params.sortOrder);

    const [items, total] = await Promise.all([
      this.prisma.expensePlan.findMany({
        where,
        include: EXPENSE_PLAN_DETAIL_INCLUDE,
        orderBy,
        skip: (page - 1) * pageSize,
        take: pageSize,
      }),
      this.prisma.expensePlan.count({ where }),
    ]);

    return {
      items: items.map((row) => serializeExpensePlanRow(row)),
      meta: { total, page, pageSize, totalPages: Math.ceil(total / pageSize) },
    };
  }

  async getGrid(params: ExpensePlanQueryParams & { year?: number }) {
    const year = params.year ?? new Date().getUTCFullYear();
    const where = await this.scopedListWhere(params);
    const rangeStart = new Date(Date.UTC(year, 0, 1));
    const rangeEnd = new Date(Date.UTC(year, 11, 31, 23, 59, 59, 999));

    const plans = await this.prisma.expensePlan.findMany({
      where,
      include: {
        ...EXPENSE_PLAN_DETAIL_INCLUDE,
        expenses: {
          where: { dueDate: { gte: rangeStart, lte: rangeEnd } },
          select: {
            id: true,
            amount: true,
            dueDate: true,
            status: true,
            expensePayments: { select: { amount: true } },
          },
        },
      },
      orderBy: { name: 'asc' },
      take: EXPENSE_PLAN_GRID_MAX_ROWS,
    });

    return buildExpensePlanGridPayload(
      plans.map((plan) => ({
        id: plan.id,
        name: plan.name,
        amount: plan.amount,
        frequency: plan.frequency,
        nextDueDate: plan.nextDueDate,
        status: plan.status,
        project: plan.project,
        expenses: plan.expenses,
      })),
      year,
    );
  }

  async findById(id: string, access?: FinanceScopedAccessContext) {
    await assertExpensePlanAccessible(this.prisma, id, access);
    const row = await this.prisma.expensePlan.findUnique({
      where: { id },
      include: EXPENSE_PLAN_DETAIL_INCLUDE,
    });
    if (!row) throw new NotFoundException('Expense plan not found');
    return serializeExpensePlanRow(row);
  }

  async create(body: CreateExpensePlanBody) {
    const name = body.name?.trim();
    if (!name) throw new BadRequestException('Name is required');
    const links = await resolveExpenseLinks(this.prisma, {
      productId: body.productId,
      credentialId: body.credentialId,
      clientServiceRecordId: body.clientServiceRecordId,
    });

    const row = await this.prisma.expensePlan.create({
      data: {
        name,
        category: requireExpensePlanCategory(
          body.category,
        ) as Prisma.ExpensePlanCreateInput['category'],
        amount: toExpensePlanAmountDecimal(body.amount),
        frequency: resolveExpenseFrequency(
          body.frequency,
        ) as Prisma.ExpensePlanCreateInput['frequency'],
        nextDueDate: body.nextDueDate ? new Date(body.nextDueDate) : null,
        productId: links.productId,
        projectId: links.projectId,
        credentialId: links.credentialId,
        clientServiceRecordId: body.clientServiceRecordId?.trim() || null,
        autoGenerate: Boolean(body.autoGenerate),
        notes: body.notes?.trim() || null,
      },
      include: EXPENSE_PLAN_DETAIL_INCLUDE,
    });
    return serializeExpensePlanRow(row);
  }

  async update(id: string, body: UpdateExpensePlanBody, access?: FinanceScopedAccessContext) {
    await assertExpensePlanAccessible(this.prisma, id, access);
    await this.ensureExists(id);
    const data = await buildExpensePlanUpdateData(this.prisma, id, body);
    const row = await this.prisma.expensePlan.update({
      where: { id },
      data,
      include: EXPENSE_PLAN_DETAIL_INCLUDE,
    });
    return serializeExpensePlanRow(row);
  }

  async updateStatus(id: string, status: string, access?: FinanceScopedAccessContext) {
    assertExpensePlanStatus(status);
    const current = await this.findById(id, access);
    const from = current.status as ExpensePlanStatusEnum;
    assertExpensePlanStatusTransition(from, status);
    const row = await this.prisma.expensePlan.update({
      where: { id },
      data: expensePlanStatusUpdateData(status),
      include: EXPENSE_PLAN_DETAIL_INCLUDE,
    });
    return serializeExpensePlanRow(row);
  }

  async delete(id: string, access?: FinanceScopedAccessContext) {
    await assertExpensePlanAccessible(this.prisma, id, access);
    const plan = await this.prisma.expensePlan.findUnique({
      where: { id },
      include: { _count: { select: { expenses: true } } },
    });
    if (!plan) throw new NotFoundException('Expense plan not found');
    assertExpensePlanEmptyDeletable(plan._count.expenses);
    await this.prisma.expensePlan.delete({ where: { id } });
  }

  /**
   * Creates a plan-linked **Expense** (card) and advances `nextDueDate` when the plan is recurring.
   * Scheduler/worker callers omit `access` so row filters are not applied.
   */
  async generateCard(
    planId: string,
    body?: { dueDate?: string | null },
    access?: ExpensePlanWriteAccess,
  ) {
    return generateExpenseCardFromPlan(this.prisma, this.expensesService, planId, body, access);
  }

  async autoGenerateDuePlans(params?: {
    asOf?: string;
    access?: ExpensePlanWriteAccess;
  }): Promise<AutoGenerateDuePlansResult> {
    const cutoff = endOfUtcDayUtc(this.parseAsOfOptional(params?.asOf));
    const participation = await resolveExpensePlanParticipationWhere(
      this.prisma,
      params?.access?.plan,
    );
    const dueWhere: Prisma.ExpensePlanWhereInput = {
      autoGenerate: true,
      status: 'ACTIVE',
      nextDueDate: { not: null, lte: cutoff },
    };
    const plans = await this.prisma.expensePlan.findMany({
      where: mergeFinanceWhere(dueWhere, participation),
      orderBy: { nextDueDate: 'asc' },
      select: { id: true },
    });

    const created: AutoGenerateDuePlansResult['created'] = [];
    const failures: AutoGenerateDuePlansResult['failures'] = [];
    for (const row of plans) {
      try {
        const expense = await this.generateCard(row.id, {}, params?.access);
        created.push({ planId: row.id, expenseId: expense.id });
      } catch (caught: unknown) {
        const message =
          caught instanceof Error ? caught.message : 'Unknown error while generating card';
        failures.push({ planId: row.id, message });
      }
    }

    return {
      asOfInclusiveEndUtc: cutoff.toISOString(),
      eligibleCount: plans.length,
      created,
      failures,
    };
  }

  private parseAsOfOptional(asOf?: string): Date {
    if (!asOf?.trim()) return new Date();
    const parsed = new Date(asOf.trim());
    if (Number.isNaN(parsed.getTime())) {
      throw new BadRequestException('Invalid asOf; use an ISO-8601 date or datetime.');
    }
    return parsed;
  }

  private async scopedListWhere(
    params: ExpensePlanQueryParams,
  ): Promise<Prisma.ExpensePlanWhereInput> {
    const participation = await resolveExpensePlanParticipationWhere(this.prisma, params.access);
    return mergeFinanceWhere(buildExpensePlanListWhere(params), participation);
  }

  private async ensureExists(id: string): Promise<void> {
    const n = await this.prisma.expensePlan.count({ where: { id } });
    if (!n) throw new NotFoundException('Expense plan not found');
  }
}
