import { api } from '../api';
import type { Expense } from './finance';
import type { ListData } from './finance-common';

export interface ExpensePlan {
  id: string;
  name: string;
  category: string;
  amount: string;
  frequency: string;
  nextDueDate: string | null;
  provider: string | null;
  projectId: string | null;
  autoGenerate: boolean;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  project: { id: string; code: string; name: string } | null;
  _count: { expenses: number };
}

export interface AutoGenerateDuePlansResult {
  asOfInclusiveEndUtc: string;
  eligibleCount: number;
  created: Array<{ planId: string; expenseId: string }>;
  failures: Array<{ planId: string; message: string }>;
}

export interface CreateExpensePlanPayload {
  name: string;
  category: string;
  amount: number;
  frequency?: string;
  nextDueDate?: string | null;
  provider?: string | null;
  projectId?: string | null;
  autoGenerate?: boolean;
  notes?: string | null;
}

export type ExpensePlanGridCellKind =
  | 'NA'
  | 'FORECAST'
  | 'DUE'
  | 'OPEN'
  | 'PARTIAL'
  | 'PAID'
  | 'OVERDUE';

export interface ExpensePlanGridCell {
  kind: ExpensePlanGridCellKind;
  amount: number;
  expenseId: string | null;
}

export interface ExpensePlanGridRow {
  planId: string;
  planName: string;
  amount: number;
  frequency: string;
  projectLabel: string | null;
  months: ExpensePlanGridCell[];
  annualTotal: number;
}

export interface ExpensePlanGridPayload {
  year: number;
  rows: ExpensePlanGridRow[];
  monthTotals: number[];
  grandAnnualTotal: number;
}

export interface ExpensePlanListParams {
  page?: number;
  pageSize?: number;
  projectId?: string;
  category?: string;
  search?: string;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface ExpensePlanGridParams {
  year?: number;
  projectId?: string;
  category?: string;
  search?: string;
}

export const expensePlansApi = {
  async getAll(params?: ExpensePlanListParams): Promise<ListData<ExpensePlan>> {
    const resp = await api.get<ListData<ExpensePlan>>('/api/expense-plans', { params });
    return resp.data;
  },

  async getGrid(params?: ExpensePlanGridParams): Promise<ExpensePlanGridPayload> {
    const resp = await api.get<ExpensePlanGridPayload>('/api/expense-plans/grid', { params });
    return resp.data;
  },

  async getById(id: string): Promise<ExpensePlan> {
    const resp = await api.get<ExpensePlan>(`/api/expense-plans/${id}`);
    return resp.data;
  },

  async create(data: CreateExpensePlanPayload): Promise<ExpensePlan> {
    const resp = await api.post<ExpensePlan>('/api/expense-plans', data);
    return resp.data;
  },

  async update(id: string, data: Partial<CreateExpensePlanPayload>): Promise<ExpensePlan> {
    const resp = await api.put<ExpensePlan>(`/api/expense-plans/${id}`, data);
    return resp.data;
  },

  async delete(id: string): Promise<void> {
    await api.delete(`/api/expense-plans/${id}`);
  },

  async generateCard(planId: string, body?: { dueDate?: string | null }): Promise<Expense> {
    const resp = await api.post<Expense>(`/api/expense-plans/${planId}/cards`, body ?? {});
    return resp.data;
  },

  async runAutoGenerateDue(params?: { asOf?: string }): Promise<AutoGenerateDuePlansResult> {
    const resp = await api.post<AutoGenerateDuePlansResult>(
      '/api/expense-plans/actions/auto-generate-due',
      {},
      { params: params?.asOf ? { asOf: params.asOf } : {} },
    );
    return resp.data;
  },
};
