export const CREDENTIAL_LIST_SELECT = {
  id: true,
  projectId: true,
  productId: true,
  domainId: true,
  clientServiceRecordId: true,
  departmentId: true,
  ownerId: true,
  category: true,
  credentialType: true,
  criticality: true,
  environment: true,
  provider: true,
  name: true,
  url: true,
  login: true,
  phone: true,
  accessLevel: true,
  allowedEmployees: true,
  publicNotes: true,
  lastRotatedAt: true,
  nextRotationAt: true,
  rotationOwnerId: true,
  createdAt: true,
  updatedAt: true,
  archivedAt: true,
  password: true,
  apiKey: true,
  envData: true,
  secureNotes: true,
  project: { select: { id: true, name: true } },
  department: { select: { id: true, name: true } },
  owner: { select: { id: true, firstName: true, lastName: true } },
} as const;
