export const CALL_LIST_SELECT = {
  id: true,
  uid: true,
  calldirect: true,
  phone: true,
  clid: true,
  state: true,
  billsec: true,
  disposition: true,
  rate: true,
  leadId: true,
  contactId: true,
  dealId: true,
  responsibleEmployeeId: true,
  answeredEmployeeId: true,
  createdAt: true,
  updatedAt: true,
  lead: { select: { name: true, contactName: true } },
  contact: { select: { firstName: true, lastName: true } },
  deal: { select: { name: true, code: true } },
  responsibleEmployee: { select: { firstName: true, lastName: true } },
  answeredEmployee: { select: { firstName: true, lastName: true } },
} as const;
