export const AUTH_SESSION_CLEANUP_CRON_ENABLED_ENV = 'SCHEDULER_AUTH_SESSION_CLEANUP_ENABLED';
export const AUTH_SESSION_CLEANUP_CRON_ENV = 'SCHEDULER_AUTH_SESSION_CLEANUP_CRON';
export const AUTH_SESSION_CLEANUP_DEFAULT_CRON = '15 * * * *';
