export const NOTIFICATION_INBOX_RECONCILE_CRON_ENABLED_ENV =
  'SCHEDULER_NOTIFICATION_INBOX_RECONCILE_ENABLED';
export const NOTIFICATION_INBOX_RECONCILE_CRON_ENV = 'SCHEDULER_NOTIFICATION_INBOX_RECONCILE_CRON';
export const NOTIFICATION_INBOX_RECONCILE_DEFAULT_CRON = '*/15 * * * *';
