export const REPORT_SCHEDULES_DUE_ENABLED_ENV = 'REPORT_SCHEDULES_DUE_CRON_ENABLED';
export const REPORT_SCHEDULES_DUE_CRON_ENV = 'REPORT_SCHEDULES_DUE_CRON';
export const REPORT_SCHEDULES_DUE_DEFAULT_CRON = '*/5 * * * *';
export const REPORT_SCHEDULES_DUE_JOB_NAME = 'reports-schedules-due';
