import { describe, it, expect, beforeEach, vi } from 'vitest';
import { SchedulerService } from './scheduler.service';
import { BillingService } from '../finance/billing/billing.service';
import { createMockPrisma, type MockPrisma } from '../../test-utils/mock-prisma';

function createMockBillingService(): Partial<BillingService> {
  return {
    runMonthlyBilling: vi.fn().mockResolvedValue({
      generatedInvoices: 3,
      totalAmount: 15000,
      errors: [],
      skippedLateDelivery: [],
    }),
    runMonthlyExpenses: vi.fn().mockResolvedValue({ generated: 2 }),
  };
}

describe('SchedulerService', () => {
  let service: SchedulerService;
  let prisma: MockPrisma;
  let billingService: ReturnType<typeof createMockBillingService>;
  let invoiceCardRemindersService: { runDueInvoiceCardReminders: ReturnType<typeof vi.fn> };
  let expensePlansService: { autoGenerateDuePlans: ReturnType<typeof vi.fn> };
  let reportsService: { runDueSchedules: ReturnType<typeof vi.fn> };

  beforeEach(() => {
    prisma = createMockPrisma();
    billingService = createMockBillingService();
    invoiceCardRemindersService = {
      runDueInvoiceCardReminders: vi.fn().mockResolvedValue({
        asOf: '2026-05-05T00:00:00.000Z',
        eligibleCount: 0,
        created: [],
        skippedExisting: 0,
      }),
    };
    expensePlansService = {
      autoGenerateDuePlans: vi.fn().mockResolvedValue({
        asOfInclusiveEndUtc: '2026-04-29T23:59:59.999Z',
        eligibleCount: 0,
        created: [],
        failures: [],
      }),
    };
    reportsService = {
      runDueSchedules: vi.fn().mockResolvedValue({ processed: 0, failed: 0 }),
    };
    service = new SchedulerService(
      prisma as never,
      billingService as never,
      invoiceCardRemindersService as never,
      expensePlansService as never,
      reportsService as never,
    );
  });

  describe('runBilling', () => {
    it('should delegate to BillingService', async () => {
      const result = await service.runBilling();

      expect(billingService.runMonthlyBilling).toHaveBeenCalled();
      expect(result.generatedInvoices).toBe(3);
      expect(result.totalAmount).toBe(15000);
    });
  });

  describe('runExpenses', () => {
    it('should delegate to BillingService', async () => {
      const result = await service.runExpenses();

      expect(billingService.runMonthlyExpenses).toHaveBeenCalled();
      expect(result.generated).toBe(2);
    });
  });

  describe('markOverdueInvoices', () => {
    it('should mark overdue invoices', async () => {
      prisma.invoice.findMany.mockResolvedValue([
        { id: 'inv-1', code: 'INV-2026-0001' },
        { id: 'inv-2', code: 'INV-2026-0002' },
      ]);

      const result = await service.markOverdueInvoices();

      expect(result.marked).toBe(2);
      expect(result.invoiceIds).toEqual(['inv-1', 'inv-2']);
      expect(prisma.invoice.updateMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: { in: ['inv-1', 'inv-2'] } },
          data: { status: 'DELAYED', moneyStatus: 'OVERDUE' },
        }),
      );
      expect(prisma.invoice.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            status: {
              notIn: ['PAID', 'FAIL', 'DELAYED', 'ON_HOLD'],
            },
          }),
        }),
      );
    });

    it('should return 0 when no overdue invoices', async () => {
      prisma.invoice.findMany.mockResolvedValue([]);

      const result = await service.markOverdueInvoices();

      expect(result.marked).toBe(0);
      expect(result.invoiceIds).toEqual([]);
      expect(prisma.invoice.updateMany).not.toHaveBeenCalled();
    });
  });

  describe('runExpensePlanAutoDue', () => {
    it('delegates to ExpensePlansService.autoGenerateDuePlans', async () => {
      const result = await service.runExpensePlanAutoDue();

      expect(expensePlansService.autoGenerateDuePlans).toHaveBeenCalledWith({});
      expect(result.eligibleCount).toBe(0);
    });
  });

  describe('runInvoiceCardReminders', () => {
    it('delegates to InvoiceCardRemindersService', async () => {
      const result = await service.runInvoiceCardReminders();

      expect(invoiceCardRemindersService.runDueInvoiceCardReminders).toHaveBeenCalledWith();
      expect(result.eligibleCount).toBe(0);
    });
  });

  describe('runReportSchedulesDue', () => {
    it('delegates to ReportsService.runDueSchedules', async () => {
      const result = await service.runReportSchedulesDue();

      expect(reportsService.runDueSchedules).toHaveBeenCalledWith();
      expect(result).toEqual({ processed: 0, failed: 0 });
    });
  });
});
