import { Body, Controller, Post, HttpCode, HttpStatus, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiSecurity } from '@nestjs/swagger';
import { SkipThrottle } from '@nestjs/throttler';
import { SchedulerService } from './scheduler.service';
import { ServiceApiKeyGuard } from '../../common/guards/service-api-key.guard';
import { Public } from '../../common/decorators';

@ApiTags('Scheduler')
@ApiSecurity('scheduler-key')
@Public()
@SkipThrottle()
@UseGuards(ServiceApiKeyGuard)
@Controller('scheduler')
export class SchedulerController {
  constructor(private readonly schedulerService: SchedulerService) {}

  @Post('billing')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Trigger monthly billing (external cron)' })
  async runBilling() {
    return this.schedulerService.runBilling();
  }

  @Post('overdue-invoices')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Mark overdue invoices (external cron)' })
  async markOverdueInvoices() {
    return this.schedulerService.markOverdueInvoices();
  }

  @Post('invoice-card-reminders')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Invoice Card reminders: official-request + subscription 5-day window',
    description:
      'Yerevan calendar asOf. Official-request catch-up for Tax invoices in Awaiting Payment without a sent request. Subscription WhatsApp «pay within 5 days» on the pay/issue anchor with catch-up until dueDate. Overdue client waves stay on the Invoices button.',
  })
  async runInvoiceCardReminders() {
    return this.schedulerService.runInvoiceCardReminders();
  }

  @Post('expense-backlog-reminders')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Expense Backlog reminder jobs (external cron)',
    description:
      'Creates idempotent NotificationEvent/NotificationJob records: one weekly digest per UTC week for open backlog cards (BACKLOG + backlog reason + unpaid balance), and per-day reminders for backlog cards whose due date has passed. Does not send external messages.',
  })
  async runExpenseBacklogReminders() {
    return this.schedulerService.runExpenseBacklogReminders();
  }

  @Post('expense-plan-auto-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run NBOS expense plan auto-generate for due dates (external cron)',
    description:
      'Delegates to ExpensePlansService.autoGenerateDuePlans (same as POST /expense-plans/actions/auto-generate-due). Optional in-process cron when SCHEDULER_EXPENSE_PLAN_AUTO_DUE_ENABLED=true (see env example).',
  })
  async runExpensePlanAutoDue() {
    return this.schedulerService.runExpensePlanAutoDue();
  }

  @Post('recurring-tasks-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Create due recurring task instances (external cron)',
    description:
      'Finds active RecurringTaskTemplate rows whose nextCreateAt is due and creates Task instances. Optional in-process cron when SCHEDULER_RECURRING_TASKS_DUE_ENABLED=true.',
  })
  async runRecurringTasksDue() {
    return this.schedulerService.runRecurringTasksDue();
  }

  @Post('report-schedules-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run due scheduled report exports (external cron)',
    description:
      'Creates queued ReportExportJob records for active ReportSchedule rows whose nextRunAt is due. Optional in-process cron when REPORT_SCHEDULES_DUE_CRON_ENABLED=true.',
  })
  async runReportSchedulesDue() {
    return this.schedulerService.runReportSchedulesDue();
  }

  @Post('sales-kpi-month-close')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Finalize Sales KPI snapshots for earned month (external cron)',
    description:
      'Syncs KpiResult rows from sales payment facts for all employees with an active KPI policy. Defaults to prior calendar month vs UTC today. Optional body `{ "earnedPeriod": "YYYY-MM" }`.',
  })
  async runSalesKpiMonthClose(@Body() body: { earnedPeriod?: string }) {
    return this.schedulerService.runSalesKpiMonthClose(body);
  }

  @Post('sales-kpi-backfill-all')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Repair Sales KPI + payable snapshots for every earned month with Sales bonuses',
    description:
      'Runs month-close sync + open-bonus payable refresh for each distinct `earnedPeriod` on Sales bonus entries. Use after migrations or data fixes.',
  })
  async runSalesKpiBackfillAll() {
    return this.schedulerService.runSalesKpiBackfillAll();
  }

  @Post('platform-trash-purge')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Unified trash retention purge (Credentials + Drive)',
    description:
      'Runs automated hard purge for credentials and Drive files past resolved retention TTL. Optional in-process cron when SCHEDULER_PLATFORM_TRASH_PURGE_ENABLED=true.',
  })
  async runPlatformTrashPurge() {
    return this.schedulerService.runPlatformTrashPurge();
  }

  @Post('support-sla-escalation')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Support SLA warning / breach in-app notifications (external cron)',
    description:
      'Scans open tickets; creates idempotent in-app notifications for resolve warning, response breach, and resolve breach. Waiting overlay pauses the SLA clock.',
  })
  async runSupportSlaEscalation() {
    return this.schedulerService.runSupportSlaEscalation();
  }

  @Post('notification-inbox-reconcile')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Reconcile NotificationInboxState vs actual unread COUNT',
    description:
      'Requires NOTIFICATION_INBOX_STATE_RECONCILE_ENABLED=true. Repairs drift in batches and publishes SSE snapshots.',
  })
  async runNotificationInboxReconcile() {
    return this.schedulerService.runNotificationInboxReconcile();
  }

  @Post('notification-enqueue-reconcile')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Scan PENDING notification jobs/deliveries after enqueue failures',
    description:
      'Requires NOTIFICATION_ENQUEUE_RECONCILE_ENABLED=true. Logs recoverable PENDING rows (outbox deferred).',
  })
  async runNotificationEnqueueReconcile() {
    return this.schedulerService.runNotificationEnqueueReconcile();
  }

  @Post('client-services-renewal-invoice')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Create renewal Invoice Cards for due WE_PAY client services (external cron)',
    description:
      'Scans Client Service Records with renewal_date within 60 days; creates pass-through Invoice Cards idempotently. REMINDER_ONLY services are skipped. Optional in-process cron when SCHEDULER_CLIENT_SERVICES_RENEWAL_INVOICE_ENABLED=true.',
  })
  async runClientServicesRenewalInvoice() {
    return this.schedulerService.runClientServicesRenewalInvoice();
  }
}
