import { Injectable, Inject, Logger } from '@nestjs/common';
import { PrismaClient, type Prisma } from '@nbos/database';
import { PRISMA_TOKEN } from '../../database.module';
import { BillingService } from '../finance/billing/billing.service';
import { InvoiceCardRemindersService } from '../finance/invoices/invoice-card-reminders.service';
import { ExpenseBacklogRemindersService } from '../expenses/expense-backlog-reminders.service';
import { ExpensePlansService } from '../expenses/expense-plans.service';
import { ReportsScheduleRunnerService } from '../reports/reports-schedule-runner.service';
import { SalesKpiMonthCloseService } from '../payroll-runs/sales-kpi-month-close.service';
import { backfillSalesKpiAndPayablesForAllEarnedPeriods } from '../payroll-runs/run-sales-kpi-month-close';
import { SupportSlaOrchestrationService } from '../support/support-sla-orchestration.service';
import { CredentialsTrashPurgeService } from '../credentials/credentials-trash-purge.service';
import { PlatformTrashPurgeService } from '../platform-lifecycle/platform-trash-purge.service';

interface OverdueResult {
  marked: number;
  invoiceIds: string[];
}

@Injectable()
export class SchedulerService {
  private readonly logger = new Logger(SchedulerService.name);

  constructor(
    @Inject(PRISMA_TOKEN)
    private readonly prisma: InstanceType<typeof PrismaClient>,
    private readonly billingService: BillingService,
    private readonly invoiceCardRemindersService: InvoiceCardRemindersService,
    private readonly expenseBacklogRemindersService: ExpenseBacklogRemindersService,
    private readonly expensePlansService: ExpensePlansService,
    private readonly reportsScheduleRunnerService: ReportsScheduleRunnerService,
    private readonly supportSlaOrchestrationService: SupportSlaOrchestrationService,
    private readonly salesKpiMonthClose: SalesKpiMonthCloseService,
    private readonly credentialsTrashPurgeService: CredentialsTrashPurgeService,
    private readonly platformTrashPurgeService: PlatformTrashPurgeService,
  ) {}

  /** Monthly subscription billing (generates invoices). */
  async runBilling() {
    this.logger.log('Scheduler: running monthly billing');
    const result = await this.billingService.runMonthlyBilling();
    const skipNote =
      result.skippedLateDelivery.length > 0
        ? `; skipped (late delivery): ${result.skippedLateDelivery.length}`
        : '';
    this.logger.log(
      `Billing complete: ${result.generatedInvoices} invoices, $${result.totalAmount}${skipNote}`,
    );
    return result;
  }

  /** Legacy monthly expenses hook from billing (not NBOS expense plans). */
  async runExpenses() {
    this.logger.log('Scheduler: running monthly expenses');
    const result = await this.billingService.runMonthlyExpenses();
    this.logger.log(`Expenses complete: ${result.generated} generated`);
    return result;
  }

  /** Marks non-terminal invoices past due as overdue. */
  async markOverdueInvoices(): Promise<OverdueResult> {
    this.logger.log('Scheduler: marking overdue invoices');

    const now = new Date();
    const overdueInvoices = await this.prisma.invoice.findMany({
      where: {
        moneyStatus: {
          notIn: [
            'PAID',
            'CANCELLED',
            'ON_HOLD',
            'OVERDUE',
          ] as Prisma.EnumInvoiceMoneyStatusEnumFilter['notIn'],
        },
        dueDate: { lt: now },
      },
      select: { id: true, code: true },
    });

    if (overdueInvoices.length === 0) {
      this.logger.log('No overdue invoices found');
      return { marked: 0, invoiceIds: [] };
    }

    const ids = overdueInvoices.map((inv) => inv.id);
    await this.prisma.invoice.updateMany({
      where: { id: { in: ids } },
      data: {
        moneyStatus: 'OVERDUE' as Prisma.InvoiceUpdateManyMutationInput['moneyStatus'],
      },
    });

    this.logger.log(
      `Marked ${ids.length} invoices as overdue: ${overdueInvoices.map((i) => i.code).join(', ')}`,
    );
    return { marked: ids.length, invoiceIds: ids };
  }

  /**
   * NBOS expense plans: creates cards for `autoGenerate` plans whose `nextDueDate` is due (UTC day).
   * Same logic as `POST /expense-plans/actions/auto-generate-due` — for external cron / worker auth.
   */
  async runExpensePlanAutoDue() {
    this.logger.log('Scheduler: expense plan auto-generate (due)');
    const result = await this.expensePlansService.autoGenerateDuePlans({});
    this.logger.log(
      `Expense plan auto-due: eligible=${result.eligibleCount}, created=${result.created.length}, failures=${result.failures.length}`,
    );
    return result;
  }

  async runInvoiceCardReminders() {
    this.logger.log('Scheduler: invoice card reminders due');
    const result = await this.invoiceCardRemindersService.runDueInvoiceCardReminders();
    this.logger.log(
      `Invoice card reminders: eligible=${result.eligibleCount}, created=${result.created.length}, skipped=${result.skippedExisting}`,
    );
    return result;
  }

  /** Expense Backlog: weekly finance digest + daily due reminders (idempotent jobs). */
  async runExpenseBacklogReminders() {
    this.logger.log('Scheduler: expense backlog reminders');
    const result = await this.expenseBacklogRemindersService.runExpenseBacklogReminders();
    this.logger.log(
      `Expense backlog reminders: digest=${JSON.stringify(result.digest)}, dueCreated=${result.due.created.length}, dueSkipped=${result.due.skippedExisting}`,
    );
    return result;
  }

  async runReportSchedulesDue() {
    this.logger.log('Scheduler: report schedules due');
    const result = await this.reportsScheduleRunnerService.runDueSchedules();
    this.logger.log(
      `Report schedules due: processed=${result.processed}, failures=${result.failed}`,
    );
    return result;
  }

  /**
   * Sales KPI month-close: sync earned-month snapshots for all employees with an active KPI policy.
   * Same logic as optional in-process cron when {@link SALES_KPI_MONTH_CLOSE_ENABLED_ENV} is set.
   */
  async runSalesKpiBackfillAll() {
    this.logger.log('Scheduler: sales KPI + payable backfill (all earned periods)');
    const results = await backfillSalesKpiAndPayablesForAllEarnedPeriods(this.prisma);
    this.logger.log(`Sales KPI backfill: ${results.length} period(s) processed`);
    return { periodsProcessed: results.length, results };
  }

  async runSalesKpiMonthClose(body?: { earnedPeriod?: string }) {
    this.logger.log('Scheduler: sales KPI month-close');
    const result = await this.salesKpiMonthClose.run(
      body?.earnedPeriod != null ? { earnedPeriod: body.earnedPeriod } : undefined,
    );
    this.logger.log(
      `Sales KPI month-close: earned=${result.earnedPeriod}, synced=${result.syncedCount}, skipped=${result.skippedCount}, payables=${result.refreshedPayableCount}`,
    );
    return result;
  }

  /** Credentials: hard-purge trashed credentials past retention TTL. */
  async runCredentialTrashPurge() {
    this.logger.log('Scheduler: credential trash retention purge');
    return this.credentialsTrashPurgeService.runRetentionPurge();
  }

  /** Platform: unified retention purge (Credentials + Drive) with audit. */
  async runPlatformTrashPurge() {
    this.logger.log('Scheduler: platform trash retention purge');
    return this.platformTrashPurgeService.runRetentionPurge();
  }

  /** Support: SLA warning / breach in-app orchestration (idempotent per ticket + recipient). */
  async runSupportSlaEscalation() {
    this.logger.log('Scheduler: support SLA escalation scan');
    const result = await this.supportSlaOrchestrationService.runSlaEscalationScan();
    this.logger.log(
      `Support SLA scan: scanned=${result.scanned}, warnings=${result.warnings}, responseBreaches=${result.responseBreaches}, resolveBreaches=${result.resolveBreaches}`,
    );
    return result;
  }
}
