import { describe, it, expect, beforeEach, vi } from 'vitest';
import { SchedulerService } from './scheduler.service';
import { BillingService } from '../finance/billing/billing.service';
import { createMockPrisma, type MockPrisma } from '../../test-utils/mock-prisma';

function createMockBillingService(): Partial<BillingService> {
  return {
    runMonthlyBilling: vi.fn().mockResolvedValue({
      generatedInvoices: 3,
      totalAmount: 15000,
      errors: [],
      skippedLateDelivery: [],
    }),
  };
}

describe('SchedulerService', () => {
  let service: SchedulerService;
  let prisma: MockPrisma;
  let billingService: ReturnType<typeof createMockBillingService>;
  let invoiceCardRemindersService: { runDueInvoiceCardReminders: ReturnType<typeof vi.fn> };
  let expenseBacklogRemindersService: { runExpenseBacklogReminders: ReturnType<typeof vi.fn> };
  let expensePlansService: { autoGenerateDuePlans: ReturnType<typeof vi.fn> };
  let reportsService: { runDueSchedules: ReturnType<typeof vi.fn> };
  let supportSlaOrchestrationService: { runSlaEscalationScan: ReturnType<typeof vi.fn> };
  let lease: { runWithLease: ReturnType<typeof vi.fn> };

  beforeEach(() => {
    prisma = createMockPrisma();
    billingService = createMockBillingService();
    invoiceCardRemindersService = {
      runDueInvoiceCardReminders: vi.fn().mockResolvedValue({
        asOf: '2026-05-05T00:00:00.000Z',
        eligibleCount: 0,
        created: [],
        skippedExisting: 0,
      }),
    };
    expenseBacklogRemindersService = {
      runExpenseBacklogReminders: vi.fn().mockResolvedValue({
        asOf: '2026-05-05T00:00:00.000Z',
        digest: { created: false, weekKey: '2026-05-04', reason: 'no_open_backlog' },
        due: { created: [], skippedExisting: 0 },
      }),
    };
    expensePlansService = {
      autoGenerateDuePlans: vi.fn().mockResolvedValue({
        asOfInclusiveEndUtc: '2026-04-29T23:59:59.999Z',
        eligibleCount: 0,
        created: [],
        failures: [],
      }),
    };
    reportsService = {
      runDueSchedules: vi.fn().mockResolvedValue({ processed: 0, failed: 0 }),
    };
    supportSlaOrchestrationService = {
      runSlaEscalationScan: vi.fn().mockResolvedValue({
        asOf: '2026-05-06T00:00:00.000Z',
        scanned: 0,
        warnings: 0,
        responseBreaches: 0,
        resolveBreaches: 0,
      }),
    };
    const salesKpiMonthClose = {
      run: vi.fn().mockResolvedValue({
        earnedPeriod: '2026-04',
        syncedCount: 0,
        skippedCount: 0,
        refreshedPayableCount: 0,
      }),
    };
    lease = {
      runWithLease: vi.fn(async (_opts, handler) => {
        const abort = new AbortController();
        await handler({
          signal: abort.signal,
          fencingToken: 1n,
          ownerId: 'test-owner',
          runId: 'run-1',
        });
        return { status: 'SUCCEEDED', runId: 'run-1' };
      }),
    };
    service = new SchedulerService(
      prisma as never,
      billingService as never,
      invoiceCardRemindersService as never,
      expenseBacklogRemindersService as never,
      expensePlansService as never,
      reportsService as never,
      supportSlaOrchestrationService as never,
      salesKpiMonthClose as never,
      { runRetentionPurge: vi.fn() } as never,
      { reconcileBatch: vi.fn() } as never,
      { reconcileAll: vi.fn() } as never,
      { reconcilePending: vi.fn() } as never,
      { cleanupExpiredSessions: vi.fn() } as never,
      {
        processDueTemplates: vi.fn().mockResolvedValue({ created: 0, failed: 0, taskIds: [] }),
      } as never,
      lease as never,
    );
  });

  describe('runBilling', () => {
    it('should delegate to BillingService under lease', async () => {
      const result = await service.runBilling();
      expect(billingService.runMonthlyBilling).toHaveBeenCalled();
      expect(result.status).toBe('SUCCEEDED');
      expect(lease.runWithLease).toHaveBeenCalled();
    });
  });

  describe('markOverdueInvoices', () => {
    it('should mark overdue invoices under lease', async () => {
      prisma.invoice.findMany.mockResolvedValue([
        { id: 'inv-1', code: 'INV-2026-0001' },
        { id: 'inv-2', code: 'INV-2026-0002' },
      ]);
      const result = await service.markOverdueInvoices();
      expect(result.status).toBe('SUCCEEDED');
      expect(prisma.invoice.updateMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: { in: ['inv-1', 'inv-2'] } },
          data: { moneyStatus: 'OVERDUE' },
        }),
      );
    });

    it('should not update when no overdue invoices', async () => {
      prisma.invoice.findMany.mockResolvedValue([]);
      const result = await service.markOverdueInvoices();
      expect(result.status).toBe('SUCCEEDED');
      expect(prisma.invoice.updateMany).not.toHaveBeenCalled();
    });
  });

  describe('runExpensePlanAutoDue', () => {
    it('delegates to ExpensePlansService.autoGenerateDuePlans', async () => {
      const result = await service.runExpensePlanAutoDue();
      expect(expensePlansService.autoGenerateDuePlans).toHaveBeenCalledWith({});
      expect(result.status).toBe('SUCCEEDED');
    });
  });

  describe('runInvoiceCardReminders', () => {
    it('delegates to InvoiceCardRemindersService', async () => {
      const result = await service.runInvoiceCardReminders();
      expect(invoiceCardRemindersService.runDueInvoiceCardReminders).toHaveBeenCalledWith();
      expect(result.status).toBe('SUCCEEDED');
    });
  });

  describe('runExpenseBacklogReminders', () => {
    it('delegates to ExpenseBacklogRemindersService', async () => {
      const result = await service.runExpenseBacklogReminders();
      expect(expenseBacklogRemindersService.runExpenseBacklogReminders).toHaveBeenCalledWith();
      expect(result.status).toBe('SUCCEEDED');
    });
  });

  describe('runReportSchedulesDue', () => {
    it('delegates to ReportsService.runDueSchedules', async () => {
      const result = await service.runReportSchedulesDue();
      expect(reportsService.runDueSchedules).toHaveBeenCalledWith();
      expect(result.status).toBe('SUCCEEDED');
    });
  });

  describe('runSupportSlaEscalation', () => {
    it('delegates to SupportSlaOrchestrationService', async () => {
      const result = await service.runSupportSlaEscalation();
      expect(supportSlaOrchestrationService.runSlaEscalationScan).toHaveBeenCalled();
      expect(result.status).toBe('SUCCEEDED');
    });
  });
});
