/** Nest cron flags for jobs that used to be HTTP-only. All default off. */

export const BILLING_CRON_ENABLED_ENV = 'SCHEDULER_BILLING_ENABLED';
export const BILLING_CRON_ENV = 'SCHEDULER_BILLING_CRON';
export const BILLING_DEFAULT_CRON = '0 11 * * *';

export const OVERDUE_INVOICES_CRON_ENABLED_ENV = 'SCHEDULER_OVERDUE_INVOICES_ENABLED';
export const OVERDUE_INVOICES_CRON_ENV = 'SCHEDULER_OVERDUE_INVOICES_CRON';
export const OVERDUE_INVOICES_DEFAULT_CRON = '0 5 * * *';

export const INVOICE_CARD_REMINDERS_CRON_ENABLED_ENV = 'SCHEDULER_INVOICE_CARD_REMINDERS_ENABLED';
export const INVOICE_CARD_REMINDERS_CRON_ENV = 'SCHEDULER_INVOICE_CARD_REMINDERS_CRON';
/** 11:00 daily — work hours in `TZ` (recommend Asia/Yerevan), not overnight. */
export const INVOICE_CARD_REMINDERS_DEFAULT_CRON = '0 11 * * *';

export const EXPENSE_BACKLOG_REMINDERS_CRON_ENABLED_ENV =
  'SCHEDULER_EXPENSE_BACKLOG_REMINDERS_ENABLED';
export const EXPENSE_BACKLOG_REMINDERS_CRON_ENV = 'SCHEDULER_EXPENSE_BACKLOG_REMINDERS_CRON';
export const EXPENSE_BACKLOG_REMINDERS_DEFAULT_CRON = '0 7 * * *';

export const SALES_KPI_MONTH_CLOSE_CRON_ENABLED_ENV = 'SCHEDULER_SALES_KPI_MONTH_CLOSE_ENABLED';
export const SALES_KPI_MONTH_CLOSE_CRON_ENV = 'SCHEDULER_SALES_KPI_MONTH_CLOSE_CRON';
export const SALES_KPI_MONTH_CLOSE_DEFAULT_CRON = '0 8 1 * *';

export const SUPPORT_SLA_ESCALATION_CRON_ENABLED_ENV = 'SCHEDULER_SUPPORT_SLA_ESCALATION_ENABLED';
export const SUPPORT_SLA_ESCALATION_CRON_ENV = 'SCHEDULER_SUPPORT_SLA_ESCALATION_CRON';
export const SUPPORT_SLA_ESCALATION_DEFAULT_CRON = '*/15 * * * *';
