import { Injectable, Inject, Logger } from '@nestjs/common';
import { PrismaClient, type Prisma } from '@nbos/database';
import { PRISMA_TOKEN } from '../../database.module';
import { BillingService } from '../finance/billing/billing.service';
import { ExpensePlansService } from '../expenses/expense-plans.service';

interface OverdueResult {
  marked: number;
  invoiceIds: string[];
}

@Injectable()
export class SchedulerService {
  private readonly logger = new Logger(SchedulerService.name);

  constructor(
    @Inject(PRISMA_TOKEN)
    private readonly prisma: InstanceType<typeof PrismaClient>,
    private readonly billingService: BillingService,
    private readonly expensePlansService: ExpensePlansService,
  ) {}

  /** Monthly subscription billing (generates invoices). */
  async runBilling() {
    this.logger.log('Scheduler: running monthly billing');
    const result = await this.billingService.runMonthlyBilling();
    this.logger.log(
      `Billing complete: ${result.generatedInvoices} invoices, $${result.totalAmount}`,
    );
    return result;
  }

  /** Legacy monthly expenses hook from billing (not NBOS expense plans). */
  async runExpenses() {
    this.logger.log('Scheduler: running monthly expenses');
    const result = await this.billingService.runMonthlyExpenses();
    this.logger.log(`Expenses complete: ${result.generated} generated`);
    return result;
  }

  /** Marks non-terminal invoices past due as overdue. */
  async markOverdueInvoices(): Promise<OverdueResult> {
    this.logger.log('Scheduler: marking overdue invoices');

    const now = new Date();
    const overdueInvoices = await this.prisma.invoice.findMany({
      where: {
        status: {
          notIn: ['PAID', 'FAIL', 'DELAYED'] as Prisma.EnumInvoiceStatusEnumFilter['notIn'],
        },
        dueDate: { lt: now },
      },
      select: { id: true, code: true },
    });

    if (overdueInvoices.length === 0) {
      this.logger.log('No overdue invoices found');
      return { marked: 0, invoiceIds: [] };
    }

    const ids = overdueInvoices.map((inv) => inv.id);
    await this.prisma.invoice.updateMany({
      where: { id: { in: ids } },
      data: { status: 'DELAYED' as Prisma.InvoiceUpdateManyMutationInput['status'] },
    });

    this.logger.log(
      `Marked ${ids.length} invoices as overdue: ${overdueInvoices.map((i) => i.code).join(', ')}`,
    );
    return { marked: ids.length, invoiceIds: ids };
  }

  /**
   * NBOS expense plans: creates cards for `autoGenerate` plans whose `nextDueDate` is due (UTC day).
   * Same logic as `POST /expense-plans/actions/auto-generate-due` — for external cron / worker auth.
   */
  async runExpensePlanAutoDue() {
    this.logger.log('Scheduler: expense plan auto-generate (due)');
    const result = await this.expensePlansService.autoGenerateDuePlans({});
    this.logger.log(
      `Expense plan auto-due: eligible=${result.eligibleCount}, created=${result.created.length}, failures=${result.failures.length}`,
    );
    return result;
  }
}
