import {
  BILLING_CRON_ENABLED_ENV,
  BILLING_CRON_ENV,
  BILLING_DEFAULT_CRON,
  EXPENSE_BACKLOG_REMINDERS_CRON_ENABLED_ENV,
  EXPENSE_BACKLOG_REMINDERS_CRON_ENV,
  EXPENSE_BACKLOG_REMINDERS_DEFAULT_CRON,
  INVOICE_CARD_REMINDERS_CRON_ENABLED_ENV,
  INVOICE_CARD_REMINDERS_CRON_ENV,
  INVOICE_CARD_REMINDERS_DEFAULT_CRON,
  OVERDUE_INVOICES_CRON_ENABLED_ENV,
  OVERDUE_INVOICES_CRON_ENV,
  OVERDUE_INVOICES_DEFAULT_CRON,
  SALES_KPI_MONTH_CLOSE_CRON_ENABLED_ENV,
  SALES_KPI_MONTH_CLOSE_CRON_ENV,
  SALES_KPI_MONTH_CLOSE_DEFAULT_CRON,
  SUPPORT_SLA_ESCALATION_CRON_ENABLED_ENV,
  SUPPORT_SLA_ESCALATION_CRON_ENV,
  SUPPORT_SLA_ESCALATION_DEFAULT_CRON,
} from './scheduler-internal-cron.constants';
import {
  EXPENSE_PLAN_AUTO_DUE_CRON_ENV,
  EXPENSE_PLAN_AUTO_DUE_DEFAULT_CRON,
  EXPENSE_PLAN_AUTO_DUE_ENABLED_ENV,
} from './expense-plan-auto-due-cron.constants';
import {
  RECURRING_TASKS_DUE_CRON_ENV,
  RECURRING_TASKS_DUE_DEFAULT_CRON,
  RECURRING_TASKS_DUE_ENABLED_ENV,
} from './recurring-tasks-due-cron.constants';
import {
  CLIENT_SERVICES_RENEWAL_INVOICE_CRON_ENV,
  CLIENT_SERVICES_RENEWAL_INVOICE_DEFAULT_CRON,
  CLIENT_SERVICES_RENEWAL_INVOICE_ENABLED_ENV,
} from './client-services-renewal-invoice-cron.constants';
import {
  REPORT_SCHEDULES_DUE_CRON_ENV,
  REPORT_SCHEDULES_DUE_DEFAULT_CRON,
  REPORT_SCHEDULES_DUE_ENABLED_ENV,
} from './report-schedules-due-cron.constants';
import {
  AUTH_SESSION_CLEANUP_CRON_ENABLED_ENV,
  AUTH_SESSION_CLEANUP_CRON_ENV,
  AUTH_SESSION_CLEANUP_DEFAULT_CRON,
} from './auth-session-cleanup.cron';
import {
  NOTIFICATION_INBOX_RECONCILE_CRON_ENABLED_ENV,
  NOTIFICATION_INBOX_RECONCILE_CRON_ENV,
  NOTIFICATION_INBOX_RECONCILE_DEFAULT_CRON,
} from './notification-inbox-reconcile.cron';
import {
  NOTIFICATION_ENQUEUE_RECONCILE_CRON_ENABLED_ENV,
  NOTIFICATION_ENQUEUE_RECONCILE_CRON_ENV,
  NOTIFICATION_ENQUEUE_RECONCILE_DEFAULT_CRON,
} from './notification-enqueue-reconcile.cron';
import {
  PLATFORM_TRASH_PURGE_CRON_ENV,
  PLATFORM_TRASH_PURGE_DEFAULT_CRON,
  PLATFORM_TRASH_PURGE_ENABLED_ENV,
} from '../platform-lifecycle/platform-trash-purge.constants';
import {
  MAIL_OUTBOUND_RECONCILE_CRON_ENV,
  MAIL_OUTBOUND_RECONCILE_DEFAULT_CRON,
  MAIL_OUTBOUND_RECONCILE_ENABLED_ENV,
} from '../mail/mail-outbound-runtime.constants';
import {
  MAIL_GMAIL_WATCH_RENEW_CRON_ENV,
  MAIL_GMAIL_WATCH_RENEW_DEFAULT_CRON,
  MAIL_GMAIL_WATCH_RENEW_ENABLED_ENV,
  MAIL_SYNC_RECONCILE_CRON_ENV,
  MAIL_SYNC_RECONCILE_DEFAULT_CRON,
  MAIL_SYNC_RECONCILE_ENABLED_ENV,
} from '../mail/mail-sync-runtime.constants';
import { SCHEDULER_JOB_NAMES } from './scheduler-lease.constants';
import {
  platformCronEntry,
  SCHEDULER_JOB_GROUP,
  SCHEDULER_JOB_RISK,
  SCHEDULER_ROSTER_INTENT,
  type SchedulerJobCatalogEntry,
} from './scheduler-job-catalog.types';

/** Nest cron catalog rows — add one when introducing a Nest cron. */
export const SCHEDULER_PLATFORM_CRON_CATALOG: readonly SchedulerJobCatalogEntry[] = [
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.billing,
    title: 'Monthly billing',
    description: 'Creates subscription invoices on the 1st at 03:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: BILLING_DEFAULT_CRON,
    enabledEnvKey: BILLING_CRON_ENABLED_ENV,
    cronEnvKey: BILLING_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.high,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.overdueInvoices,
    title: 'Overdue invoices',
    description: 'Marks past-due invoices OVERDUE daily at 05:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: OVERDUE_INVOICES_DEFAULT_CRON,
    enabledEnvKey: OVERDUE_INVOICES_CRON_ENABLED_ENV,
    cronEnvKey: OVERDUE_INVOICES_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.invoiceCardReminders,
    title: 'Invoice card reminders',
    description: 'Tax official-request + subscription D-10/D-2 WhatsApp reminders at 11:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: INVOICE_CARD_REMINDERS_DEFAULT_CRON,
    enabledEnvKey: INVOICE_CARD_REMINDERS_CRON_ENABLED_ENV,
    cronEnvKey: INVOICE_CARD_REMINDERS_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.high,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.expenseBacklogReminders,
    title: 'Expense backlog reminders',
    description: 'In-app reminders for stuck expense backlog cards daily at 07:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: EXPENSE_BACKLOG_REMINDERS_DEFAULT_CRON,
    enabledEnvKey: EXPENSE_BACKLOG_REMINDERS_CRON_ENABLED_ENV,
    cronEnvKey: EXPENSE_BACKLOG_REMINDERS_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.salesKpiMonthClose,
    title: 'Sales KPI month close',
    description: 'Closes prior-month sales KPI on the 1st at 08:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: SALES_KPI_MONTH_CLOSE_DEFAULT_CRON,
    enabledEnvKey: SALES_KPI_MONTH_CLOSE_CRON_ENABLED_ENV,
    cronEnvKey: SALES_KPI_MONTH_CLOSE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.expensePlanAutoDue,
    title: 'Expense plan auto-due',
    description: 'Creates expense cards from due plans daily at 02:00.',
    ownerModule: 'Finance',
    group: SCHEDULER_JOB_GROUP.tasksAndPlans,
    defaultExpression: EXPENSE_PLAN_AUTO_DUE_DEFAULT_CRON,
    enabledEnvKey: EXPENSE_PLAN_AUTO_DUE_ENABLED_ENV,
    cronEnvKey: EXPENSE_PLAN_AUTO_DUE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.recurringTasksDue,
    title: 'Recurring tasks due',
    description: 'Creates Task instances from due templates every 10 minutes.',
    ownerModule: 'Tasks',
    group: SCHEDULER_JOB_GROUP.tasksAndPlans,
    defaultExpression: RECURRING_TASKS_DUE_DEFAULT_CRON,
    enabledEnvKey: RECURRING_TASKS_DUE_ENABLED_ENV,
    cronEnvKey: RECURRING_TASKS_DUE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.clientServicesRenewalInvoice,
    title: 'Client Services renewal invoices',
    description: 'Creates Invoice Cards for WE_PAY renewals within 60 days daily at 06:00.',
    ownerModule: 'Client Services',
    group: SCHEDULER_JOB_GROUP.money,
    defaultExpression: CLIENT_SERVICES_RENEWAL_INVOICE_DEFAULT_CRON,
    enabledEnvKey: CLIENT_SERVICES_RENEWAL_INVOICE_ENABLED_ENV,
    cronEnvKey: CLIENT_SERVICES_RENEWAL_INVOICE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.platformTrashPurge,
    title: 'Platform trash purge',
    description: 'Unified retention purge (credentials, Drive, mail, Profile A) Sundays 03:30.',
    ownerModule: 'Platform Lifecycle',
    group: SCHEDULER_JOB_GROUP.trash,
    defaultExpression: PLATFORM_TRASH_PURGE_DEFAULT_CRON,
    enabledEnvKey: PLATFORM_TRASH_PURGE_ENABLED_ENV,
    cronEnvKey: PLATFORM_TRASH_PURGE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.high,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.supportSlaEscalation,
    title: 'Support SLA escalation',
    description: 'Escalates overdue support SLAs every 15 minutes.',
    ownerModule: 'Support',
    group: SCHEDULER_JOB_GROUP.support,
    defaultExpression: SUPPORT_SLA_ESCALATION_DEFAULT_CRON,
    enabledEnvKey: SUPPORT_SLA_ESCALATION_CRON_ENABLED_ENV,
    cronEnvKey: SUPPORT_SLA_ESCALATION_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.notificationInboxReconcile,
    title: 'Notification inbox reconcile',
    description: 'Repairs notification inbox counters every 15 minutes.',
    ownerModule: 'Notifications',
    group: SCHEDULER_JOB_GROUP.support,
    defaultExpression: NOTIFICATION_INBOX_RECONCILE_DEFAULT_CRON,
    enabledEnvKey: NOTIFICATION_INBOX_RECONCILE_CRON_ENABLED_ENV,
    cronEnvKey: NOTIFICATION_INBOX_RECONCILE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.low,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.notificationEnqueueReconcile,
    title: 'Notification enqueue reconcile',
    description: 'Reconciles notification enqueue state every 10 minutes.',
    ownerModule: 'Notifications',
    group: SCHEDULER_JOB_GROUP.support,
    defaultExpression: NOTIFICATION_ENQUEUE_RECONCILE_DEFAULT_CRON,
    enabledEnvKey: NOTIFICATION_ENQUEUE_RECONCILE_CRON_ENABLED_ENV,
    cronEnvKey: NOTIFICATION_ENQUEUE_RECONCILE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.low,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.authSessionExpiryCleanup,
    title: 'Auth session expiry cleanup',
    description: 'Purges expired Auth Session V2 rows hourly at :15. Enable only with Session V2.',
    ownerModule: 'Auth',
    group: SCHEDULER_JOB_GROUP.sessions,
    defaultExpression: AUTH_SESSION_CLEANUP_DEFAULT_CRON,
    enabledEnvKey: AUTH_SESSION_CLEANUP_CRON_ENABLED_ENV,
    cronEnvKey: AUTH_SESSION_CLEANUP_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.low,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.reportSchedulesDue,
    title: 'Report schedules due',
    description:
      'Queues due ReportSchedule exports every 5 minutes. Manual Create file now remains.',
    ownerModule: 'Reports',
    group: SCHEDULER_JOB_GROUP.reports,
    defaultExpression: REPORT_SCHEDULES_DUE_DEFAULT_CRON,
    enabledEnvKey: REPORT_SCHEDULES_DUE_ENABLED_ENV,
    cronEnvKey: REPORT_SCHEDULES_DUE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.on,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.mailOutboundReconcile,
    title: 'Mail outbound reconcile',
    description: 'Reconciles stuck QUEUED/SENDING outbound mail every 2 minutes.',
    ownerModule: 'Mail',
    group: SCHEDULER_JOB_GROUP.mail,
    defaultExpression: MAIL_OUTBOUND_RECONCILE_DEFAULT_CRON,
    enabledEnvKey: MAIL_OUTBOUND_RECONCILE_ENABLED_ENV,
    cronEnvKey: MAIL_OUTBOUND_RECONCILE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.mailGmailWatchRenew,
    title: 'Mail Gmail watch renew',
    description: 'Renews Gmail watches expiring within 24h, hourly.',
    ownerModule: 'Mail',
    group: SCHEDULER_JOB_GROUP.mail,
    defaultExpression: MAIL_GMAIL_WATCH_RENEW_DEFAULT_CRON,
    enabledEnvKey: MAIL_GMAIL_WATCH_RENEW_ENABLED_ENV,
    cronEnvKey: MAIL_GMAIL_WATCH_RENEW_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
  platformCronEntry({
    jobName: SCHEDULER_JOB_NAMES.mailSyncReconcile,
    title: 'Mail sync reconcile',
    description: 'Enqueues sync for ACTIVE/DEGRADED mailboxes every 5 minutes.',
    ownerModule: 'Mail',
    group: SCHEDULER_JOB_GROUP.mail,
    defaultExpression: MAIL_SYNC_RECONCILE_DEFAULT_CRON,
    enabledEnvKey: MAIL_SYNC_RECONCILE_ENABLED_ENV,
    cronEnvKey: MAIL_SYNC_RECONCILE_CRON_ENV,
    risk: SCHEDULER_JOB_RISK.medium,
    rosterIntent: SCHEDULER_ROSTER_INTENT.off,
  }),
];
