import { Controller, Post, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth } from '@nestjs/swagger';
import { SchedulerService } from './scheduler.service';

@ApiTags('Scheduler')
@ApiBearerAuth()
@Controller('scheduler')
export class SchedulerController {
  constructor(private readonly schedulerService: SchedulerService) {}

  @Post('billing')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Trigger monthly billing (external cron)' })
  async runBilling() {
    return this.schedulerService.runBilling();
  }

  @Post('expenses')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Trigger monthly expenses generation (external cron)' })
  async runExpenses() {
    return this.schedulerService.runExpenses();
  }

  @Post('overdue-invoices')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Mark overdue invoices (external cron)' })
  async markOverdueInvoices() {
    return this.schedulerService.markOverdueInvoices();
  }

  @Post('expense-plan-auto-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run NBOS expense plan auto-generate for due dates (external cron)',
    description:
      'Delegates to ExpensePlansService.autoGenerateDuePlans (same as POST /expense-plans/actions/auto-generate-due). Optional in-process cron when SCHEDULER_EXPENSE_PLAN_AUTO_DUE_ENABLED=true (see env example).',
  })
  async runExpensePlanAutoDue() {
    return this.schedulerService.runExpensePlanAutoDue();
  }

  @Post('report-schedules-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run due scheduled report exports (external cron)',
    description:
      'Creates queued ReportExportJob records for active ReportSchedule rows whose nextRunAt is due. Optional in-process cron when REPORT_SCHEDULES_DUE_CRON_ENABLED=true.',
  })
  async runReportSchedulesDue() {
    return this.schedulerService.runReportSchedulesDue();
  }
}
