import { Controller, Post, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth } from '@nestjs/swagger';
import { SchedulerService } from './scheduler.service';

@ApiTags('Scheduler')
@ApiBearerAuth()
@Controller('scheduler')
export class SchedulerController {
  constructor(private readonly schedulerService: SchedulerService) {}

  @Post('billing')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Trigger monthly billing (external cron)' })
  async runBilling() {
    return this.schedulerService.runBilling();
  }

  @Post('expenses')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Trigger monthly expenses generation (external cron)' })
  async runExpenses() {
    return this.schedulerService.runExpenses();
  }

  @Post('overdue-invoices')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Mark overdue invoices (external cron)' })
  async markOverdueInvoices() {
    return this.schedulerService.markOverdueInvoices();
  }

  @Post('invoice-card-reminders')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Create due Invoice Card reminder notification jobs (external cron)',
    description:
      'Creates idempotent NotificationEvent/NotificationJob records from Invoice Card rules. It does not send external client messages.',
  })
  async runInvoiceCardReminders() {
    return this.schedulerService.runInvoiceCardReminders();
  }

  @Post('expense-backlog-reminders')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Expense Backlog reminder jobs (external cron)',
    description:
      'Creates idempotent NotificationEvent/NotificationJob records: one weekly digest per UTC week for open backlog cards (DELAYED + backlog reason + unpaid balance), and per-day reminders for backlog cards whose due date has passed. Does not send external messages.',
  })
  async runExpenseBacklogReminders() {
    return this.schedulerService.runExpenseBacklogReminders();
  }

  @Post('expense-plan-auto-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run NBOS expense plan auto-generate for due dates (external cron)',
    description:
      'Delegates to ExpensePlansService.autoGenerateDuePlans (same as POST /expense-plans/actions/auto-generate-due). Optional in-process cron when SCHEDULER_EXPENSE_PLAN_AUTO_DUE_ENABLED=true (see env example).',
  })
  async runExpensePlanAutoDue() {
    return this.schedulerService.runExpensePlanAutoDue();
  }

  @Post('report-schedules-due')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Run due scheduled report exports (external cron)',
    description:
      'Creates queued ReportExportJob records for active ReportSchedule rows whose nextRunAt is due. Optional in-process cron when REPORT_SCHEDULES_DUE_CRON_ENABLED=true.',
  })
  async runReportSchedulesDue() {
    return this.schedulerService.runReportSchedulesDue();
  }

  @Post('support-sla-escalation')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Support SLA warning / breach in-app notifications (external cron)',
    description:
      'Scans open tickets; creates idempotent in-app notifications for resolve warning, response breach, and resolve breach. Waiting overlay pauses the SLA clock.',
  })
  async runSupportSlaEscalation() {
    return this.schedulerService.runSupportSlaEscalation();
  }
}
