/** English fallbacks for Связать / Link. Render through `crm.svyazat` — do not ship RU-only copy. */
export const LEAD_SVYAZAT_LABELS = {
  button: 'Link',
  merge: 'Merge',
  mergeLead: 'with lead',
  mergeContact: 'with contact',
  add: 'Add',
  newContact: 'new contact',
  contactToWork: 'contact to work',
  searchContact: 'Find contact',
  searchLead: 'Find lead',
  searchDeal: 'Find deal',
  searchProject: 'Find project',
  searchProduct: 'Find product',
  apply: 'Apply',
  cancel: 'Cancel',
  createContactTitle: 'New contact',
  createContactBody: 'Save the person from this lead. The lead stays on the board.',
  createContactApply: 'Create contact',
  attachWorkTitle: 'Contact to work',
  attachWorkHint:
    'Create a contact and attach it to one open work item. This lead will move to Trash.',
  pourTitle: 'Merge with contact',
  pourHint: 'Pour name, phones, and notes into an existing contact. This lead will move to Trash.',
  searchHint: 'Latest 10. Start typing to refresh the list.',
  emptyRecent: 'No recent records',
  emptySearch: 'Nothing found',
  searching: 'Searching…',
  targetDeal: 'Deal',
  targetProject: 'Project',
  targetProduct: 'Product',
  targetLead: 'Lead',
} as const;

export const LEAD_SVYAZAT_RECENT_LIMIT = 10;
