import type { AiCapabilityDefinition, AiScopeType } from './capability-types';

export const CAPABILITY_VERSION_1 = 1;

export const WORKSPACE_SCOPES: readonly AiScopeType[] = [
  'ORGANIZATION',
  'PROJECT',
  'PRODUCT',
  'WORKSPACE',
];

export const TASK_SCOPES: readonly AiScopeType[] = [
  'ORGANIZATION',
  'PROJECT',
  'PRODUCT',
  'WORKSPACE',
  'RESOURCE',
];

/** Phase 1 read capabilities from `02-AI-Capability-and-Action-Layer.md`. */
export const AI_READ_CAPABILITIES: readonly AiCapabilityDefinition[] = [
  {
    key: 'workspaces.read',
    version: CAPABILITY_VERSION_1,
    module: 'Tasks',
    description: 'Discover authorized Work Spaces.',
    access: 'READ',
    risk: 'LOW',
    allowedScopeTypes: WORKSPACE_SCOPES,
    input: { id: 'workspaces.read.input.v1', fields: [] },
    output: {
      id: 'workspaces.read.output.v1',
      fields: ['id', 'name', 'type', 'projectId', 'productId', 'scrumEnabled'],
    },
    idempotency: 'NOT_REQUIRED',
    audit: 'ON_DENY',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'INTERNAL',
    requiresTargetDataClassification: false,
    deprecated: false,
  },
  {
    key: 'tasks.list',
    version: CAPABILITY_VERSION_1,
    module: 'Tasks',
    description: 'List tasks inside an authorized Work Space.',
    access: 'READ',
    risk: 'LOW',
    allowedScopeTypes: TASK_SCOPES,
    input: { id: 'tasks.list.input.v1', fields: ['workspaceId', 'status', 'page', 'pageSize'] },
    output: {
      id: 'tasks.list.output.v1',
      fields: ['id', 'code', 'title', 'status', 'priority', 'dueDate', 'workspaceId'],
    },
    idempotency: 'NOT_REQUIRED',
    audit: 'ON_DENY',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'INTERNAL',
    requiresTargetDataClassification: false,
    deprecated: false,
  },
  {
    key: 'tasks.read',
    version: CAPABILITY_VERSION_1,
    module: 'Tasks',
    description: 'Read one authorized task projection.',
    access: 'READ',
    risk: 'LOW',
    allowedScopeTypes: TASK_SCOPES,
    input: { id: 'tasks.read.input.v1', fields: ['taskId'] },
    output: {
      id: 'tasks.read.output.v1',
      fields: [
        'id',
        'code',
        'title',
        'description',
        'status',
        'priority',
        'dueDate',
        'workspaceId',
        'sprintId',
      ],
    },
    idempotency: 'NOT_REQUIRED',
    audit: 'ON_DENY',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'INTERNAL',
    requiresTargetDataClassification: false,
    deprecated: false,
  },
  {
    key: 'tasks.read_links',
    version: CAPABILITY_VERSION_1,
    module: 'Tasks',
    description: 'Read permitted task-linked context references.',
    access: 'READ',
    risk: 'LOW',
    allowedScopeTypes: TASK_SCOPES,
    input: { id: 'tasks.read_links.input.v1', fields: ['taskId'] },
    output: { id: 'tasks.read_links.output.v1', fields: ['linkType', 'entityType', 'entityId'] },
    idempotency: 'NOT_REQUIRED',
    audit: 'ON_DENY',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'INTERNAL',
    requiresTargetDataClassification: false,
    deprecated: false,
  },
  {
    key: 'tasks.read_discussion',
    version: CAPABILITY_VERSION_1,
    module: 'Tasks',
    description: 'Read permitted task discussion entries.',
    access: 'READ',
    risk: 'MEDIUM',
    allowedScopeTypes: TASK_SCOPES,
    input: { id: 'tasks.read_discussion.input.v1', fields: ['taskId', 'page', 'pageSize'] },
    output: {
      id: 'tasks.read_discussion.output.v1',
      fields: ['id', 'body', 'authorActorType', 'authorDisplayName', 'createdAt'],
    },
    idempotency: 'NOT_REQUIRED',
    audit: 'ON_DENY',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'SENSITIVE',
    requiresTargetDataClassification: true,
    deprecated: false,
  },
  {
    key: 'drive.read_task_artifact',
    version: CAPABILITY_VERSION_1,
    module: 'Drive',
    description: 'Read a task-linked Drive artifact. Secret-adjacent files stay denied.',
    access: 'READ',
    risk: 'MEDIUM',
    allowedScopeTypes: TASK_SCOPES,
    input: { id: 'drive.read_task_artifact.input.v1', fields: ['taskId', 'fileAssetId'] },
    output: {
      id: 'drive.read_task_artifact.output.v1',
      fields: ['id', 'name', 'mimeType', 'sizeBytes', 'confidentiality', 'viewUrl'],
    },
    idempotency: 'NOT_REQUIRED',
    audit: 'ALWAYS',
    approval: 'NONE',
    rateLimitClass: 'READ_STANDARD',
    maxDataClassification: 'INTERNAL',
    requiresTargetDataClassification: true,
    deprecated: false,
  },
];
