/**
 * Task Blueprints — launch packs of tasks when a Product/Deal starts (not recurring, not event rules).
 */
export const TASK_BLUEPRINTS_BY_PRODUCT_TYPE: Record<string, string[]> = {
  BUSINESS_CARD_WEBSITE: [
    'Setup project repo',
    'UI/UX design',
    'Frontend development',
    'Content integration',
    'Testing & QA',
    'Deployment & DNS',
    'Client handover',
  ],
  COMPANY_WEBSITE: [
    'Setup project repo',
    'UI/UX design',
    'Frontend development',
    'Backend development',
    'Content integration',
    'Testing & QA',
    'Deployment & DNS',
    'Client handover',
  ],
  WEB_APP: [
    'Setup project repo',
    'UI/UX design',
    'Frontend development',
    'Backend development',
    'API integration',
    'Testing & QA',
    'Deployment',
    'Client handover',
  ],
  MOBILE_APP: [
    'Setup project repo',
    'UI/UX design',
    'Mobile development',
    'API integration',
    'App store setup',
    'Testing & QA',
    'Release',
    'Client handover',
  ],
  CRM: [
    'Requirements analysis',
    'Database schema',
    'Backend development',
    'Frontend UI',
    'Integration testing',
    'Data migration',
    'UAT',
    'Deployment',
  ],
  ECOMMERCE: [
    'Requirements analysis',
    'UI/UX design',
    'Product catalog setup',
    'Payment integration',
    'Frontend development',
    'Backend development',
    'Testing & QA',
    'Deployment',
    'Client handover',
  ],
  SAAS: [
    'Setup project repo',
    'Architecture design',
    'UI/UX design',
    'Frontend development',
    'Backend development',
    'API integration',
    'Auth & billing setup',
    'Testing & QA',
    'Deployment',
    'Client handover',
  ],
  LANDING: [
    'Content & copy',
    'UI/UX design',
    'Frontend development',
    'Testing & QA',
    'Deployment & DNS',
    'Client handover',
  ],
  ERP: [
    'Requirements analysis',
    'Database schema',
    'Backend development',
    'Frontend UI',
    'Integration testing',
    'Data migration',
    'UAT',
    'Deployment',
  ],
  LOGO: [
    'Client brief',
    'Mood board & concepts',
    'Design iterations',
    'Final deliverables',
    'Client handover',
  ],
  BRANDING: [
    'Client brief',
    'Brand strategy & research',
    'Visual identity concepts',
    'Design iterations',
    'Brand guidelines',
    'Final deliverables',
    'Client handover',
  ],
  DESIGN: [
    'Client brief',
    'Mood board & concepts',
    'Design iterations',
    'Final deliverables',
    'Client handover',
  ],
  SEO: [
    'Technical audit',
    'Keyword research',
    'On-page optimization',
    'Content plan',
    'Link building',
    'Monthly report',
  ],
  PPC: [
    'Account audit & setup',
    'Keyword research & strategy',
    'Ad copy creation',
    'Campaign launch',
    'Optimization & monitoring',
    'Monthly report',
  ],
  SMM: [
    'Strategy & content plan',
    'Visual content creation',
    'Account setup',
    'Launch & monitoring',
    'Monthly report',
  ],
  OTHER: ['Requirements', 'Development', 'Testing', 'Delivery'],
};
