export const paymentReminderSelect = {
  id: true,
  code: true,
  amount: true,
  dueDate: true,
  createdAt: true,
  coverageStartMonth: true,
  taxStatus: true,
  moneyStatus: true,
  officialInvoiceRequestSent: true,
  officialInvoiceSentAt: true,
  notificationsEnabled: true,
  paymentReminderCycle: true,
  company: { select: { name: true } },
  subscription: {
    select: {
      name: true,
      code: true,
      productId: true,
      billingDay: true,
      notificationsEnabled: true,
      reminderLanguage: true,
      product: { select: { id: true, name: true } },
    },
  },
} as const;
