export const MESSENGER_OUTBOUND_RECONCILE_ENABLED_ENV =
  'SCHEDULER_MESSENGER_OUTBOUND_RECONCILE_ENABLED';
export const MESSENGER_OUTBOUND_RECONCILE_CRON_ENV = 'SCHEDULER_MESSENGER_OUTBOUND_RECONCILE_CRON';
/** One-minute cadence matching the reviewed 60s unknown reconcile interval. */
export const MESSENGER_OUTBOUND_RECONCILE_DEFAULT_CRON = '* * * * *';

export const MESSENGER_COMMAND_INVALID_REASON = {
  MISSING_MESSAGE: 'MISSING_MESSAGE',
  DELETED_MESSAGE: 'DELETED_MESSAGE',
  CONVERSATION_MISMATCH: 'CONVERSATION_MISMATCH',
  MALFORMED_PAYLOAD: 'MALFORMED_PAYLOAD',
  NON_CLIENT: 'NON_CLIENT',
  NON_WHATSAPP: 'NON_WHATSAPP',
  FORGED_ROUTING: 'FORGED_ROUTING',
  GATEWAY_WINDOW_EXPIRED: 'GATEWAY_WINDOW_EXPIRED',
  PROVIDER_REF_CONFLICT: 'PROVIDER_REF_CONFLICT',
  MESSAGE_CANCELLED: 'MESSAGE_CANCELLED',
  MESSAGE_FAILED: 'MESSAGE_FAILED',
} as const;

export type MessengerCommandInvalidReason =
  (typeof MESSENGER_COMMAND_INVALID_REASON)[keyof typeof MESSENGER_COMMAND_INVALID_REASON];
