import {
  siAndroid,
  siAnthropic,
  siApple,
  siAsana,
  siAtlassian,
  siBitbucket,
  siBitwarden,
  siClaude,
  siClaudecode,
  siClickup,
  siCloudflare,
  siConfluence,
  siCoolify,
  siCursor,
  siDatadog,
  siDeepseek,
  siDigitalocean,
  siDiscord,
  siDocker,
  siDropbox,
  siFigma,
  siFirebase,
  siFramer,
  siGit,
  siGitea,
  siGithub,
  siGitlab,
  siGmail,
  siGodaddy,
  siGoogle,
  siGooglecloud,
  siGooglegemini,
  siGoogledocs,
  siGoogledrive,
  siGooglemeet,
  siGoogleplay,
  siGooglesheets,
  siGrafana,
  siHetzner,
  siHostinger,
  siHubspot,
  siHuggingface,
  siJira,
  siKubernetes,
  siLinear,
  siLmstudio,
  siMailgun,
  siMiro,
  siMistralai,
  siMongodb,
  siNeon,
  siNamecheap,
  siNextdotjs,
  siNodedotjs,
  siNotion,
  siNpm,
  siOllama,
  siOpenrouter,
  siPerplexity,
  siPnpm,
  siPorkbun,
  siPostgresql,
  siPostman,
  siPrisma,
  siPypi,
  siRailway,
  siReact,
  siRedis,
  siRender,
  siSentry,
  siSquarespace,
  siStackoverflow,
  siStripe,
  siSupabase,
  siTelegram,
  siTrello,
  siVercel,
  siWhatsapp,
  siWordpress,
  siX,
  siYandexcloud,
  siYoutube,
  siZoho,
  siZoom,
  si1password,
} from 'simple-icons';
import type { BrandMark } from './brand-mark';
import { LOCAL_BRAND_MARKS } from './local-brand-marks';
import { LOCAL_HOSTING_BRAND_MARKS } from './local-hosting-brand-marks';

export { IT_BRAND_HOSTS } from './it-brand-hosts';
export { IT_BRAND_LABELS } from './it-brand-labels';

export const IT_BRAND_MARKS: Record<string, BrandMark> = {
  ...LOCAL_BRAND_MARKS,
  ...LOCAL_HOSTING_BRAND_MARKS,
  android: siAndroid,
  anthropic: siAnthropic,
  apple: siApple,
  asana: siAsana,
  atlassian: siAtlassian,
  bitbucket: siBitbucket,
  bitwarden: siBitwarden,
  claude: siClaude,
  claudecode: siClaudecode,
  clickup: siClickup,
  cloudflare: siCloudflare,
  confluence: siConfluence,
  coolify: siCoolify,
  cursor: siCursor,
  datadog: siDatadog,
  deepseek: siDeepseek,
  digitalocean: siDigitalocean,
  discord: siDiscord,
  docker: siDocker,
  dropbox: siDropbox,
  figma: siFigma,
  firebase: siFirebase,
  framer: siFramer,
  git: siGit,
  gitea: siGitea,
  github: siGithub,
  gitlab: siGitlab,
  gmail: siGmail,
  godaddy: siGodaddy,
  google: siGoogle,
  googlecloud: siGooglecloud,
  googlegemini: siGooglegemini,
  googledocs: siGoogledocs,
  googledrive: siGoogledrive,
  googlemeet: siGooglemeet,
  googleplay: siGoogleplay,
  googlesheets: siGooglesheets,
  grafana: siGrafana,
  hetzner: siHetzner,
  hostinger: siHostinger,
  hubspot: siHubspot,
  huggingface: siHuggingface,
  jira: siJira,
  kubernetes: siKubernetes,
  linear: siLinear,
  lmstudio: siLmstudio,
  mailgun: siMailgun,
  miro: siMiro,
  mistralai: siMistralai,
  mongodb: siMongodb,
  namecheap: siNamecheap,
  neon: siNeon,
  nextjs: siNextdotjs,
  nodejs: siNodedotjs,
  notion: siNotion,
  npm: siNpm,
  ollama: siOllama,
  openrouter: siOpenrouter,
  onepassword: si1password,
  perplexity: siPerplexity,
  pnpm: siPnpm,
  porkbun: siPorkbun,
  postgresql: siPostgresql,
  postman: siPostman,
  prisma: siPrisma,
  pypi: siPypi,
  railway: siRailway,
  react: siReact,
  redis: siRedis,
  render: siRender,
  sentry: siSentry,
  squarespace: siSquarespace,
  stackoverflow: siStackoverflow,
  stripe: siStripe,
  supabase: siSupabase,
  telegram: siTelegram,
  trello: siTrello,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  wordpress: siWordpress,
  x: siX,
  yandexcloud: siYandexcloud,
  youtube: siYoutube,
  zoho: siZoho,
  zoom: siZoom,
};
