/** Normalized label / token → catalog key. */
export const IT_BRAND_LABELS: Record<string, string> = {
  git: 'git',
  github: 'github',
  gh: 'github',
  gitlab: 'gitlab',
  slack: 'slack',
  figma: 'figma',
  notion: 'notion',
  linear: 'linear',
  jira: 'jira',
  trello: 'trello',
  asana: 'asana',
  clickup: 'clickup',
  docker: 'docker',
  vercel: 'vercel',
  npm: 'npm',
  cursor: 'cursor',
  claude: 'claude',
  anthropic: 'anthropic',
  openai: 'openai',
  chatgpt: 'openai',
  gpt: 'openai',
  adobe: 'adobe',
  aws: 'amazonaws',
  amazonaws: 'amazonaws',
  gemini: 'googlegemini',
  googlegemini: 'googlegemini',
  deepseek: 'deepseek',
  mistral: 'mistralai',
  mistralai: 'mistralai',
  openrouter: 'openrouter',
  lmstudio: 'lmstudio',
  'lm studio': 'lmstudio',
  'chat gpt': 'openai',
  'amazon web services': 'amazonaws',
  vscode: 'visualstudiocode',
  'vs code': 'visualstudiocode',
  discord: 'discord',
  telegram: 'telegram',
  zoom: 'zoom',
  gmail: 'gmail',
  googlemail: 'gmail',
  hetzner: 'hetzner',
  beget: 'beget',
  timeweb: 'timeweb',
  selectel: 'selectel',
  hostinger: 'hostinger',
  namecheap: 'namecheap',
  godaddy: 'godaddy',
  zoho: 'zoho',
  mailgun: 'mailgun',
  wordpress: 'wordpress',
  squarespace: 'squarespace',
  firebase: 'firebase',
  googleplay: 'googleplay',
  'google play': 'googleplay',
  coolify: 'coolify',
  yandexcloud: 'yandex',
  'yandex cloud': 'yandex',
  'yandex mail': 'yandex',
  yandex: 'yandex',
  mailru: 'mailru',
  'mail.ru': 'mailru',
  'mail ru': 'mailru',
  nameam: 'nameam',
  'name.am': 'nameam',
  hayhost: 'hayhost',
  'hay host': 'hayhost',
  regam: 'regam',
  'reg.am': 'regam',
  regru: 'regru',
  'reg.ru': 'regru',
  sendgrid: 'sendgrid',
  porkbun: 'porkbun',
  'google workspace': 'google',
  google: 'google',
  linkedin: 'linkedin',
  youtube: 'youtube',
  sentry: 'sentry',
  postman: 'postman',
  postgresql: 'postgresql',
  pgadmin: 'postgresql',
  githubcopilot: 'github',
};
