import {
  siAndroid,
  siAnthropic,
  siApple,
  siAsana,
  siAtlassian,
  siBitbucket,
  siBitwarden,
  siClaude,
  siClaudecode,
  siClickup,
  siCloudflare,
  siConfluence,
  siCursor,
  siDatadog,
  siDigitalocean,
  siDiscord,
  siDocker,
  siDropbox,
  siFigma,
  siFramer,
  siGit,
  siGitea,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGooglecloud,
  siGoogledocs,
  siGoogledrive,
  siGooglemeet,
  siGooglesheets,
  siGrafana,
  siHubspot,
  siHuggingface,
  siJira,
  siKubernetes,
  siLinear,
  siMiro,
  siMongodb,
  siNeon,
  siNextdotjs,
  siNodedotjs,
  siNotion,
  siNpm,
  siOllama,
  siPerplexity,
  siPnpm,
  siPostgresql,
  siPostman,
  siPrisma,
  siPypi,
  siRailway,
  siReact,
  siRedis,
  siRender,
  siSentry,
  siStackoverflow,
  siStripe,
  siSupabase,
  siTelegram,
  siTrello,
  siVercel,
  siWhatsapp,
  siX,
  siYoutube,
  siZoom,
  si1password,
} from 'simple-icons';
import type { BrandMark } from './brand-mark';
import { LOCAL_BRAND_MARKS } from './local-brand-marks';

export const IT_BRAND_MARKS: Record<string, BrandMark> = {
  ...LOCAL_BRAND_MARKS,
  android: siAndroid,
  anthropic: siAnthropic,
  apple: siApple,
  asana: siAsana,
  atlassian: siAtlassian,
  bitbucket: siBitbucket,
  bitwarden: siBitwarden,
  claude: siClaude,
  claudecode: siClaudecode,
  clickup: siClickup,
  cloudflare: siCloudflare,
  confluence: siConfluence,
  cursor: siCursor,
  datadog: siDatadog,
  digitalocean: siDigitalocean,
  discord: siDiscord,
  docker: siDocker,
  dropbox: siDropbox,
  figma: siFigma,
  framer: siFramer,
  git: siGit,
  gitea: siGitea,
  github: siGithub,
  gitlab: siGitlab,
  gmail: siGmail,
  google: siGoogle,
  googlecloud: siGooglecloud,
  googledocs: siGoogledocs,
  googledrive: siGoogledrive,
  googlemeet: siGooglemeet,
  googlesheets: siGooglesheets,
  grafana: siGrafana,
  hubspot: siHubspot,
  huggingface: siHuggingface,
  jira: siJira,
  kubernetes: siKubernetes,
  linear: siLinear,
  miro: siMiro,
  mongodb: siMongodb,
  neon: siNeon,
  nextjs: siNextdotjs,
  nodejs: siNodedotjs,
  notion: siNotion,
  npm: siNpm,
  ollama: siOllama,
  onepassword: si1password,
  perplexity: siPerplexity,
  pnpm: siPnpm,
  postgresql: siPostgresql,
  postman: siPostman,
  prisma: siPrisma,
  pypi: siPypi,
  railway: siRailway,
  react: siReact,
  redis: siRedis,
  render: siRender,
  sentry: siSentry,
  stackoverflow: siStackoverflow,
  stripe: siStripe,
  supabase: siSupabase,
  telegram: siTelegram,
  trello: siTrello,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  x: siX,
  youtube: siYoutube,
  zoom: siZoom,
};

/** Host suffix → catalog key. Longer hosts win (docs.google.com over google.com). */
export const IT_BRAND_HOSTS: ReadonlyArray<readonly [string, string]> = [
  ['docs.google.com', 'googledocs'],
  ['sheets.google.com', 'googlesheets'],
  ['drive.google.com', 'googledrive'],
  ['mail.google.com', 'gmail'],
  ['meet.google.com', 'googlemeet'],
  ['calendar.google.com', 'google'],
  ['cloud.google.com', 'googlecloud'],
  ['google.com', 'google'],
  ['gmail.com', 'gmail'],
  ['github.com', 'github'],
  ['github.dev', 'github'],
  ['gitlab.com', 'gitlab'],
  ['bitbucket.org', 'bitbucket'],
  ['gitea.com', 'gitea'],
  ['linear.app', 'linear'],
  ['atlassian.net', 'atlassian'],
  ['jira.com', 'jira'],
  ['trello.com', 'trello'],
  ['asana.com', 'asana'],
  ['clickup.com', 'clickup'],
  ['notion.so', 'notion'],
  ['notion.site', 'notion'],
  ['slack.com', 'slack'],
  ['discord.com', 'discord'],
  ['discord.gg', 'discord'],
  ['telegram.org', 'telegram'],
  ['t.me', 'telegram'],
  ['whatsapp.com', 'whatsapp'],
  ['zoom.us', 'zoom'],
  ['figma.com', 'figma'],
  ['miro.com', 'miro'],
  ['framer.com', 'framer'],
  ['vercel.com', 'vercel'],
  ['cloudflare.com', 'cloudflare'],
  ['docker.com', 'docker'],
  ['hub.docker.com', 'docker'],
  ['kubernetes.io', 'kubernetes'],
  ['digitalocean.com', 'digitalocean'],
  ['railway.app', 'railway'],
  ['render.com', 'render'],
  ['npmjs.com', 'npm'],
  ['pypi.org', 'pypi'],
  ['sentry.io', 'sentry'],
  ['datadoghq.com', 'datadog'],
  ['grafana.com', 'grafana'],
  ['postman.com', 'postman'],
  ['anthropic.com', 'anthropic'],
  ['claude.ai', 'claude'],
  ['cursor.com', 'cursor'],
  ['huggingface.co', 'huggingface'],
  ['perplexity.ai', 'perplexity'],
  ['ollama.com', 'ollama'],
  ['stackoverflow.com', 'stackoverflow'],
  ['linkedin.com', 'linkedin'],
  ['youtube.com', 'youtube'],
  ['youtu.be', 'youtube'],
  ['x.com', 'x'],
  ['twitter.com', 'x'],
  ['dropbox.com', 'dropbox'],
  ['1password.com', 'onepassword'],
  ['bitwarden.com', 'bitwarden'],
  ['stripe.com', 'stripe'],
  ['prisma.io', 'prisma'],
  ['neon.tech', 'neon'],
  ['supabase.com', 'supabase'],
  ['hubspot.com', 'hubspot'],
  ['apple.com', 'apple'],
  ['developer.apple.com', 'apple'],
  ['android.com', 'android'],
  ['microsoft.com', 'microsoft'],
  ['office.com', 'microsoft'],
  ['live.com', 'microsoft'],
  ['vscode.dev', 'visualstudiocode'],
  ['code.visualstudio.com', 'visualstudiocode'],
];

export const IT_BRAND_LABELS: Record<string, string> = {
  git: 'git',
  github: 'github',
  gh: 'github',
  gitlab: 'gitlab',
  slack: 'slack',
  figma: 'figma',
  notion: 'notion',
  linear: 'linear',
  jira: 'jira',
  trello: 'trello',
  asana: 'asana',
  clickup: 'clickup',
  docker: 'docker',
  vercel: 'vercel',
  npm: 'npm',
  cursor: 'cursor',
  claude: 'claude',
  vscode: 'visualstudiocode',
  'vs code': 'visualstudiocode',
  discord: 'discord',
  telegram: 'telegram',
  zoom: 'zoom',
  gmail: 'gmail',
  google: 'google',
  linkedin: 'linkedin',
  youtube: 'youtube',
  sentry: 'sentry',
  postman: 'postman',
  githubcopilot: 'github',
};
