import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_A = [
  deskPair(
    'everyday-better-than-expected',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, թող օրը սպասածից լավ անցնի։',
    'Մի փոքր հաջողությունն էլ կարող է ամբողջ օրը փոխել։',
  ),
  deskPair(
    'everyday-little-surprise',
    'everyday',
    'surprise',
    'Smile',
    'Այսօր մի հաճելի անակնկալ քեզ, {{firstName}}։',
    'Գուցե լավ լուր, գուցե վաղուց սպասված զանգ։',
  ),
  deskPair(
    'everyday-easy-thing',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, թող մի գործ հեշտ ստացվի։',
    'Այնքան հեշտ, որ ինքդ էլ զարմանաս։',
  ),
  deskPair(
    'everyday-pleasant-detour',
    'everyday',
    'detour',
    'Compass',
    '{{firstName}}, թող ճանապարհդ մի լավ տեղ տանի։',
    'Երբեմն պատահաբար գտած սրճարանն է դառնում սիրելին։',
  ),
  deskPair(
    'everyday-new-favourite',
    'everyday',
    'favourite',
    'Sparkles',
    '{{firstName}}, գուցե այսօր նոր սիրելի երգ գտնես։',
    'Այնպիսին, որ միանգամից ուզենաս մեկին ուղարկել։',
  ),
  deskPair(
    'everyday-looking-forward',
    'everyday',
    'forward',
    'Smile',
    'Թող առջևում սպասելու լավ բան լինի։',
    'Թեկուզ փոքրիկ հանդիպում, որի մասին մտածելիս ժպտաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-idea',
    'everyday',
    'clarity',
    'Coffee',
    'Թող լավ միտքը ճիշտ պահին գա։',
    'Ցանկալի է՝ մինչև սուրճդ սառչի, {{firstName}}։',
  ),
  deskPair(
    'everyday-click',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, թող մի բան վերջապես պարզ դառնա։',
    'Այն հաճելի պահը, երբ ասում ես՝ «բա իհարկե»։',
  ),
  deskPair(
    'everyday-fresh-thought',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, այսօր մի նոր միտք քեզ։',
    'Գուցե ամենաանսպասելի զրույցից ծնվի։',
  ),
  deskPair(
    'everyday-right-words',
    'everyday',
    'words',
    'MessageCircle',
    'Թող ասելիքիդ ճիշտ բառերը գտնվեն։',
    'Ու դիմացինդ քեզ հասկանա հենց առաջին անգամից, {{firstName}}։',
  ),
  deskPair(
    'everyday-good-conversation',
    'everyday',
    'conversation',
    'MessageCircle',
    'Մի լավ զրույց եմ մաղթում, {{firstName}}։',
    'Այնպիսին, որ հետո էլ մտքումդ շարունակվի։',
  ),
  deskPair(
    'everyday-good-story',
    'everyday',
    'story',
    'MessageCircle',
    '{{firstName}}, թող պատմելու լավ բան ունենաս։',
    'Երեկոյան մեկին ասես՝ «գիտե՞ս՝ այսօր ինչ եղավ»։',
  ),
  deskPair(
    'everyday-kindness',
    'everyday',
    'kindness',
    'Smile',
    'Թող այսօր մի բարի վերաբերմունք հանդիպի։',
    'Փոքրիկ ուշադրությունն էլ ջերմություն ունի, {{firstName}}։',
  ),
  deskPair(
    'everyday-small-pleasure',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, թող սովորական օրը համով բան ունենա։',
    'Համեղ ճաշն էլ է օրվա լավ պահերից։',
  ),
  deskPair(
    'everyday-laugh',
    'everyday',
    'humour',
    'Smile',
    'Այսօր սրտանց ծիծաղելու առիթ քեզ, {{firstName}}։',
    'Այն տեսակ ծիծաղը, որից հետո էլ ժպիտդ մնում է։',
  ),
  deskPair(
    'everyday-music',
    'everyday',
    'music',
    'Music',
    'Թող օրդ լավ երաժշտությամբ ուղեկցվի։',
    'Ու մի երգ լինի, որ նորից միացնես, {{firstName}}։',
  ),
  deskPair(
    'everyday-quiet-yes',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, թող այսօր լավ լուր լսես։',
    'Հատկապես այն կողմից, որտեղից չէիր սպասում։',
  ),
  deskPair(
    'everyday-window',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, մի փոքր բացահայտում եմ մաղթում։',
    'Գուցե հենց այն փողոցում, որով ամեն օր անցնում ես։',
  ),
  deskPair(
    'everyday-soft-landing',
    'everyday',
    'kindness',
    'Smile',
    'Ծանոթ դեմքը երբեմն օրը փոխում է։',
    'Թող այսօր հաճելի հանդիպում ունենաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-second-look',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, թող մի գեղեցիկ մանրուք նկատես։',
    'Այն, ինչի կողքով ուրիշ օրերին աննկատ անցնում ես։',
  ),
  deskPair(
    'everyday-shared-joke',
    'everyday',
    'humour',
    'Smile',
    'Մեկի հետ նույն բանի վրա ծիծաղելը լավ է։',
    'Թող այսօր այդպիսի ընկերակից ունենաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-warm-plate',
    'everyday',
    'pleasure',
    'Coffee',
    '{{firstName}}, թող ճաշդ այսօր հատկապես համեղ լինի։',
    'Այնքան, որ բաղադրատոմսն էլ ուզենաս իմանալ։',
  ),
  deskPair(
    'everyday-clear-sentence',
    'everyday',
    'words',
    'MessageCircle',
    'Թող մի պատասխան ամեն ինչ պարզեցնի։',
    'Ու ասես՝ «հիմա արդեն հասկացա», {{firstName}}։',
  ),
  deskPair(
    'everyday-unfinished-song',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, թող մի լավ մեղեդի ուղեկցի քեզ։',
    'Այնպիսին, որ ակամա սկսես քթի տակ երգել։',
  ),
  deskPair(
    'everyday-tiny-win',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, մի փոքր հաջողություն քեզ այսօր։',
    'Անհրաժեշտ բանը գտնես հենց անհրաժեշտ պահին։',
  ),
  deskPair(
    'everyday-good-timing',
    'everyday',
    'surprise',
    'Compass',
    'Թող ճիշտ պահին ճիշտ տեղում լինես։',
    'Օրինակ՝ հենց հերթը կարճացած լինի, {{firstName}}։',
  ),
  deskPair(
    'everyday-honest-chat',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, թող մեկը լավ բան խորհուրդ տա։',
    'Ու հետո ուրախ լինես, որ փորձեցիր։',
  ),
  deskPair(
    'everyday-page-turns',
    'everyday',
    'curiosity',
    'BookOpen',
    'Այսօր մի հետաքրքիր ընթերցանություն քեզ։',
    'Գուցե կարճ պատմություն, որ երկար հիշես, {{firstName}}։',
  ),
  deskPair(
    'everyday-light-pocket',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, թող ճանապարհիդ թարմ գաթա հանդիպի։',
    'Այն բույրով, որի կողքով դժվար է անտարբեր անցնել։',
  ),
  deskPair(
    'everyday-gentle-weather',
    'everyday',
    'kindness',
    'Sprout',
    '{{firstName}}, թող օրը սահուն անցնի։',
    'Մի քանի բան էլ ինքն իրեն իր տեղն ընկնի։',
  ),
  deskPair(
    'everyday-better-question',
    'everyday',
    'clarity',
    'Lightbulb',
    'Թող մի հարց հետաքրքրությունդ շարժի։',
    'Ու պատասխանը փնտրելիս նոր բան իմանաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-old-favourite',
    'everyday',
    'favourite',
    'Music',
    '{{firstName}}, թող մի հին սիրելի բան հիշես։',
    'Երգ, ֆիլմ կամ համ, որին վաղուց չէիր վերադարձել։',
  ),
] as const;
