import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_C = [
  deskPair('everyday-first-light', 'everyday', 'forward', 'Sparkles', '{{firstName}}, hope the first good thing arrives early.', 'It does not have to be large to set the tone.'),
  deskPair('everyday-borrowed-luck', 'everyday', 'surprise', 'Sparkles', 'Here’s to a little borrowed luck.', 'Pay it forward if you like, {{firstName}}.'),
  deskPair('everyday-clear-path', 'everyday', 'clarity', 'Compass', '{{firstName}}, may one path be obvious for once.', 'A straight line is allowed.'),
  deskPair('everyday-warm-mug', 'everyday', 'pleasure', 'Coffee', 'Hope the first warm thing you hold is pleasant.', 'Mug, bag, hand — any of those, {{firstName}}.'),
  deskPair('everyday-unread-joy', 'everyday', 'curiosity', 'BookOpen', '{{firstName}}, here’s to an unread joy nearby.', 'A chapter, a playlist, a street you have not walked.'),
  deskPair('everyday-easy-yes', 'everyday', 'surprise', 'Smile', 'May someone say yes without a meeting about it.', 'The short yes is a beautiful yes, {{firstName}}.'),
  deskPair('everyday-good-margin', 'everyday', 'pleasure', 'Sprout', '{{firstName}}, hope the day leaves a little margin.', 'A sliver of unclaimed time is still yours.'),
  deskPair('everyday-sharp-joke', 'everyday', 'humour', 'Smile', 'Here’s to a joke with no victims.', 'Just the lift, {{firstName}}.'),
  deskPair('everyday-found-rhythm', 'everyday', 'music', 'Music', '{{firstName}}, may the day find a rhythm you like.', 'Not a march. A tune you can keep.'),
  deskPair('everyday-kind-edit', 'everyday', 'words', 'MessageCircle', 'Hope a sentence gets the kindness of an edit.', 'Clearer is kinder, {{firstName}}.'),
  deskPair('everyday-nearby-yes', 'everyday', 'forward', 'Sparkles', '{{firstName}}, here’s to a yes sitting nearby.', 'Close enough to notice. Close enough to take.'),
  deskPair('everyday-small-ceremony', 'everyday', 'pleasure', 'Coffee', 'May something ordinary feel slightly ceremonial.', 'Lighting the kettle counts, {{firstName}}.'),
  deskPair('everyday-new-name', 'everyday', 'curiosity', 'Compass', '{{firstName}}, hope you learn a name worth keeping.', 'A person, a street, a dish, a tune.'),
  deskPair('everyday-gentle-nudge', 'everyday', 'kindness', 'Hand', 'Here’s to a nudge that is actually helpful.', 'The rare kind, {{firstName}}.'),
  deskPair('everyday-bright-aside', 'everyday', 'humour', 'Smile', '{{firstName}}, may an aside be the best part.', 'The comment in the margin often is.'),
  deskPair('everyday-open-circle', 'everyday', 'conversation', 'MessageCircle', 'Hope a circle opens and you fit without effort.', 'No performance required, {{firstName}}.'),
  deskPair('everyday-quiet-spark', 'everyday', 'clarity', 'Lightbulb', '{{firstName}}, here’s to a quiet spark of sense.', 'It does not need a spotlight to be useful.'),
  deskPair('everyday-sweet-ordinary', 'everyday', 'pleasure', 'Smile', 'May the ordinary taste slightly sweeter.', 'Bread, air, a joke, a walk, {{firstName}}.'),
  deskPair('everyday-next-chapter', 'everyday', 'story', 'BookOpen', '{{firstName}}, hope a next chapter looks inviting.', 'You do not have to start it today. Just see it.'),
  deskPair('everyday-good-signal', 'everyday', 'surprise', 'Sparkles', 'Here’s to a signal that is actually clear.', 'No static. No decoding, {{firstName}}.'),
  deskPair('everyday-held-door', 'everyday', 'kindness', 'Hand', '{{firstName}}, may a door be held for you.', 'Literal or otherwise. Both count.'),
  deskPair('everyday-late-sun', 'everyday', 'pleasure', 'Sunset', 'Hope the light does something kind later.', 'A late colour on a wall is enough, {{firstName}}.'),
  deskPair('everyday-curious-turn', 'everyday', 'curiosity', 'Compass', '{{firstName}}, here’s to a curious turn of thought.', 'The one that makes the next hour smarter.'),
  deskPair('everyday-human-pace', 'everyday', 'kindness', 'Smile', 'May the day keep a human pace somewhere.', 'One stretch that does not hurry you, {{firstName}}.'),
  deskPair('everyday-found-lyric', 'everyday', 'music', 'Music', '{{firstName}}, hope a lyric says it for you.', 'The line you did not know you needed.'),
  deskPair('everyday-small-return', 'everyday', 'favourite', 'Sparkles', 'Here’s to something good coming back around.', 'A person, a habit, a flavour, {{firstName}}.'),
  deskPair('everyday-open-hand', 'everyday', 'kindness', 'Hand', '{{firstName}}, may an open hand meet an open hand.', 'That is a fine shape for a day.'),
  deskPair('everyday-clean-joke', 'everyday', 'humour', 'Smile', 'Hope the funny thing is also kind.', 'Those last longer, {{firstName}}.'),
  deskPair('everyday-useful-wonder', 'everyday', 'curiosity', 'Lightbulb', '{{firstName}}, here’s to useful wonder.', 'Curiosity that actually helps.'),
  deskPair('everyday-quiet-treat', 'everyday', 'pleasure', 'Coffee', 'May a quiet treat be waiting somewhere.', 'You do not have to earn it first, {{firstName}}.'),
  deskPair('everyday-good-thread', 'everyday', 'conversation', 'MessageCircle', '{{firstName}}, hope a thread is worth following.', 'A chat, a thought, a tune — pick one.'),
  deskPair('everyday-evening-note', 'everyday', 'story', 'Sunset', 'Here’s to a day that ends on a decent note.', 'Not perfect. Just decent, {{firstName}}.'),
] as const;
