import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_A = [
  deskPair(
    'everyday-better-than-expected',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, may something go better than expected.',
    'Even a small, unexpected yes would do.',
  ),
  deskPair(
    'everyday-little-surprise',
    'everyday',
    'surprise',
    'Smile',
    'Here’s to a good little surprise.',
    'A kind message. A favourite song. Something just for you, {{firstName}}.',
  ),
  deskPair(
    'everyday-easy-thing',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, may one thing be easier than expected.',
    'A small favour from the day.',
  ),
  deskPair(
    'everyday-pleasant-detour',
    'everyday',
    'detour',
    'Compass',
    '{{firstName}}, here’s to a pleasant detour.',
    'Sometimes the unplanned bit makes the best story.',
  ),
  deskPair(
    'everyday-new-favourite',
    'everyday',
    'favourite',
    'Sparkles',
    '{{firstName}}, perhaps today brings a new favourite.',
    'A song, a place, or something you weren’t looking for.',
  ),
  deskPair(
    'everyday-looking-forward',
    'everyday',
    'forward',
    'Smile',
    'Here’s to having something to look forward to.',
    'Something small is more than enough, {{firstName}}.',
  ),
  deskPair(
    'everyday-idea',
    'everyday',
    'clarity',
    'Coffee',
    'May your best idea arrive without a struggle.',
    'Preferably while the coffee is still warm, {{firstName}}.',
  ),
  deskPair(
    'everyday-click',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, here’s to something finally making sense.',
    'That lovely moment when the pieces fit.',
  ),
  deskPair(
    'everyday-fresh-thought',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, hope a fresh thought finds you today.',
    'Perhaps from somewhere you wouldn’t normally look.',
  ),
  deskPair(
    'everyday-right-words',
    'everyday',
    'words',
    'MessageCircle',
    'Here’s to finding just the right words.',
    'And someone who understands what you mean, {{firstName}}.',
  ),
  deskPair(
    'everyday-good-conversation',
    'everyday',
    'conversation',
    'MessageCircle',
    'Hope a good conversation finds you today.',
    'One that leaves you with something to think about, {{firstName}}.',
  ),
  deskPair(
    'everyday-good-story',
    'everyday',
    'story',
    'MessageCircle',
    '{{firstName}}, hope today gives you a good story.',
    'The kind you want to tell someone later.',
  ),
  deskPair(
    'everyday-kindness',
    'everyday',
    'kindness',
    'Smile',
    'A little unexpected kindness would be nice today.',
    'Hope some finds its way to you, {{firstName}}.',
  ),
  deskPair(
    'everyday-small-pleasure',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, hope there’s something lovely in the ordinary.',
    'A good lunch counts. So does an unexpectedly good song.',
  ),
  deskPair(
    'everyday-laugh',
    'everyday',
    'humour',
    'Smile',
    'Hope something makes you laugh today, {{firstName}}.',
    'The sort of laugh that’s hard to explain afterwards.',
  ),
  deskPair(
    'everyday-music',
    'everyday',
    'music',
    'Music',
    'Hope today comes with a good soundtrack.',
    'And at least one song worth playing twice, {{firstName}}.',
  ),
  deskPair(
    'everyday-quiet-yes',
    'everyday',
    'surprise',
    'Sparkles',
    'Some good news would be lovely, {{firstName}}.',
    'Especially the kind you weren’t expecting to hear.',
  ),
  deskPair(
    'everyday-window',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, wishing you a day with something to discover.',
    'A place nearby that you’ve walked past a hundred times, perhaps.',
  ),
  deskPair(
    'everyday-soft-landing',
    'everyday',
    'kindness',
    'Smile',
    'A familiar face can make a day, {{firstName}}.',
    'Hope you get to see someone you’re always happy to meet.',
  ),
  deskPair(
    'everyday-second-look',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, hope you notice something you like today.',
    'A detail you’ve missed before, right there in the everyday.',
  ),
  deskPair(
    'everyday-shared-joke',
    'everyday',
    'humour',
    'Smile',
    'Here’s to laughing at the same thing, {{firstName}}.',
    'Even when neither of you can quite explain why.',
  ),
  deskPair(
    'everyday-warm-plate',
    'everyday',
    'pleasure',
    'Coffee',
    '{{firstName}}, hope lunch is worth looking forward to.',
    'Something delicious would make a very welcome highlight.',
  ),
  deskPair(
    'everyday-clear-sentence',
    'everyday',
    'words',
    'MessageCircle',
    'Wishing you an answer that clears things up.',
    'A simple explanation can be such a relief, {{firstName}}.',
  ),
  deskPair(
    'everyday-unfinished-song',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, hope a tune follows you around.',
    'The pleasant kind you do not mind humming twice.',
  ),
  deskPair(
    'everyday-tiny-win',
    'everyday',
    'surprise',
    'Sparkles',
    'A small stroke of luck for you, {{firstName}}.',
    'Finding exactly what you need, just when you need it.',
  ),
  deskPair(
    'everyday-good-timing',
    'everyday',
    'surprise',
    'Compass',
    '{{firstName}}, here’s to unusually good timing.',
    'Arriving just as the queue gets shorter would be a start.',
  ),
  deskPair(
    'everyday-honest-chat',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, hope someone shares a good recommendation.',
    'The sort you’re glad you took a chance on.',
  ),
  deskPair(
    'everyday-page-turns',
    'everyday',
    'curiosity',
    'BookOpen',
    'Something worth reading would be nice today.',
    'Hope you find a story you want to stay with, {{firstName}}.',
  ),
  deskPair(
    'everyday-light-pocket',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, hope you find a little treat today.',
    'Perhaps something from that bakery you keep walking past.',
  ),
  deskPair(
    'everyday-gentle-weather',
    'everyday',
    'kindness',
    'Sprout',
    '{{firstName}}, wishing you a day that goes smoothly.',
    'A few things falling into place would be lovely.',
  ),
  deskPair(
    'everyday-better-question',
    'everyday',
    'clarity',
    'Lightbulb',
    'Here’s to a question that gets you curious.',
    'The answer might take you somewhere interesting, {{firstName}}.',
  ),
  deskPair(
    'everyday-old-favourite',
    'everyday',
    'favourite',
    'Music',
    '{{firstName}}, here’s to an old favourite returning.',
    'The song or snack you forgot you missed.',
  ),
] as const;
