import { deskPair } from './desk-line-pair';

export const DESK_LINE_SEASONS_CATALOG = [
  deskPair('spring-new', 'season_spring', 'spring', 'Sprout', '{{firstName}}, here’s to something new this spring.', 'A small discovery you’ll be glad you made.'),
  deskPair('spring-room', 'season_spring', 'spring', 'Sprout', 'Hope spring brings room for something you enjoy.', 'An old favourite or a new curiosity, {{firstName}}.'),
  deskPair('spring-window', 'season_spring', 'spring', 'Sprout', '{{firstName}}, may spring leave a window open.', 'For a walk, a plan, or a thought that needs air.'),
  deskPair('spring-colour', 'season_spring', 'spring', 'Sprout', 'Here’s to a little more colour in the weeks.', 'Spring is good at that, {{firstName}}.'),
  deskPair('spring-return', 'season_spring', 'spring', 'Sprout', '{{firstName}}, hope something you like returns with the season.', 'A street, a habit, a flavour you forgot.'),
  deskPair('spring-light', 'season_spring', 'spring', 'Sparkles', 'May the longer light be kind to your evenings.', 'Even a few extra minutes count, {{firstName}}.'),
  deskPair('spring-start', 'season_spring', 'spring', 'Sprout', '{{firstName}}, here’s to a gentle start of something.', 'Spring is a good cover story for beginnings.'),
  deskPair('spring-air', 'season_spring', 'spring', 'Sprout', 'Hope the air feels a little more generous.', 'Open a window if you can, {{firstName}}.'),
  deskPair('spring-curiosity', 'season_spring', 'spring', 'Compass', '{{firstName}}, may spring make you slightly more curious.', 'A shop, a path, a page you would usually skip.'),
  deskPair('spring-green', 'season_spring', 'spring', 'Sprout', 'Here’s to noticing the first stubborn green.', 'It is a small, reliable miracle, {{firstName}}.'),
  deskPair('spring-plans', 'season_spring', 'spring', 'Smile', '{{firstName}}, hope a light plan finds you this season.', 'Nothing heavy. Just something pleasant to keep.'),
  deskPair('spring-market', 'season_spring', 'spring', 'Sprout', 'May a market, street, or table feel newly interesting.', 'Spring is good at rearranging the ordinary, {{firstName}}.'),
  deskPair('spring-letter', 'season_spring', 'spring', 'MessageCircle', '{{firstName}}, here’s to a message that feels like spring.', 'Short, bright, and better than expected.'),
  deskPair('spring-walk', 'season_spring', 'spring', 'Compass', 'Hope a walk earns its place this season.', 'Even a short one between doors, {{firstName}}.'),
  deskPair('spring-fresh', 'season_spring', 'spring', 'Sprout', '{{firstName}}, may something taste newly fresh.', 'Fruit, air, an idea — any of those will do.'),
  deskPair('spring-keep', 'season_spring', 'spring', 'Sprout', 'Here’s to one spring thing worth keeping.', 'A habit, a song, a place, {{firstName}}.'),

  deskPair('summer-room', 'season_summer', 'summer', 'Sun', '{{firstName}}, leave a little room for summer.', 'Here’s to long evenings with no particular plan.'),
  deskPair('summer-evening', 'season_summer', 'summer', 'Sunset', 'Hope there’s a lovely evening ahead, {{firstName}}.', 'The summer kind you’d happily make a little longer.'),
  deskPair('summer-flavour', 'season_summer', 'summer', 'Sun', '{{firstName}}, here’s to a little taste of summer.', 'Something fresh, something cold, something you really like.'),
  deskPair('summer-memory', 'season_summer', 'summer', 'Sun', 'Hope this summer gives you a good memory.', 'An ordinary day can become one too, {{firstName}}.'),
  deskPair('summer-shade', 'season_summer', 'summer', 'Sunset', '{{firstName}}, may a good patch of shade find you.', 'And something cold to go with it.'),
  deskPair('summer-late', 'season_summer', 'summer', 'Sunset', 'Here’s to a later evening than usual.', 'Summer is generous with those, {{firstName}}.'),
  deskPair('summer-street', 'season_summer', 'summer', 'Sun', '{{firstName}}, hope a street feels worth lingering on.', 'A door, a bench, a little leftover light.'),
  deskPair('summer-cold', 'season_summer', 'summer', 'Sun', 'May something cold and excellent reach you.', 'A drink, a plate, a slice of luck, {{firstName}}.'),
  deskPair('summer-window', 'season_summer', 'summer', 'Sun', '{{firstName}}, here’s to an open-window kind of day.', 'Air moving is already a small luxury.'),
  deskPair('summer-slow', 'season_summer', 'summer', 'Sunset', 'Hope one hour refuses to hurry.', 'That is a very summer talent, {{firstName}}.'),
  deskPair('summer-outside', 'season_summer', 'summer', 'Sun', '{{firstName}}, may a little of the day happen outside.', 'A step, a corner, a sky you actually notice.'),
  deskPair('summer-peach', 'season_summer', 'summer', 'Sun', 'Here’s to a flavour that tastes like the season.', 'Ripe, simple, and worth repeating, {{firstName}}.'),
  deskPair('summer-light-clothes', 'season_summer', 'summer', 'Sun', '{{firstName}}, hope the lighter days feel lighter.', 'Long light, thin air, and a little extra evening.'),
  deskPair('summer-gather', 'season_summer', 'summer', 'Smile', 'May good company find an easy evening.', 'Summer is built for that, {{firstName}}.'),
  deskPair('summer-horizon', 'season_summer', 'summer', 'Sunset', '{{firstName}}, here’s to a horizon that looks friendly.', 'Even from a balcony or a bus window.'),
  deskPair('summer-keep', 'season_summer', 'summer', 'Sun', 'Hope you keep one summer thing for later.', 'A photo, a joke, a place, {{firstName}}.'),

  deskPair('autumn-favourite', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, may this season bring a new favourite.', 'A place, a book, a small habit worth keeping.'),
  deskPair('autumn-pages', 'season_autumn', 'autumn', 'BookOpen', 'Here’s to a book that draws you in.', 'Something for an autumn evening, {{firstName}} — if that sounds like your kind of plan.'),
  deskPair('autumn-colour', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, hope autumn brings a little colour.', 'To the everyday things as much as the trees.'),
  deskPair('autumn-comfort', 'season_autumn', 'autumn', 'Leaf', 'Here’s to the small comforts of autumn.', 'Whatever yours happen to be, {{firstName}}.'),
  deskPair('autumn-lamp', 'season_autumn', 'autumn', 'Lightbulb', '{{firstName}}, may a lamp earn its keep this season.', 'Early light indoors has its own charm.'),
  deskPair('autumn-pocket', 'season_autumn', 'autumn', 'Leaf', 'Hope something warm fits in a pocket.', 'Hands, keys, a good thought, {{firstName}}.'),
  deskPair('autumn-return', 'season_autumn', 'autumn', 'BookOpen', '{{firstName}}, here’s to returning to a half-finished book.', 'Autumn is excellent at that invitation.'),
  deskPair('autumn-kitchen', 'season_autumn', 'autumn', 'Coffee', 'May a kitchen smell like a reason to stay in.', 'Soup is a perfectly serious plan, {{firstName}}.'),
  deskPair('autumn-walk', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, hope a walk collects a little colour.', 'Even a short one between two doors.'),
  deskPair('autumn-evening', 'season_autumn', 'autumn', 'Sunset', 'Here’s to evenings that arrive a bit earlier.', 'And still have room for you, {{firstName}}.'),
  deskPair('autumn-layer', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, may an extra layer feel like a friend.', 'The season’s most practical kindness.'),
  deskPair('autumn-quiet', 'season_autumn', 'autumn', 'BookOpen', 'Hope a quieter hour is easy to accept.', 'Autumn is good at making that feel natural, {{firstName}}.'),
  deskPair('autumn-market', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, here’s to a stall, shelf, or table of good things.', 'Apples are a respectable form of joy.'),
  deskPair('autumn-story', 'season_autumn', 'autumn', 'MessageCircle', 'May a longer story find you this season.', 'On a page or across a table, {{firstName}}.'),
  deskPair('autumn-gold', 'season_autumn', 'autumn', 'Leaf', '{{firstName}}, hope a little gold shows up in the week.', 'Leaves, light, a well-timed message.'),
  deskPair('autumn-keep', 'season_autumn', 'autumn', 'Leaf', 'Here’s to one autumn habit worth repeating.', 'Tea, pages, a later walk home, {{firstName}}.'),

  deskPair('winter-warmth', 'season_winter', 'winter', 'Coffee', '{{firstName}}, wishing you a little winter warmth.', 'A good meal and good company would be a lovely start.'),
  deskPair('winter-bright', 'season_winter', 'winter', 'Sparkles', 'Hope something brightens your winter day, {{firstName}}.', 'A message from someone you’re always glad to hear from, perhaps.'),
  deskPair('winter-table', 'season_winter', 'winter', 'Coffee', '{{firstName}}, may a table feel especially like shelter.', 'Winter is honest about how much that matters.'),
  deskPair('winter-light', 'season_winter', 'winter', 'Lightbulb', 'Here’s to indoor light doing its best work.', 'Lamps are underrated company, {{firstName}}.'),
  deskPair('winter-coat', 'season_winter', 'winter', 'Smile', '{{firstName}}, hope a coat, scarf, or room is kind.', 'The small architectures of warmth.'),
  deskPair('winter-broth', 'season_winter', 'winter', 'Coffee', 'May something hot and simple be enough.', 'Broth is a complete sentence, {{firstName}}.'),
  deskPair('winter-early', 'season_winter', 'winter', 'Sunset', '{{firstName}}, here’s to making peace with an early evening.', 'It can still hold a good hour.'),
  deskPair('winter-message', 'season_winter', 'winter', 'MessageCircle', 'Hope a warm message crosses the colder air.', 'Distance is less with a good line, {{firstName}}.'),
  deskPair('winter-window', 'season_winter', 'winter', 'Sparkles', '{{firstName}}, may a window give you a quiet view.', 'Steam, streetlights, a little weather to watch.'),
  deskPair('winter-return', 'season_winter', 'winter', 'Coffee', 'Here’s to coming back to a warm room.', 'That arrival is a whole event, {{firstName}}.'),
  deskPair('winter-slow', 'season_winter', 'winter', 'BookOpen', '{{firstName}}, hope a slower page feels welcome.', 'Winter is a natural accomplice to that.'),
  deskPair('winter-company', 'season_winter', 'winter', 'Smile', 'May good company make the season shorter.', 'Or at least brighter, {{firstName}}.'),
  deskPair('winter-citrus', 'season_winter', 'winter', 'Sparkles', '{{firstName}}, here’s to a bright flavour in a dark month.', 'Citrus is a tiny act of optimism.'),
  deskPair('winter-quiet', 'season_winter', 'winter', 'Leaf', 'Hope a quiet hour is allowed to stay quiet.', 'No need to decorate it, {{firstName}}.'),
  deskPair('winter-glove', 'season_winter', 'winter', 'Hand', '{{firstName}}, may the day meet you with warm hands.', 'Literal gloves count. So does a kind hello.'),
  deskPair('winter-keep', 'season_winter', 'winter', 'Coffee', 'Here’s to one winter comfort you can repeat.', 'The reliable kind, {{firstName}}.'),
] as const;
