import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_B = [
  deskPair('everyday-unexpected-colour', 'everyday', 'surprise', 'Sparkles', '{{firstName}}, hope the day has an unexpected colour.', 'A coat, a sky, a sentence that brightens the room.'),
  deskPair('everyday-two-minutes', 'everyday', 'pleasure', 'Coffee', 'Here’s to two unhurried minutes.', 'Long enough for the first sip to count, {{firstName}}.'),
  deskPair('everyday-kind-mirror', 'everyday', 'kindness', 'Smile', '{{firstName}}, may someone meet you kindly today.', 'Even a small, ordinary courtesy would do.'),
  deskPair('everyday-map-unfolds', 'everyday', 'detour', 'Compass', 'Hope the day unfolds a little sideways.', 'A useful detour is still a kind of luck, {{firstName}}.'),
  deskPair('everyday-name-remembered', 'everyday', 'kindness', 'Hand', '{{firstName}}, here’s to being remembered well.', 'A name said warmly is a good start.'),
  deskPair('everyday-clean-thought', 'everyday', 'clarity', 'Lightbulb', 'May one thought arrive already tidy.', 'No extra knots, {{firstName}}. Just the thought.'),
  deskPair('everyday-shared-silence', 'everyday', 'conversation', 'MessageCircle', '{{firstName}}, hope a comfortable silence finds you.', 'The kind that does not need filling.'),
  deskPair('everyday-street-music', 'everyday', 'music', 'Music', 'Here’s to music you did not choose.', 'A window, a car, a shop — and it still works, {{firstName}}.'),
  deskPair('everyday-good-crumb', 'everyday', 'pleasure', 'Smile', '{{firstName}}, may a small pleasure arrive unannounced.', 'A crumb of delight is still delight.'),
  deskPair('everyday-story-seed', 'everyday', 'story', 'MessageCircle', 'Hope today plants a story you will tell later.', 'It does not have to be dramatic, {{firstName}}.'),
  deskPair('everyday-right-tool', 'everyday', 'clarity', 'Lightbulb', '{{firstName}}, here’s to the right tool being nearby.', 'The one that turns a fiddle into a minute.'),
  deskPair('everyday-open-window', 'everyday', 'curiosity', 'Compass', 'May something interesting wander in.', 'A tab, a tip, a person with a better angle, {{firstName}}.'),
  deskPair('everyday-warm-hello', 'everyday', 'kindness', 'Hand', '{{firstName}}, hope a hello lands at the right time.', 'The ordinary kind that still steadies the hour.'),
  deskPair('everyday-half-smile', 'everyday', 'humour', 'Smile', 'Here’s to a half-smile that becomes a whole one.', 'Those are the best kind, {{firstName}}.'),
  deskPair('everyday-fresh-air', 'everyday', 'pleasure', 'Sprout', '{{firstName}}, may a little fresh air reach you.', 'A street, a stairwell, a walk between things.'),
  deskPair('everyday-puzzle-click', 'everyday', 'clarity', 'Lightbulb', 'Hope a stubborn piece finally clicks.', 'Quietly. Satisfyingly. For you, {{firstName}}.'),
  deskPair('everyday-good-company', 'everyday', 'conversation', 'MessageCircle', '{{firstName}}, here’s to company that is easy.', 'No performance. Just people who make sense.'),
  deskPair('everyday-saved-song', 'everyday', 'music', 'Music', 'May a song earn another play.', 'The replay is the compliment, {{firstName}}.'),
  deskPair('everyday-small-invite', 'everyday', 'forward', 'Smile', '{{firstName}}, hope something small is worth circling.', 'A plan that fits in one line is still a plan.'),
  deskPair('everyday-lost-and-found', 'everyday', 'surprise', 'Sparkles', 'Here’s to finding what you were not hunting.', 'A thought, a coin, a better way, {{firstName}}.'),
  deskPair('everyday-neat-ending', 'everyday', 'clarity', 'Compass', '{{firstName}}, may one thing finish cleanly.', 'A tidy close is an underrated pleasure.'),
  deskPair('everyday-kind-weather-inside', 'everyday', 'kindness', 'Smile', 'Hope the people around you are easy weather.', 'A calm room is a gift, {{firstName}}.'),
  deskPair('everyday-new-route', 'everyday', 'detour', 'Compass', '{{firstName}}, here’s to a slightly different route.', 'Same destination, better scenery.'),
  deskPair('everyday-notebook', 'everyday', 'curiosity', 'BookOpen', 'May a line be worth writing down.', 'One sentence can hold the day, {{firstName}}.'),
  deskPair('everyday-shared-table', 'everyday', 'pleasure', 'Coffee', '{{firstName}}, hope a table feels welcoming.', 'Food tastes better when the seat is right.'),
  deskPair('everyday-light-remark', 'everyday', 'humour', 'Smile', 'Here’s to a remark that lightens the room.', 'Not a speech. Just a well-placed line, {{firstName}}.'),
  deskPair('everyday-hidden-door', 'everyday', 'curiosity', 'Compass', '{{firstName}}, may a hidden door be slightly ajar.', 'Enough to peek. Enough to be interesting.'),
  deskPair('everyday-steady-hand', 'everyday', 'kindness', 'Hand', 'Hope a steady hand is nearby if you need one.', 'Asking is allowed, {{firstName}}.'),
  deskPair('everyday-bright-object', 'everyday', 'surprise', 'Sparkles', '{{firstName}}, here’s to one bright object in the day.', 'A colour, a sentence, a face you like seeing.'),
  deskPair('everyday-good-pause', 'everyday', 'pleasure', 'Sunset', 'May a pause arrive before you have to invent one.', 'The useful kind, {{firstName}}. Not the empty kind.'),
  deskPair('everyday-echo', 'everyday', 'conversation', 'MessageCircle', '{{firstName}}, hope something you say is heard well.', 'Understood is better than impressive.'),
  deskPair('everyday-later-smile', 'everyday', 'story', 'Smile', 'Here’s to a moment you will smile at later.', 'Today can store those quietly, {{firstName}}.'),
] as const;
