import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_B = [
  deskPair(
    'everyday-unexpected-colour',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, թող աչքդ մի գեղեցիկ գույն որսա։',
    'Պատուհանի ծաղիկը կամ մի սիրուն ցուցափեղկ։',
  ),
  deskPair(
    'everyday-two-minutes',
    'everyday',
    'pleasure',
    'Coffee',
    'Մի քանի հանգիստ րոպե սուրճի համար։',
    'Որ առաջին կումի համն իսկապես զգաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-kind-mirror',
    'everyday',
    'kindness',
    'Smile',
    '{{firstName}}, թող այսօր քեզ սիրալիր դիմավորեն։',
    'Սովորական բարևն էլ կարող է ջերմ լինել։',
  ),
  deskPair(
    'everyday-map-unfolds',
    'everyday',
    'detour',
    'Compass',
    '{{firstName}}, թող մի լավ հասցե բացահայտես։',
    'Մի տեղ, ուր հետո ընկերներիդ էլ կտանես։',
  ),
  deskPair(
    'everyday-name-remembered',
    'everyday',
    'kindness',
    'Hand',
    'Հաճելի է, երբ քեզ հիշում են։',
    'Թող այսօր անունդ ջերմությամբ հնչի, {{firstName}}։',
  ),
  deskPair(
    'everyday-clean-thought',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, թող բարդ թվացածը պարզ լուծում ունենա։',
    'Ու վերջում զարմանաս՝ ինչքան հեշտ էր։',
  ),
  deskPair(
    'everyday-shared-silence',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, քեզ լավ ընկերակցություն եմ մաղթում։',
    'Երբ նույնիսկ լռելն է հարմար ու հաճելի։',
  ),
  deskPair(
    'everyday-street-music',
    'everyday',
    'music',
    'Music',
    'Թող պատահաբար մի լավ երգ լսես։',
    'Սրճարանում, մեքենայում կամ բաց պատուհանից, {{firstName}}։',
  ),
  deskPair(
    'everyday-good-crumb',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, թող այսօր նոր համ բացահայտես։',
    'Մաղթում եմ՝ հենց առաջին պատառից դուր գա։',
  ),
  deskPair(
    'everyday-story-seed',
    'everyday',
    'story',
    'MessageCircle',
    'Թող մեկը հետաքրքիր պատմություն պատմի։',
    'Այնպիսին, որ տուն գնալիս էլ հիշես, {{firstName}}։',
  ),
  deskPair(
    'everyday-right-tool',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, թող մի օգտակար հնարք իմանաս։',
    'Ու մտածես՝ ինչո՞ւ ավելի շուտ չգիտեի։',
  ),
  deskPair(
    'everyday-open-window',
    'everyday',
    'curiosity',
    'Compass',
    'Մի հետաքրքիր նյութ թող պատահի այսօր։',
    'Որ կարդալուց հետո էլ մտածելու բան մնա, {{firstName}}։',
  ),
  deskPair(
    'everyday-warm-hello',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, թող մի հարազատ ձայն լսես։',
    'Թեկուզ կարճ զանգ լինի, բայց օրը ջերմացնի։',
  ),
  deskPair(
    'everyday-half-smile',
    'everyday',
    'humour',
    'Smile',
    'Երբեմն ամենապարզ կատակն է ամենածիծաղելին։',
    'Թող այսօր քեզ էլ այդպիսին բաժին հասնի, {{firstName}}։',
  ),
  deskPair(
    'everyday-fresh-air',
    'everyday',
    'pleasure',
    'Sprout',
    '{{firstName}}, դրսում մի հաճելի պահ եմ մաղթում։',
    'Մի փոքր զբոսանք ու տեսարանի փոփոխություն։',
  ),
  deskPair(
    'everyday-puzzle-click',
    'everyday',
    'clarity',
    'Lightbulb',
    'Թող մտաբերես այն մոռացված բառը։',
    'Անունը, երգը կամ հասցեն, որ լեզվիդ ծայրին էր, {{firstName}}։',
  ),
  deskPair(
    'everyday-good-company',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, թող ընկերներիդ հետ հանդիպում ստացվի։',
    'Որ պարզապես նստեք ու իրարից լուր առնեք։',
  ),
  deskPair(
    'everyday-saved-song',
    'everyday',
    'music',
    'Music',
    'Հին երգացանկում գուցե լավ բան սպասի։',
    'Թող նորից գտնես վաղուց չլսած սիրելի երգդ, {{firstName}}։',
  ),
  deskPair(
    'everyday-small-invite',
    'everyday',
    'forward',
    'Smile',
    '{{firstName}}, թող հաճելի հրավեր ստանաս։',
    'Այնպիսին, որ լսելիս միանգամից ուզենաս գնալ։',
  ),
  deskPair(
    'everyday-lost-and-found',
    'everyday',
    'surprise',
    'Sparkles',
    'Թող կորած համարածդ բանը գտնվի։',
    'Ու ցանկալի է՝ հենց առաջին փնտրածդ տեղում, {{firstName}}։',
  ),
  deskPair(
    'everyday-neat-ending',
    'everyday',
    'clarity',
    'Compass',
    '{{firstName}}, թող մի հարց այսօր իր պատասխանը գտնի։',
    'Ու մտքիդ մեջ մի քիչ ավելի պարզություն լինի։',
  ),
  deskPair(
    'everyday-kind-weather-inside',
    'everyday',
    'kindness',
    'Smile',
    'Թող այսօր քեզ համբերությամբ լսեն։',
    'Առանց շտապեցնելու ու խոսքդ կիսատ թողնելու, {{firstName}}։',
  ),
  deskPair(
    'everyday-new-route',
    'everyday',
    'detour',
    'Compass',
    '{{firstName}}, գուցե ուրիշ ճանապարհը հաճելի լինի։',
    'Նույն տեղը հասնես, բայց մի նոր բան տեսնես։',
  ),
  deskPair(
    'everyday-notebook',
    'everyday',
    'curiosity',
    'BookOpen',
    'Թող գրի առնելու արժանի միտք գտնես։',
    'Այնպիսին, որ հետո հաճույքով վերակարդաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-shared-table',
    'everyday',
    'pleasure',
    'Coffee',
    '{{firstName}}, լավ սեղան ու լավ զրույց եմ մաղթում։',
    'Երբ ուտելիքն ավարտվում է, բայց զրույցը՝ ոչ։',
  ),
  deskPair(
    'everyday-light-remark',
    'everyday',
    'humour',
    'Smile',
    'Թող մեկի խոսքը ժպիտ առաջացնի։',
    'Երբեմն մի նախադասությունն էլ բավական է, {{firstName}}։',
  ),
  deskPair(
    'everyday-hidden-door',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, գուցե սիրելի նոր տեղդ մոտակայքում է։',
    'Թող այսօր այն գտնելու առիթ լինի։',
  ),
  deskPair(
    'everyday-steady-hand',
    'everyday',
    'kindness',
    'Hand',
    'Թող օգնությունը ճիշտ պահին հասնի։',
    'Մեկից, ով գիտի՝ որտեղից սկսել, {{firstName}}։',
  ),
  deskPair(
    'everyday-bright-object',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, թող նկարելու արժանի պահ նկատես։',
    'Թեկուզ լուսանկարը միայն քեզ համար պահես։',
  ),
  deskPair(
    'everyday-good-pause',
    'everyday',
    'pleasure',
    'Sunset',
    'Մի գեղեցիկ տեսարանի համար կանգ առնելու պահ։',
    'Թող այդպիսի պահ ունենաս այսօր, {{firstName}}։',
  ),
  deskPair(
    'everyday-echo',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, թող այսօր քեզ ճիշտ հասկանան։',
    'Հաճելի է, երբ երկար բացատրելու կարիք չկա։',
  ),
  deskPair(
    'everyday-later-smile',
    'everyday',
    'story',
    'Smile',
    'Թող օրվանից մի ժպիտ հիշատակ մնա։',
    'Մի պահ, որ երեկոյան էլ հաճույքով հիշես, {{firstName}}։',
  ),
] as const;
