import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_C = [
  deskPair(
    'everyday-first-light',
    'everyday',
    'forward',
    'Sparkles',
    '{{firstName}}, թող բարի խոսքը ճիշտ պահին հնչի։',
    'Հենց այն ժամանակ, երբ լսելը հաճելի կլինի։',
  ),
  deskPair(
    'everyday-borrowed-luck',
    'everyday',
    'surprise',
    'Sparkles',
    'Թող ուզածդ բանը դեռ մնացած լինի։',
    'Վերջին կտորը, հարմար չափսը կամ լավ նստատեղը, {{firstName}}։',
  ),
  deskPair(
    'everyday-clear-path',
    'everyday',
    'clarity',
    'Compass',
    '{{firstName}}, թող ընտրությունդ հեշտ լինի։',
    'Երբ մի տարբերակն ուղղակի սրտովդ է։',
  ),
  deskPair(
    'everyday-warm-mug',
    'everyday',
    'pleasure',
    'Coffee',
    'Մի լավ բաժակ սուրճ կամ թեյ քեզ։',
    'Հենց այնպես պատրաստված, ինչպես սիրում ես, {{firstName}}։',
  ),
  deskPair(
    'everyday-unread-joy',
    'everyday',
    'curiosity',
    'BookOpen',
    '{{firstName}}, թող հաջորդ գիրքդ լավը լինի։',
    'Գուցե մեկը խորհուրդ տա, ումից չէիր սպասում։',
  ),
  deskPair(
    'everyday-easy-yes',
    'everyday',
    'surprise',
    'Smile',
    'Թող հանդիպման օրը հեշտ համաձայնեցնեք։',
    'Բոլորն էլ նույն օրը ազատ լինեն, {{firstName}}։',
  ),
  deskPair(
    'everyday-good-margin',
    'everyday',
    'pleasure',
    'Sprout',
    '{{firstName}}, թող սիրածդ բանի համար ժամանակ գտնվի։',
    'Մի փոքր զբաղմունք՝ պարզապես քո հաճույքի համար։',
  ),
  deskPair(
    'everyday-sharp-joke',
    'everyday',
    'humour',
    'Smile',
    'Մի լավ ծիծաղ՝ ընկերոջ հետ կիսելու համար։',
    'Թող այսօր ուղարկելու զվարճալի բան գտնես, {{firstName}}։',
  ),
  deskPair(
    'everyday-found-rhythm',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, թող նոր երգիչ բացահայտես։',
    'Ու պարզվի՝ դեռ շատ լավ երգեր ունի լսելու։',
  ),
  deskPair(
    'everyday-kind-edit',
    'everyday',
    'words',
    'MessageCircle',
    'Թող ջերմ հաղորդագրություն ստանաս այսօր։',
    'Այնպիսին, որ մի քանի անգամ կարդաս, {{firstName}}։',
  ),
  deskPair(
    'everyday-nearby-yes',
    'everyday',
    'forward',
    'Sparkles',
    '{{firstName}}, թող ոգևորվելու մի լավ առիթ լինի։',
    'Օրացույցում մի օր, որին հաճույքով սպասես։',
  ),
  deskPair(
    'everyday-small-ceremony',
    'everyday',
    'pleasure',
    'Coffee',
    'Փոքրիկ սովորություններն էլ իրենց հաճույքն ունեն։',
    'Թող քո սիրելի բաժակով սուրճը համով լինի, {{firstName}}։',
  ),
  deskPair(
    'everyday-new-name',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, թող մի հետաքրքիր բառ իմանաս։',
    'Ու նույն օրը օգտագործելու առիթ ունենաս։',
  ),
  deskPair(
    'everyday-gentle-nudge',
    'everyday',
    'kindness',
    'Hand',
    'Թող մեկի խորհուրդը տեղին լինի։',
    'Գուցե պարզ ու լավ տարբերակ առաջարկի, {{firstName}}։',
  ),
  deskPair(
    'everyday-bright-aside',
    'everyday',
    'humour',
    'Smile',
    '{{firstName}}, թող սովորական զրույցը զվարճալի դառնա։',
    'Այդպիսի հանդիպումներն են հաճախ երկար հիշվում։',
  ),
  deskPair(
    'everyday-open-circle',
    'everyday',
    'conversation',
    'MessageCircle',
    'Թող հետաքրքիր մարդու հետ ծանոթանաս։',
    'Ու խոսելու ընդհանուր թեմա անմիջապես գտնվի, {{firstName}}։',
  ),
  deskPair(
    'everyday-quiet-spark',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, թող ծանոթ բանի մեջ նորը տեսնես։',
    'Երբեմն մի ուրիշ հայացքն էլ բավական է։',
  ),
  deskPair(
    'everyday-sweet-ordinary',
    'everyday',
    'pleasure',
    'Smile',
    'Այսօր մի քաղցր բան քեզ, {{firstName}}։',
    'Թող սիրածդ աղանդերը հենց պատրաստ լինի։',
  ),
  deskPair(
    'everyday-next-chapter',
    'everyday',
    'story',
    'BookOpen',
    '{{firstName}}, թող պատմությունը շարունակելու ցանկություն մնա։',
    'Ու հաջորդ գիրքը կամ ֆիլմն արդեն հասանելի լինի։',
  ),
  deskPair(
    'everyday-good-signal',
    'everyday',
    'surprise',
    'Sparkles',
    'Թող պատասխանը քեզ ուրախացնի, {{firstName}}։',
    'Հատկապես եթե վաղուց էիր դրան սպասում։',
  ),
  deskPair(
    'everyday-held-door',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, փոքրիկ բարություն եմ մաղթում այսօր։',
    'Մի բաց պահած դուռ կամ հոգատար հարց։',
  ),
  deskPair(
    'everyday-late-sun',
    'everyday',
    'pleasure',
    'Sunset',
    'Թող օրը հաճելի ավարտ ունենա։',
    'Տանը սիրածդ ուտեստը կամ մի լավ ֆիլմ, {{firstName}}։',
  ),
  deskPair(
    'everyday-curious-turn',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, թող նոր բան սովորելու առիթ լինի։',
    'Ու բացատրողն էլ հետաքրքիր պատմի։',
  ),
  deskPair(
    'everyday-human-pace',
    'everyday',
    'kindness',
    'Smile',
    'Թող հերթը սպասածից արագ առաջ գնա։',
    'Խնայած մի քանի րոպեն էլ հաճելի է, {{firstName}}։',
  ),
  deskPair(
    'everyday-found-lyric',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, թող երգը քո փոխարեն խոսի։',
    'Երբ լսում ես ու մտածում՝ հենց սա էի ուզում ասել։',
  ),
  deskPair(
    'everyday-small-return',
    'everyday',
    'favourite',
    'Sparkles',
    'Գուցե հին սիրելի բանին վերադառնալու օր է։',
    'Թող նույնքան լավը լինի, որքան հիշում էիր, {{firstName}}։',
  ),
  deskPair(
    'everyday-open-hand',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, թող մեկը սիրով կիսվի քեզ հետ։',
    'Լավ գաղափարով կամ թխվածքի վերջին կտորով։',
  ),
  deskPair(
    'everyday-clean-joke',
    'everyday',
    'humour',
    'Smile',
    'Թող մի անսպասելի զվարճալի պահ պատահի։',
    'Առանց պատրաստած կատակի էլ կարելի է լավ ծիծաղել, {{firstName}}։',
  ),
  deskPair(
    'everyday-useful-wonder',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, թող մի հարմար նոր ձև գտնես։',
    'Փոքրիկ փոփոխություն, որ առօրյադ հեշտացնի։',
  ),
  deskPair(
    'everyday-quiet-treat',
    'everyday',
    'pleasure',
    'Coffee',
    'Թարմ թխվածքի բույրը լավ անակնկալ է։',
    'Թող հենց ջեռոցից հանելու պահին հասնես, {{firstName}}։',
  ),
  deskPair(
    'everyday-good-thread',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, թող զրույցը շարունակելու ցանկություն լինի։',
    'Որ երկուսիդ էլ հետաքրքիր լինի լսել ու պատմել։',
  ),
  deskPair(
    'everyday-evening-note',
    'everyday',
    'story',
    'Sunset',
    'Թող օրը սիրով հիշելու բան ունենա։',
    'Գոնե մի պահ, որ կուզենայիր կրկնել, {{firstName}}։',
  ),
] as const;
