import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVENTS_CATALOG = [
  deskPair(
    'birthday-yours',
    'birthday',
    'birthday',
    'Cake',
    '{{firstName}}, may today feel unmistakably yours.',
    'Happy birthday — with your favourite people and your kind of plans.',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-year',
    'birthday',
    'birthday',
    'Cake',
    'Happy birthday, {{firstName}}. Here’s to a lovely year.',
    'With good surprises and plenty to look forward to.',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-table',
    'birthday',
    'birthday',
    'Cake',
    '{{firstName}}, wishing you a birthday full of your favourites.',
    'Good food, lovely company, and plans that suit you.',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-story',
    'birthday',
    'birthday',
    'Cake',
    'Happy birthday, {{firstName}}. Hope it’s one to remember.',
    'For the lovely moments, both planned and unexpected.',
    { tone: 'festive' },
  ),

  deskPair(
    'birthday-memorial-quiet',
    'birthday_memorial',
    'birthday',
    'Smile',
    '{{firstName}}, wishing you a gentle birthday.',
    'A quiet day can still be unmistakably yours.',
    { tone: 'memorial' },
  ),
  deskPair(
    'birthday-memorial-kind',
    'birthday_memorial',
    'birthday',
    'Hand',
    'Happy birthday, {{firstName}}. Wishing you a peaceful one.',
    'With the people and the pace that suit you.',
    { tone: 'memorial' },
  ),

  deskPair(
    'first-day-welcome',
    'first_day',
    'first-day',
    'Hand',
    '{{firstName}}, it’s good to have you here.',
    'Here’s to unfamiliar faces becoming familiar ones.',
    { tone: 'warm' },
  ),
  deskPair(
    'first-day-names',
    'first_day',
    'first-day',
    'Hand',
    'Welcome, {{firstName}}. It’s lovely to meet you.',
    'Wishing you a good first day with the team.',
    { tone: 'warm' },
  ),
  deskPair(
    'first-day-corner',
    'first_day',
    'first-day',
    'Compass',
    '{{firstName}}, here’s to a good beginning together.',
    'Hope your first day brings a few friendly conversations.',
    { tone: 'warm' },
  ),

  deskPair(
    'first-day-memorial',
    'first_day_memorial',
    'first-day',
    'Hand',
    '{{firstName}}, it’s good to have you here.',
    'Take the day as it comes. We are glad you arrived.',
    { tone: 'memorial' },
  ),

  deskPair(
    'anniversary-one',
    'anniversary_one',
    'anniversary',
    'PartyPopper',
    'A year together, {{firstName}}. Thank you.',
    'Happy first work anniversary. It’s good to have you here.',
    { tone: 'festive' },
  ),
  deskPair(
    'anniversary-one-quiet',
    'anniversary_one',
    'anniversary',
    'Smile',
    '{{firstName}}, one year together. Glad you’re here.',
    'Happy first work anniversary, and thank you for being part of the team.',
    { tone: 'warm' },
  ),
  deskPair(
    'anniversary-one-company',
    'anniversary_one',
    'anniversary',
    'Hand',
    'A year of good company, {{firstName}}. Thank you.',
    'Happy first work anniversary.',
    { tone: 'warm' },
  ),

  deskPair(
    'anniversary-many',
    'anniversary_many',
    'anniversary',
    'PartyPopper',
    '{{years}} years together, {{firstName}}. Thank you.',
    'Happy work anniversary. Here’s to good company along the way.',
    { tone: 'festive' },
  ),
  deskPair(
    'anniversary-many-kept',
    'anniversary_many',
    'anniversary',
    'Smile',
    '{{firstName}}, {{years}} years here. That is no small thing.',
    'Happy work anniversary — and thank you.',
    { tone: 'warm' },
  ),
  deskPair(
    'anniversary-many-along',
    'anniversary_many',
    'anniversary',
    'Hand',
    '{{firstName}}, thank you for {{years}} years together.',
    'Wishing you a happy work anniversary and good things ahead.',
    { tone: 'warm' },
  ),

  deskPair(
    'anniversary-memorial',
    'anniversary_memorial',
    'anniversary',
    'Hand',
    '{{firstName}}, thank you for being here.',
    'A quiet note for a work anniversary. We are glad you are with us.',
    { tone: 'memorial' },
  ),

  deskPair(
    'onboarding-3',
    'onboarding_3',
    'onboarding',
    'Hand',
    '{{firstName}}, hope each day feels a little more familiar.',
    'A few more names, a few more friendly faces.',
  ),
  deskPair(
    'onboarding-3-map',
    'onboarding_3',
    'onboarding',
    'Compass',
    '{{firstName}}, wishing you a good start with the team.',
    'Hope there’s a friendly face whenever you have a question.',
  ),
  deskPair(
    'onboarding-3-faces',
    'onboarding_3',
    'onboarding',
    'Smile',
    'Here’s to getting to know each other, {{firstName}}.',
    'Hope your first few days bring some easy conversations.',
  ),

  deskPair(
    'onboarding-10',
    'onboarding_10',
    'onboarding',
    'Compass',
    'Here’s to finding your own way, {{firstName}}.',
    'And having someone to ask when you need a hand.',
  ),
  deskPair(
    'onboarding-10-ask',
    'onboarding_10',
    'onboarding',
    'Hand',
    '{{firstName}}, hope you’re finding your feet here.',
    'Wishing you helpful answers and people you feel comfortable asking.',
  ),
  deskPair(
    'onboarding-10-shape',
    'onboarding_10',
    'onboarding',
    'Compass',
    '{{firstName}}, it’s good to be getting to know you.',
    'Hope the introductions are turning into familiar faces.',
  ),

  deskPair(
    'onboarding-21',
    'onboarding_21',
    'onboarding',
    'Smile',
    '{{firstName}}, hope there have been some good surprises.',
    'It’s good to have you as part of the team.',
  ),
  deskPair(
    'onboarding-21-team',
    'onboarding_21',
    'onboarding',
    'Hand',
    'Three weeks with us, {{firstName}}. Glad you’re here.',
    'Here’s to more good conversations with the team.',
  ),
  deskPair(
    'onboarding-21-keep',
    'onboarding_21',
    'onboarding',
    'Smile',
    '{{firstName}}, hope it’s starting to feel familiar here.',
    'A few people to turn to and a few things to look forward to.',
  ),

  deskPair(
    'book-hard-to-leave',
    'cultural',
    'books',
    'BookOpen',
    '{{firstName}}, may your next book be hard to put down.',
    'It’s World Book Day. Here’s to “just one more page.”',
    { eventId: 'world-book-day', tone: 'warm' },
  ),
  deskPair(
    'book-evening',
    'cultural',
    'books',
    'BookOpen',
    'Here’s to a book you’ll want to recommend.',
    'World Book Day is a lovely occasion to find one, {{firstName}}.',
    { eventId: 'world-book-day', tone: 'warm' },
  ),
  deskPair(
    'book-finds-you',
    'cultural',
    'books',
    'BookOpen',
    '{{firstName}}, hope a book finds you at the right time.',
    'World Book Day — even one good page would do.',
    { eventId: 'world-book-day', tone: 'warm' },
  ),

  deskPair(
    'music-soundtrack',
    'cultural',
    'music',
    'Music',
    '{{firstName}}, wishing you a day with a great soundtrack.',
    'It’s International Music Day. Hope an old favourite gets a play.',
    { eventId: 'international-music-day', tone: 'warm' },
  ),
  deskPair(
    'music-twice',
    'cultural',
    'music',
    'Music',
    'Here’s to a song worth playing twice.',
    'Happy International Music Day, {{firstName}}. Maybe three times, if it’s that good.',
    { eventId: 'international-music-day', tone: 'warm' },
  ),
  deskPair(
    'music-finds-you',
    'cultural',
    'music',
    'Music',
    '{{firstName}}, hope you discover a song you love today.',
    'A little something to remember International Music Day by.',
    { eventId: 'international-music-day', tone: 'warm' },
  ),

  deskPair(
    'new-year-surprises',
    'cultural',
    'new-year',
    'Sparkles',
    '{{firstName}}, here’s to a year with good surprises.',
    'Happy New Year. Hope there’s plenty in it for you.',
    { eventId: 'new-year', tone: 'festive' },
  ),
  deskPair(
    'new-year-pages',
    'cultural',
    'new-year',
    'Sparkles',
    'Happy New Year, {{firstName}}. Here’s to good things ahead.',
    'New places to discover and familiar people to enjoy them with.',
    { eventId: 'new-year', tone: 'festive' },
  ),
  deskPair(
    'new-year-kind',
    'cultural',
    'new-year',
    'Smile',
    '{{firstName}}, wishing you a year with plenty of happy moments.',
    'Happy New Year. Hope it gives you some lovely memories.',
    { eventId: 'new-year', tone: 'festive' },
  ),

  deskPair(
    'new-year-eve-close',
    'cultural',
    'new-year',
    'Sparkles',
    '{{firstName}}, wishing you a lovely end to the year.',
    'And something to look forward to in the next one.',
    { eventId: 'new-year-eve', tone: 'festive' },
  ),
  deskPair(
    'new-year-eve-light',
    'cultural',
    'new-year',
    'Sparkles',
    'One last day of the year, {{firstName}}.',
    'Hope there’s still a pleasant surprise in it for you.',
    { eventId: 'new-year-eve', tone: 'warm' },
  ),
  deskPair(
    'new-year-eve-forward',
    'cultural',
    'new-year',
    'Smile',
    '{{firstName}}, here’s to welcoming a new year.',
    'Wishing you a good evening, whatever your plans.',
    { eventId: 'new-year-eve', tone: 'warm' },
  ),

  deskPair(
    'independence-quiet',
    'cultural',
    'armenia',
    'Sparkles',
    '{{firstName}}, wishing you a lovely Independence Day.',
    'Hope there’s time for something you enjoy today.',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),
  deskPair(
    'independence-company',
    'cultural',
    'armenia',
    'Smile',
    'Here’s to good company this Independence Day, {{firstName}}.',
    'A shared meal or a friendly conversation would be lovely.',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),
  deskPair(
    'independence-here',
    'cultural',
    'armenia',
    'Hand',
    '{{firstName}}, warm wishes for Independence Day.',
    'Hope the day brings a few moments you’ll be glad to remember.',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),

  deskPair(
    'memorial-peaceful',
    'memorial_neutral',
    'peaceful',
    'None',
    'Wishing you a peaceful day, {{firstName}}.',
    'A little room for what matters to you.',
    { tone: 'memorial' },
  ),
  deskPair(
    'memorial-room',
    'memorial_neutral',
    'peaceful',
    'None',
    '{{firstName}}, wishing you a peaceful day ahead.',
    'With time for the people and things that matter to you.',
    { tone: 'memorial' },
  ),
  deskPair(
    'memorial-plain',
    'memorial_neutral',
    'peaceful',
    'None',
    'Wishing you a quiet moment today.',
    'And a little space for what matters most.',
    { tone: 'memorial' },
  ),
] as const;
