import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_C = [
  deskPair(
    'everyday-first-light',
    'everyday',
    'forward',
    'Sparkles',
    '{{firstName}}, wishing you something good at the right moment.',
    'A little encouragement just when it would be welcome.',
  ),
  deskPair(
    'everyday-borrowed-luck',
    'everyday',
    'surprise',
    'Sparkles',
    'Hope the thing you want is still available.',
    'The last slice, the right size, the good seat, {{firstName}}.',
  ),
  deskPair(
    'everyday-clear-path',
    'everyday',
    'clarity',
    'Compass',
    '{{firstName}}, may a decision turn out to be easy.',
    'It’s nice when one option simply feels right.',
  ),
  deskPair(
    'everyday-warm-mug',
    'everyday',
    'pleasure',
    'Coffee',
    'Wishing you a very good cup of something.',
    'Made just the way you like it, {{firstName}}.',
  ),
  deskPair(
    'everyday-unread-joy',
    'everyday',
    'curiosity',
    'BookOpen',
    '{{firstName}}, hope you find your next good read.',
    'Perhaps from someone whose taste you’ve never tried before.',
  ),
  deskPair(
    'everyday-easy-yes',
    'everyday',
    'surprise',
    'Smile',
    'Hope a plan comes together easily, {{firstName}}.',
    'Everyone free on the same day? That would be something.',
  ),
  deskPair(
    'everyday-good-margin',
    'everyday',
    'pleasure',
    'Sprout',
    '{{firstName}}, hope there’s time for something you enjoy.',
    'A small plan that’s just for you.',
  ),
  deskPair(
    'everyday-sharp-joke',
    'everyday',
    'humour',
    'Smile',
    'Wishing you a laugh you can share, {{firstName}}.',
    'Something funny enough to send to a friend.',
  ),
  deskPair(
    'everyday-found-rhythm',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, hope you discover a musician you like.',
    'And find out there’s a whole album to explore.',
  ),
  deskPair(
    'everyday-kind-edit',
    'everyday',
    'words',
    'MessageCircle',
    'Hope a message arrives just as you need it.',
    'A kind word can stay with you all day, {{firstName}}.',
  ),
  deskPair(
    'everyday-nearby-yes',
    'everyday',
    'forward',
    'Sparkles',
    '{{firstName}}, wishing you something to get excited about.',
    'A date in the diary you’ll be glad to see coming.',
  ),
  deskPair(
    'everyday-small-ceremony',
    'everyday',
    'pleasure',
    'Coffee',
    'Here’s to enjoying the little rituals, {{firstName}}.',
    'A favourite cup or a song on the way home.',
  ),
  deskPair(
    'everyday-new-name',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, hope you learn something delightfully unexpected.',
    'A new word, perhaps, that you’ll want to use straight away.',
  ),
  deskPair(
    'everyday-gentle-nudge',
    'everyday',
    'kindness',
    'Hand',
    'Here’s to a suggestion you’re glad you heard.',
    'Sometimes someone else knows a lovely shortcut, {{firstName}}.',
  ),
  deskPair(
    'everyday-bright-aside',
    'everyday',
    'humour',
    'Smile',
    '{{firstName}}, hope an ordinary chat takes a funny turn.',
    'Those are often the conversations you remember.',
  ),
  deskPair(
    'everyday-open-circle',
    'everyday',
    'conversation',
    'MessageCircle',
    'Hope you meet someone you enjoy talking to.',
    'Finding a shared interest is a good beginning, {{firstName}}.',
  ),
  deskPair(
    'everyday-quiet-spark',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, here’s to seeing a familiar thing differently.',
    'A fresh perspective can make it interesting all over again.',
  ),
  deskPair(
    'everyday-sweet-ordinary',
    'everyday',
    'pleasure',
    'Smile',
    'Something sweet would be lovely today, {{firstName}}.',
    'Hope your favourite is on the menu.',
  ),
  deskPair(
    'everyday-next-chapter',
    'everyday',
    'story',
    'BookOpen',
    '{{firstName}}, hope a story leaves you wanting more.',
    'With a sequel ready whenever you are.',
  ),
  deskPair(
    'everyday-good-signal',
    'everyday',
    'surprise',
    'Sparkles',
    'Hope the answer is a happy one, {{firstName}}.',
    'Especially if you’ve been looking forward to hearing it.',
  ),
  deskPair(
    'everyday-held-door',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, here’s to the small kindnesses people notice.',
    'A held door, a thoughtful gesture, a friendly hello.',
  ),
  deskPair(
    'everyday-late-sun',
    'everyday',
    'pleasure',
    'Sunset',
    'Wishing you a lovely end to the day.',
    'Something as simple as a favourite meal, {{firstName}}.',
  ),
  deskPair(
    'everyday-curious-turn',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, hope you get to ask ‘how does that work?’',
    'And hear an explanation that’s worth the question.',
  ),
  deskPair(
    'everyday-human-pace',
    'everyday',
    'kindness',
    'Smile',
    'Hope a queue moves faster than you expected.',
    'A little time back is always welcome, {{firstName}}.',
  ),
  deskPair(
    'everyday-found-lyric',
    'everyday',
    'music',
    'Music',
    '{{firstName}}, hope a song says it just right.',
    'There’s something lovely about finding the words in music.',
  ),
  deskPair(
    'everyday-small-return',
    'everyday',
    'favourite',
    'Sparkles',
    'An old favourite might be worth another try.',
    'Hope it’s just as good as you remember, {{firstName}}.',
  ),
  deskPair(
    'everyday-open-hand',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, wishing you a little generosity today.',
    'Someone sharing a good idea or the last biscuit.',
  ),
  deskPair(
    'everyday-clean-joke',
    'everyday',
    'humour',
    'Smile',
    'Hope you catch a wonderfully funny moment.',
    'The completely unplanned kind, {{firstName}}.',
  ),
  deskPair(
    'everyday-useful-wonder',
    'everyday',
    'curiosity',
    'Lightbulb',
    '{{firstName}}, here’s to discovering a new way to do something.',
    'Even a tiny improvement can be surprisingly satisfying.',
  ),
  deskPair(
    'everyday-quiet-treat',
    'everyday',
    'pleasure',
    'Coffee',
    'Something freshly baked would be a nice surprise.',
    'Hope you happen to arrive at the right time, {{firstName}}.',
  ),
  deskPair(
    'everyday-good-thread',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, hope a conversation carries on a little longer.',
    'Because you’re both enjoying where it’s going.',
  ),
  deskPair(
    'everyday-evening-note',
    'everyday',
    'story',
    'Sunset',
    'Here’s to a day you’re glad you had.',
    'With at least one part you’d happily do again, {{firstName}}.',
  ),
] as const;
