import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVENTS_CATALOG = [
  deskPair(
    'birthday-yours',
    'birthday',
    'birthday',
    'Cake',
    '{{firstName}}, ծնունդդ շնորհավոր։',
    'Թող օրդ անցնի սիրելի մարդկանցով ու հենց քո ուզած ձևով։',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-year',
    'birthday',
    'birthday',
    'Cake',
    'Ծնունդդ շնորհավոր, {{firstName}}։ Լավ տարի քեզ։',
    'Հաճելի անակնկալներով ու սպասելու գեղեցիկ առիթներով։',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-table',
    'birthday',
    'birthday',
    'Cake',
    '{{firstName}}, թող ծնունդդ սիրածդ բաներով լի լինի։',
    'Համեղ սեղան, ջերմ ընկերակցություն ու սրտովդ ծրագրեր։',
    { tone: 'festive' },
  ),
  deskPair(
    'birthday-story',
    'birthday',
    'birthday',
    'Cake',
    'Ծնունդդ շնորհավոր, {{firstName}}։ Հիշվող օր քեզ։',
    'Թե՛ ծրագրած, թե՛ անսպասելի գեղեցիկ պահերով։',
    { tone: 'festive' },
  ),

  deskPair(
    'birthday-memorial-quiet',
    'birthday_memorial',
    'birthday',
    'Smile',
    '{{firstName}}, ծննդյանդ օրը խաղաղություն եմ մաղթում։',
    'Թող կողքիդ լինեն քեզ հարազատ մարդիկ։',
    { tone: 'memorial' },
  ),
  deskPair(
    'birthday-memorial-kind',
    'birthday_memorial',
    'birthday',
    'Hand',
    'Ծնունդդ շնորհավոր, {{firstName}}։ Առողջ ու խաղաղ տարի քեզ։',
    'Քեզ համար կարևոր մարդկանց ջերմությամբ։',
    { tone: 'memorial' },
  ),

  deskPair(
    'first-day-welcome',
    'first_day',
    'first-day',
    'Hand',
    '{{firstName}}, բարի գալուստ մեր թիմ։',
    'Թող առաջին ծանոթությունները լավ զրույցների սկիզբ դառնան։',
    { tone: 'warm' },
  ),
  deskPair(
    'first-day-names',
    'first_day',
    'first-day',
    'Hand',
    'Բարի գալուստ, {{firstName}}։ Ուրախ ենք ծանոթանալու համար։',
    'Թող առաջին օրդ հաճելի անցնի մեր թիմում։',
    { tone: 'warm' },
  ),
  deskPair(
    'first-day-corner',
    'first_day',
    'first-day',
    'Compass',
    '{{firstName}}, բարի սկիզբ մեզ միասին։',
    'Թող առաջին օրվանից ջերմ զրուցակիցներ գտնես։',
    { tone: 'warm' },
  ),

  deskPair(
    'first-day-memorial',
    'first_day_memorial',
    'first-day',
    'Hand',
    '{{firstName}}, բարի գալուստ։ Ուրախ ենք, որ մեզ հետ ես։',
    'Մաղթում ենք հանգիստ ու բարեհաջող առաջին օր։',
    { tone: 'memorial' },
  ),

  deskPair(
    'anniversary-one',
    'anniversary_one',
    'anniversary',
    'PartyPopper',
    'Արդեն մեկ տարի միասին, {{firstName}}։ Շնորհակալություն։',
    'Ուրախ ենք, որ մեր թիմի մասն ես։',
    { tone: 'festive' },
  ),
  deskPair(
    'anniversary-one-quiet',
    'anniversary_one',
    'anniversary',
    'Smile',
    '{{firstName}}, այսօր քո առաջին տարին է լրանում մեզ հետ։',
    'Շնորհակալ ենք միասին անցած ճանապարհի համար։',
    { tone: 'warm' },
  ),
  deskPair(
    'anniversary-one-company',
    'anniversary_one',
    'anniversary',
    'Hand',
    'Մի տարվա համատեղ ճանապարհ, {{firstName}}։',
    'Թող առջևում էլ լավ օրեր ու հետաքրքիր փորձառություններ լինեն։',
    { tone: 'warm' },
  ),

  deskPair(
    'anniversary-many',
    'anniversary_many',
    'anniversary',
    'PartyPopper',
    'Արդեն {{years}} տարի միասին, {{firstName}}։ Շնորհակալություն։',
    'Լավ է այս ճանապարհը միասին անցնելը։',
    { tone: 'festive' },
  ),
  deskPair(
    'anniversary-many-kept',
    'anniversary_many',
    'anniversary',
    'Smile',
    '{{firstName}}, արդեն {{years}} տարի է՝ մեր թիմում ես։',
    'Շնորհակալ ենք, որ մեզ հետ ես։',
    { tone: 'warm' },
  ),
  deskPair(
    'anniversary-many-along',
    'anniversary_many',
    'anniversary',
    'Hand',
    '{{firstName}}, շնորհակալություն միասին անցած {{years}} տարվա համար։',
    'Թող շարունակությունն էլ լավ հանդիպումներով լի լինի։',
    { tone: 'warm' },
  ),

  deskPair(
    'anniversary-memorial',
    'anniversary_memorial',
    'anniversary',
    'Hand',
    '{{firstName}}, շնորհակալ ենք, որ մեր թիմում ես։',
    'Այսօր մեզ միանալու տարեդարձդ է։ Լավ է միասին աշխատելը։',
    { tone: 'memorial' },
  ),

  deskPair(
    'onboarding-3',
    'onboarding_3',
    'onboarding',
    'Hand',
    '{{firstName}}, թող ամեն օրն ավելի ծանոթ դառնա։',
    'Մի քանի նոր անուն ու մի քանի ջերմ դեմք։',
  ),
  deskPair(
    'onboarding-3-map',
    'onboarding_3',
    'onboarding',
    'Compass',
    '{{firstName}}, լավ սկիզբ եմ մաղթում թիմում։',
    'Թող հարցերիդ համար միշտ գտնվի սիրալիր պատասխանող։',
  ),
  deskPair(
    'onboarding-3-faces',
    'onboarding_3',
    'onboarding',
    'Smile',
    'Թող ծանոթանալը հաճելի լինի, {{firstName}}։',
    'Առաջին օրերի զրույցները երբեմն լավ ընկերության սկիզբ են։',
  ),

  deskPair(
    'onboarding-10',
    'onboarding_10',
    'onboarding',
    'Compass',
    '{{firstName}}, թող այստեղ քո ձևով հարմարվես։',
    'Ու հարցնելու համար հարմար մարդ միշտ գտնվի։',
  ),
  deskPair(
    'onboarding-10-ask',
    'onboarding_10',
    'onboarding',
    'Hand',
    '{{firstName}}, թող առօրյան կամաց-կամաց ծանոթ դառնա։',
    'Մաղթում եմ օգտակար պատասխաններ ու ջերմ շփումներ։',
  ),
  deskPair(
    'onboarding-10-shape',
    'onboarding_10',
    'onboarding',
    'Compass',
    '{{firstName}}, հաճելի է քեզ ավելի լավ ճանաչելը։',
    'Թող նոր անունների հետևում արդեն ծանոթ դեմքեր լինեն։',
  ),

  deskPair(
    'onboarding-21',
    'onboarding_21',
    'onboarding',
    'Smile',
    '{{firstName}}, հուսով ենք՝ լավ անակնկալներ արդեն եղել են։',
    'Ուրախ ենք, որ մեր թիմի հետ ես։',
  ),
  deskPair(
    'onboarding-21-team',
    'onboarding_21',
    'onboarding',
    'Hand',
    'Երեք շաբաթ մեզ հետ, {{firstName}}։ Բարի շարունակություն։',
    'Թող թիմում դեռ շատ լավ զրույցներ ունենաս։',
  ),
  deskPair(
    'onboarding-21-keep',
    'onboarding_21',
    'onboarding',
    'Smile',
    '{{firstName}}, թող այստեղ արդեն քո անկյունը գտնես։',
    'Ծանոթ մարդիկ ու հաճելի պահեր՝ օրվա ընթացքում։',
  ),

  deskPair(
    'book-hard-to-leave',
    'cultural',
    'books',
    'BookOpen',
    '{{firstName}}, թող հաջորդ գիրքդ դժվարությամբ փակես։',
    'Այսօր գրքի օրն է։ Եվս մի էջ կարդալու լավ առիթ։',
    { eventId: 'world-book-day', tone: 'warm' },
  ),
  deskPair(
    'book-evening',
    'cultural',
    'books',
    'BookOpen',
    'Թող խորհուրդ տալու արժանի գիրք գտնես։',
    'Գրքի օրվա մի լավ բացահայտում քեզ, {{firstName}}։',
    { eventId: 'world-book-day', tone: 'warm' },
  ),
  deskPair(
    'book-finds-you',
    'cultural',
    'books',
    'BookOpen',
    '{{firstName}}, թող ճիշտ գիրքը ճիշտ պահին հանդիպի։',
    'Գրքի օրը գուցե սիրելի հայ հեղինակի էլ վերադառնաս։',
    { eventId: 'world-book-day', tone: 'warm' },
  ),

  deskPair(
    'music-soundtrack',
    'cultural',
    'music',
    'Music',
    '{{firstName}}, երաժշտության օրվա մի լավ երգ քեզ։',
    'Թող սիրելի մեղեդիդ այսօր անպայման հնչի։',
    { eventId: 'international-music-day', tone: 'warm' },
  ),
  deskPair(
    'music-twice',
    'cultural',
    'music',
    'Music',
    'Թող մի երգ նորից լսելու ցանկություն առաջացնի։',
    'Երաժշտության օրն է, {{firstName}}։ Երրորդ անգամն էլ կարելի է։',
    { eventId: 'international-music-day', tone: 'warm' },
  ),
  deskPair(
    'music-finds-you',
    'cultural',
    'music',
    'Music',
    '{{firstName}}, թող այսօր նոր սիրելի մեղեդի գտնես։',
    'Երաժշտության օրվանից քեզ մի փոքր հիշատակ։',
    { eventId: 'international-music-day', tone: 'warm' },
  ),

  deskPair(
    'new-year-surprises',
    'cultural',
    'new-year',
    'Sparkles',
    '{{firstName}}, շնորհավոր Ամանոր։ Լավ անակնկալներով տարի քեզ։',
    'Թող առողջություն ու ուրախանալու առիթներ շատ լինեն։',
    { eventId: 'new-year', tone: 'festive' },
  ),
  deskPair(
    'new-year-pages',
    'cultural',
    'new-year',
    'Sparkles',
    'Շնորհավոր Նոր տարի, {{firstName}}։ Բարի սկիզբ։',
    'Նոր բացահայտումներ ու հարազատ մարդիկ՝ կողքիդ։',
    { eventId: 'new-year', tone: 'festive' },
  ),
  deskPair(
    'new-year-kind',
    'cultural',
    'new-year',
    'Smile',
    '{{firstName}}, խաղաղ ու բարեբեր տարի եմ մաղթում։',
    'Թող այս Ամանորը լավ հիշողությունների սկիզբ լինի։',
    { eventId: 'new-year', tone: 'festive' },
  ),

  deskPair(
    'new-year-eve-close',
    'cultural',
    'new-year',
    'Sparkles',
    '{{firstName}}, թող տարին լավ ավարտ ունենա։',
    'Ու նոր տարում սպասելու գեղեցիկ բան լինի։',
    { eventId: 'new-year-eve', tone: 'festive' },
  ),
  deskPair(
    'new-year-eve-light',
    'cultural',
    'new-year',
    'Sparkles',
    'Տարվա վերջին օրն է, {{firstName}}։',
    'Թող մի հաճելի անակնկալի տեղ դեռ մնացած լինի։',
    { eventId: 'new-year-eve', tone: 'warm' },
  ),
  deskPair(
    'new-year-eve-forward',
    'cultural',
    'new-year',
    'Smile',
    '{{firstName}}, բարի մուտք դեպի նոր տարի։',
    'Հաճելի երեկո եմ մաղթում՝ ինչ ծրագրեր էլ ունենաս։',
    { eventId: 'new-year-eve', tone: 'warm' },
  ),

  deskPair(
    'independence-quiet',
    'cultural',
    'armenia',
    'Sparkles',
    '{{firstName}}, շնորհավոր Անկախության օրը։',
    'Մեր երկրին՝ խաղաղություն, քեզ՝ բարօրություն։',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),
  deskPair(
    'independence-company',
    'cultural',
    'armenia',
    'Smile',
    'Անկախության օրվա ջերմ մաղթանքներ քեզ, {{firstName}}։',
    'Թող օրը լավ մարդկանց հետ անցկացնելու առիթ լինի։',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),
  deskPair(
    'independence-here',
    'cultural',
    'armenia',
    'Hand',
    '{{firstName}}, խաղաղ ու լուսավոր օրեր մեր երկրին։',
    'Անկախության օրվա առթիվ քեզ էլ լավն եմ մաղթում։',
    { eventId: 'armenia-independence', tone: 'warm' },
  ),

  deskPair(
    'memorial-peaceful',
    'memorial_neutral',
    'peaceful',
    'None',
    'Խաղաղ օր եմ մաղթում, {{firstName}}։',
    'Մի քիչ ժամանակ քեզ համար կարևորի մասին մտածելու։',
    { tone: 'memorial' },
  ),
  deskPair(
    'memorial-room',
    'memorial_neutral',
    'peaceful',
    'None',
    '{{firstName}}, խաղաղություն քեզ ու հարազատներիդ։',
    'Թող հոգատարությունն ու մարդկային ջերմությունը միշտ տեղ ունենան։',
    { tone: 'memorial' },
  ),
  deskPair(
    'memorial-plain',
    'memorial_neutral',
    'peaceful',
    'None',
    'Այսօր՝ հիշելու ու մտորելու պահ։',
    'Խաղաղություն ու մարդկային ջերմություն բոլորիս։',
    { tone: 'memorial' },
  ),
] as const;
