import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_A = [
  deskPair('everyday-better-than-expected', 'everyday', 'surprise', 'Sparkles', '{{firstName}}, may something go better than expected.', 'Even a small, unexpected yes would do.'),
  deskPair('everyday-little-surprise', 'everyday', 'surprise', 'Smile', 'Here’s to a good little surprise.', 'A kind message. A favourite song. Something just for you, {{firstName}}.'),
  deskPair('everyday-easy-thing', 'everyday', 'surprise', 'Sparkles', '{{firstName}}, may one thing be easier than expected.', 'A small favour from the day.'),
  deskPair('everyday-pleasant-detour', 'everyday', 'detour', 'Compass', '{{firstName}}, here’s to a pleasant detour.', 'Sometimes the unplanned bit makes the best story.'),
  deskPair('everyday-new-favourite', 'everyday', 'favourite', 'Sparkles', '{{firstName}}, perhaps today brings a new favourite.', 'A song, a place, or something you weren’t looking for.'),
  deskPair('everyday-looking-forward', 'everyday', 'forward', 'Smile', 'Here’s to having something to look forward to.', 'Something small is more than enough, {{firstName}}.'),
  deskPair('everyday-idea', 'everyday', 'clarity', 'Coffee', 'May your best idea arrive without a struggle.', 'Preferably while the coffee is still warm, {{firstName}}.'),
  deskPair('everyday-click', 'everyday', 'clarity', 'Lightbulb', '{{firstName}}, here’s to something finally making sense.', 'That lovely moment when the pieces fit.'),
  deskPair('everyday-fresh-thought', 'everyday', 'curiosity', 'Lightbulb', '{{firstName}}, hope a fresh thought finds you today.', 'Perhaps from somewhere you wouldn’t normally look.'),
  deskPair('everyday-right-words', 'everyday', 'words', 'MessageCircle', 'Here’s to finding just the right words.', 'And someone who understands what you mean, {{firstName}}.'),
  deskPair('everyday-good-conversation', 'everyday', 'conversation', 'MessageCircle', 'Hope a good conversation finds you today.', 'One that leaves you with something to think about, {{firstName}}.'),
  deskPair('everyday-good-story', 'everyday', 'story', 'MessageCircle', '{{firstName}}, hope today gives you a good story.', 'The kind you want to tell someone later.'),
  deskPair('everyday-kindness', 'everyday', 'kindness', 'Smile', 'A little unexpected kindness would be nice today.', 'Hope some finds its way to you, {{firstName}}.'),
  deskPair('everyday-small-pleasure', 'everyday', 'pleasure', 'Smile', '{{firstName}}, hope there’s something lovely in the ordinary.', 'A good lunch counts. So does an unexpectedly good song.'),
  deskPair('everyday-laugh', 'everyday', 'humour', 'Smile', 'Hope something makes you laugh today, {{firstName}}.', 'The sort of laugh that’s hard to explain afterwards.'),
  deskPair('everyday-music', 'everyday', 'music', 'Music', 'Hope today comes with a good soundtrack.', 'And at least one song worth playing twice, {{firstName}}.'),
  deskPair('everyday-quiet-yes', 'everyday', 'surprise', 'Sparkles', 'May a quiet yes arrive out of nowhere.', 'The small kind that still changes the afternoon, {{firstName}}.'),
  deskPair('everyday-window', 'everyday', 'curiosity', 'Compass', '{{firstName}}, hope the day opens a window.', 'Not a door you have to force — just a little more air.'),
  deskPair('everyday-soft-landing', 'everyday', 'kindness', 'Smile', 'Here’s to a soft landing somewhere today.', 'A chair, a message, a familiar face, {{firstName}}.'),
  deskPair('everyday-second-look', 'everyday', 'curiosity', 'Lightbulb', '{{firstName}}, here’s to a useful second look.', 'The thing that only appears when you glance again.'),
  deskPair('everyday-shared-joke', 'everyday', 'humour', 'Smile', 'Hope you catch a joke that actually lands.', 'The private kind you can still replay later, {{firstName}}.'),
  deskPair('everyday-warm-plate', 'everyday', 'pleasure', 'Coffee', '{{firstName}}, may lunch be better than you planned.', 'A warm plate is a perfectly respectable highlight.'),
  deskPair('everyday-clear-sentence', 'everyday', 'words', 'MessageCircle', 'Here’s to one clear sentence.', 'The one that says exactly what you meant, {{firstName}}.'),
  deskPair('everyday-unfinished-song', 'everyday', 'music', 'Music', '{{firstName}}, hope a tune follows you around.', 'The pleasant kind you do not mind humming twice.'),
  deskPair('everyday-tiny-win', 'everyday', 'surprise', 'Sparkles', 'May a tiny win show up without ceremony.', 'No parade required, {{firstName}}. Just the win.'),
  deskPair('everyday-good-timing', 'everyday', 'surprise', 'Compass', '{{firstName}}, here’s to unusually good timing.', 'A door opening while you are already nearby.'),
  deskPair('everyday-honest-chat', 'everyday', 'conversation', 'MessageCircle', 'Hope someone says the useful thing out loud.', 'Not the grand speech — the honest one, {{firstName}}.'),
  deskPair('everyday-page-turns', 'everyday', 'curiosity', 'BookOpen', '{{firstName}}, may a page be hard to leave.', 'A paragraph, a recipe, a thought you want to keep.'),
  deskPair('everyday-light-pocket', 'everyday', 'pleasure', 'Smile', 'Here’s to something that fits in a pocket.', 'A note, a sweet, a song saved for later, {{firstName}}.'),
  deskPair('everyday-gentle-weather', 'everyday', 'kindness', 'Sprout', '{{firstName}}, hope the day treats you gently.', 'Not a forecast — just a little luck with the hours.'),
  deskPair('everyday-better-question', 'everyday', 'clarity', 'Lightbulb', 'May a better question arrive before the answer.', 'That is often the interesting part, {{firstName}}.'),
  deskPair('everyday-old-favourite', 'everyday', 'favourite', 'Music', '{{firstName}}, here’s to an old favourite returning.', 'The song or snack you forgot you missed.'),
] as const;
