import { deskPair } from './desk-line-pair';

export const DESK_LINE_SEASONS_CATALOG = [
  deskPair(
    'spring-new',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, here’s to something new this spring.',
    'A small discovery you’ll be glad you made.',
  ),
  deskPair(
    'spring-room',
    'season_spring',
    'spring',
    'Sprout',
    'Hope spring brings room for something you enjoy.',
    'An old favourite or a new curiosity, {{firstName}}.',
  ),
  deskPair(
    'spring-window',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, wishing you a lovely spring outing.',
    'Somewhere familiar or somewhere you’ve been meaning to try.',
  ),
  deskPair(
    'spring-colour',
    'season_spring',
    'spring',
    'Sprout',
    'A little spring colour would be lovely.',
    'Hope you spot something that makes you smile, {{firstName}}.',
  ),
  deskPair(
    'spring-return',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, hope you rediscover something you enjoy this spring.',
    'A favourite walk or a recipe you haven’t made in ages.',
  ),
  deskPair(
    'spring-light',
    'season_spring',
    'spring',
    'Sparkles',
    'Here’s to spring evenings with something to enjoy.',
    'A little walk after dinner, perhaps, {{firstName}}.',
  ),
  deskPair(
    'spring-start',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, wishing you a lovely first attempt this spring.',
    'At something you’ve wanted to try for a while.',
  ),
  deskPair(
    'spring-air',
    'season_spring',
    'spring',
    'Sprout',
    'A spring picnic could be a good plan.',
    'Hope the right day and some good company come together, {{firstName}}.',
  ),
  deskPair(
    'spring-curiosity',
    'season_spring',
    'spring',
    'Compass',
    '{{firstName}}, hope this spring gives you something to explore.',
    'A neighbourhood, a new interest, a different way home.',
  ),
  deskPair(
    'spring-green',
    'season_spring',
    'spring',
    'Sprout',
    'Here’s to the little things growing this spring.',
    'Hope there’s something lovely to notice nearby, {{firstName}}.',
  ),
  deskPair(
    'spring-plans',
    'season_spring',
    'spring',
    'Smile',
    '{{firstName}}, wishing you a spring plan to look forward to.',
    'Something simple that you’ll be happy you arranged.',
  ),
  deskPair(
    'spring-market',
    'season_spring',
    'spring',
    'Sprout',
    'Hope you find something delicious this spring.',
    'A new ingredient or an old favourite back in season, {{firstName}}.',
  ),
  deskPair(
    'spring-letter',
    'season_spring',
    'spring',
    'MessageCircle',
    '{{firstName}}, here’s to catching up with someone this spring.',
    'And finding you still have plenty to talk about.',
  ),
  deskPair(
    'spring-walk',
    'season_spring',
    'spring',
    'Compass',
    'Hope a spring walk brings a nice discovery.',
    'A little café or a path you haven’t taken before, {{firstName}}.',
  ),
  deskPair(
    'spring-fresh',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, wishing you a fresh idea this spring.',
    'Something you’re curious enough to give a go.',
  ),
  deskPair(
    'spring-keep',
    'season_spring',
    'spring',
    'Sprout',
    'Here’s to one spring thing worth keeping.',
    'A habit, a song, a place, {{firstName}}.',
  ),

  deskPair(
    'summer-room',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, leave a little room for summer.',
    'Here’s to long evenings with no particular plan.',
  ),
  deskPair(
    'summer-evening',
    'season_summer',
    'summer',
    'Sunset',
    'Hope there’s a lovely evening ahead, {{firstName}}.',
    'The summer kind you’d happily make a little longer.',
  ),
  deskPair(
    'summer-flavour',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, here’s to a little taste of summer.',
    'Something fresh, something cold, something you really like.',
  ),
  deskPair(
    'summer-memory',
    'season_summer',
    'summer',
    'Sun',
    'Hope this summer gives you a good memory.',
    'An ordinary day can become one too, {{firstName}}.',
  ),
  deskPair(
    'summer-shade',
    'season_summer',
    'summer',
    'Sunset',
    '{{firstName}}, here’s to a comfortable spot in the shade.',
    'With a good drink and something interesting to read.',
  ),
  deskPair(
    'summer-late',
    'season_summer',
    'summer',
    'Sunset',
    'Hope there’s a summer evening worth lingering over.',
    'With a conversation you’re in no hurry to finish, {{firstName}}.',
  ),
  deskPair(
    'summer-street',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, wishing you a lovely summer discovery.',
    'A small café with a table you’d happily stay at.',
  ),
  deskPair(
    'summer-cold',
    'season_summer',
    'summer',
    'Sun',
    'Hope your next ice cream is a good one.',
    'An old favourite or a brave new flavour, {{firstName}}.',
  ),
  deskPair(
    'summer-window',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, here’s to a good summer playlist.',
    'A few songs that will remind you of this season later.',
  ),
  deskPair(
    'summer-slow',
    'season_summer',
    'summer',
    'Sunset',
    'A summer afternoon with no plans sounds lovely.',
    'Hope one comes your way, {{firstName}}.',
  ),
  deskPair(
    'summer-outside',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, hope you enjoy a little time outdoors this summer.',
    'A park bench and a pleasant view would do nicely.',
  ),
  deskPair(
    'summer-peach',
    'season_summer',
    'summer',
    'Sun',
    'Here’s to a flavour that tastes like the season.',
    'Ripe, simple, and worth repeating, {{firstName}}.',
  ),
  deskPair(
    'summer-light-clothes',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, wishing you a few lovely summer plans.',
    'The kind that are easy to arrange and hard to forget.',
  ),
  deskPair(
    'summer-gather',
    'season_summer',
    'summer',
    'Smile',
    'Here’s to a summer meal with good company.',
    'Something to share and plenty to talk about, {{firstName}}.',
  ),
  deskPair(
    'summer-horizon',
    'season_summer',
    'summer',
    'Sunset',
    '{{firstName}}, hope you find a view worth stopping for.',
    'A little summer memory, even close to home.',
  ),
  deskPair(
    'summer-keep',
    'season_summer',
    'summer',
    'Sun',
    'Hope you keep one summer thing for later.',
    'A photo, a joke, a place, {{firstName}}.',
  ),

  deskPair(
    'autumn-favourite',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, may this season bring a new favourite.',
    'A place, a book, a small habit worth keeping.',
  ),
  deskPair(
    'autumn-pages',
    'season_autumn',
    'autumn',
    'BookOpen',
    'Here’s to a book that draws you in.',
    'Something for an autumn evening, {{firstName}} — if that sounds like your kind of plan.',
  ),
  deskPair(
    'autumn-colour',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, hope autumn brings a little colour.',
    'To the everyday things as much as the trees.',
  ),
  deskPair(
    'autumn-comfort',
    'season_autumn',
    'autumn',
    'Leaf',
    'Here’s to the small comforts of autumn.',
    'Whatever yours happen to be, {{firstName}}.',
  ),
  deskPair(
    'autumn-lamp',
    'season_autumn',
    'autumn',
    'Lightbulb',
    '{{firstName}}, here’s to a cosy autumn evening.',
    'A favourite chair and a good story would be lovely.',
  ),
  deskPair(
    'autumn-pocket',
    'season_autumn',
    'autumn',
    'Leaf',
    'Hope autumn brings a pleasant little surprise.',
    'Finding something in a coat pocket is a good start, {{firstName}}.',
  ),
  deskPair(
    'autumn-return',
    'season_autumn',
    'autumn',
    'BookOpen',
    '{{firstName}}, perhaps there’s a book worth returning to this autumn.',
    'Hope it’s even better than you remember.',
  ),
  deskPair(
    'autumn-kitchen',
    'season_autumn',
    'autumn',
    'Coffee',
    'Wishing you something delicious from the kitchen this autumn.',
    'A familiar recipe or a new one that turns out well, {{firstName}}.',
  ),
  deskPair(
    'autumn-walk',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, hope you enjoy the colours of autumn.',
    'A little detour on foot might be worth it.',
  ),
  deskPair(
    'autumn-evening',
    'season_autumn',
    'autumn',
    'Sunset',
    'Here’s to an autumn evening with a good film.',
    'One you’ll be recommending afterwards, {{firstName}}.',
  ),
  deskPair(
    'autumn-layer',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, wishing you a comfortable start to an autumn day.',
    'A favourite jumper and something warm to drink.',
  ),
  deskPair(
    'autumn-quiet',
    'season_autumn',
    'autumn',
    'BookOpen',
    'Hope you find a lovely autumn read, {{firstName}}.',
    'Something you’re pleased to pick up again each evening.',
  ),
  deskPair(
    'autumn-market',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, here’s to a good find at the market.',
    'Something seasonal you’ll enjoy bringing home.',
  ),
  deskPair(
    'autumn-story',
    'season_autumn',
    'autumn',
    'MessageCircle',
    'An autumn catch-up would be lovely, {{firstName}}.',
    'Hope you get to hear what someone’s been up to.',
  ),
  deskPair(
    'autumn-gold',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, hope this autumn gives you a favourite photo.',
    'Something that reminds you of a good day.',
  ),
  deskPair(
    'autumn-keep',
    'season_autumn',
    'autumn',
    'Leaf',
    'Here’s to an autumn habit you look forward to.',
    'A weekly walk or a favourite place for tea, {{firstName}}.',
  ),

  deskPair(
    'winter-warmth',
    'season_winter',
    'winter',
    'Coffee',
    '{{firstName}}, wishing you a little winter warmth.',
    'A good meal and good company would be a lovely start.',
  ),
  deskPair(
    'winter-bright',
    'season_winter',
    'winter',
    'Sparkles',
    'Hope something brightens your winter day, {{firstName}}.',
    'A message from someone you’re always glad to hear from, perhaps.',
  ),
  deskPair(
    'winter-table',
    'season_winter',
    'winter',
    'Coffee',
    '{{firstName}}, wishing you a welcoming table this winter.',
    'Something warm to eat and someone good to talk to.',
  ),
  deskPair(
    'winter-light',
    'season_winter',
    'winter',
    'Lightbulb',
    'Here’s to a comfortable evening indoors, {{firstName}}.',
    'With a film you’ve been meaning to watch.',
  ),
  deskPair(
    'winter-coat',
    'season_winter',
    'winter',
    'Smile',
    '{{firstName}}, hope winter has its little comforts for you.',
    'A favourite scarf, a warm room, a familiar voice.',
  ),
  deskPair(
    'winter-broth',
    'season_winter',
    'winter',
    'Coffee',
    'A bowl of something warm sounds good.',
    'Hope you find a winter recipe worth making again, {{firstName}}.',
  ),
  deskPair(
    'winter-early',
    'season_winter',
    'winter',
    'Sunset',
    '{{firstName}}, wishing you a winter evening to enjoy.',
    'A board game and good company could be a lovely plan.',
  ),
  deskPair(
    'winter-message',
    'season_winter',
    'winter',
    'MessageCircle',
    'Hope you hear from a friend this winter.',
    'A proper catch-up, however far apart you are, {{firstName}}.',
  ),
  deskPair(
    'winter-window',
    'season_winter',
    'winter',
    'Sparkles',
    '{{firstName}}, here’s to a little winter daydreaming.',
    'Perhaps a place you’d like to visit when the time is right.',
  ),
  deskPair(
    'winter-return',
    'season_winter',
    'winter',
    'Coffee',
    'Coming home to something warm is a winter pleasure.',
    'Hope there’s a good cup of tea in it for you, {{firstName}}.',
  ),
  deskPair(
    'winter-slow',
    'season_winter',
    'winter',
    'BookOpen',
    '{{firstName}}, hope a good book keeps you company this winter.',
    'The sort you look forward to getting back to.',
  ),
  deskPair(
    'winter-company',
    'season_winter',
    'winter',
    'Smile',
    'Here’s to a winter get-together worth arranging.',
    'Even a simple lunch with someone you’ve missed, {{firstName}}.',
  ),
  deskPair(
    'winter-citrus',
    'season_winter',
    'winter',
    'Sparkles',
    '{{firstName}}, wishing you a little winter sweetness.',
    'A really good mandarin would do nicely.',
  ),
  deskPair(
    'winter-quiet',
    'season_winter',
    'winter',
    'Leaf',
    'Hope you find a winter afternoon to yourself.',
    'For a little of whatever you enjoy, {{firstName}}.',
  ),
  deskPair(
    'winter-glove',
    'season_winter',
    'winter',
    'Hand',
    '{{firstName}}, here’s to a cheerful hello on a winter day.',
    'It’s lovely when someone is pleased to see you.',
  ),
  deskPair(
    'winter-keep',
    'season_winter',
    'winter',
    'Coffee',
    'Wishing you a new winter favourite, {{firstName}}.',
    'A dish, a film, or somewhere you’ll want to go again.',
  ),
] as const;
