import { deskPair } from './desk-line-pair';

export const DESK_LINE_SEASONS_CATALOG = [
  deskPair(
    'spring-new',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, թող գարունը մի նոր բան բերի։',
    'Մի փոքր բացահայտում, որից ուրախանաս։',
  ),
  deskPair(
    'spring-room',
    'season_spring',
    'spring',
    'Sprout',
    'Թող գարնանը սիրածդ բաների համար տեղ լինի։',
    'Հին նախասիրության կամ նոր հետաքրքրության համար, {{firstName}}։',
  ),
  deskPair(
    'spring-window',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, մի հաճելի գարնանային զբոսանք քեզ։',
    'Ծանոթ տեղով կամ մի հասցեով, ուր վաղուց էիր ուզում գնալ։',
  ),
  deskPair(
    'spring-colour',
    'season_spring',
    'spring',
    'Sprout',
    'Գարնան մի քիչ գույն եմ մաղթում։',
    'Թող ճանապարհիդ մի ծաղկած ծառ հանդիպի, {{firstName}}։',
  ),
  deskPair(
    'spring-return',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, թող գարնանը սիրելի սովորություն վերադառնա։',
    'Երեկոյան զբոսանքը կամ վաղուց չպատրաստած ուտեստը։',
  ),
  deskPair(
    'spring-light',
    'season_spring',
    'spring',
    'Sparkles',
    'Թող գարնան երեկոները հաճելի անցնեն։',
    'Ընթրիքից հետո մի փոքր զբոսանքով, գուցե, {{firstName}}։',
  ),
  deskPair(
    'spring-start',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, թող առաջին փորձդ հաջող ստացվի։',
    'Մի բանում, որ այս գարնանը ուզում ես սկսել։',
  ),
  deskPair(
    'spring-air',
    'season_spring',
    'spring',
    'Sprout',
    'Գարնանային մի պիկնիկ լավ կլիներ։',
    'Թող հարմար օրն ու լավ ընկերությունը համընկնեն, {{firstName}}։',
  ),
  deskPair(
    'spring-curiosity',
    'season_spring',
    'spring',
    'Compass',
    '{{firstName}}, թող գարունը հետաքրքիր ճանապարհներ բացի։',
    'Նոր թաղամաս, նոր զբաղմունք կամ տուն տանող ուրիշ փողոց։',
  ),
  deskPair(
    'spring-green',
    'season_spring',
    'spring',
    'Sprout',
    'Գարնանը փոքրիկ կանաչն էլ աչք է շոյում։',
    'Թող պատուհանիդ մոտ էլ աճելու բան լինի, {{firstName}}։',
  ),
  deskPair(
    'spring-plans',
    'season_spring',
    'spring',
    'Smile',
    '{{firstName}}, թող գարնան մի լավ ծրագիր ունենաս։',
    'Այնքան պարզ, որ հեշտ կազմակերպվի ու հաճելի անցնի։',
  ),
  deskPair(
    'spring-market',
    'season_spring',
    'spring',
    'Sprout',
    'Թող գարնան սեղանին համեղ նորություն լինի։',
    'Թարմ կանաչիով մի ուտեստ, որ սիրես, {{firstName}}։',
  ),
  deskPair(
    'spring-letter',
    'season_spring',
    'spring',
    'MessageCircle',
    '{{firstName}}, թող այս գարնանը հին ընկերոջ հանդիպես։',
    'Ու պարզվի՝ պատմելու դեռ շատ բան ունեք։',
  ),
  deskPair(
    'spring-walk',
    'season_spring',
    'spring',
    'Compass',
    'Թող գարնան զբոսանքը մի լավ տեղ տանի։',
    'Գուցե փոքրիկ սրճարան կամ անծանոթ բակ գտնես, {{firstName}}։',
  ),
  deskPair(
    'spring-fresh',
    'season_spring',
    'spring',
    'Sprout',
    '{{firstName}}, մի թարմ գաղափար այս գարնանը։',
    'Այնպիսին, որ փորձելու ցանկություն առաջացնի։',
  ),
  deskPair(
    'spring-keep',
    'season_spring',
    'spring',
    'Sprout',
    'Թող գարնանից մի լավ սովորություն մնա։',
    'Սիրելի երթուղի կամ նոր հետաքրքրություն, {{firstName}}։',
  ),

  deskPair(
    'summer-room',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, ամառվա համար էլ մի քիչ ժամանակ։',
    'Երկար երեկոների ու առանց ծրագրի հանդիպումների համար։',
  ),
  deskPair(
    'summer-evening',
    'season_summer',
    'summer',
    'Sunset',
    'Թող առջևում հաճելի ամառային երեկո լինի։',
    'Այնպիսին, որ կուզենաս մի քիչ երկար տևի, {{firstName}}։',
  ),
  deskPair(
    'summer-flavour',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, ամառվա համերից մի լավ բան քեզ։',
    'Սառը, թարմ ու հենց քո սիրած տեսակից։',
  ),
  deskPair(
    'summer-memory',
    'season_summer',
    'summer',
    'Sun',
    'Թող այս ամառից լավ հիշողություն մնա։',
    'Ամենասովորական օրն էլ կարող է այդպիսին դառնալ, {{firstName}}։',
  ),
  deskPair(
    'summer-shade',
    'season_summer',
    'summer',
    'Sunset',
    '{{firstName}}, մի հարմար տեղ ծառի ստվերում։',
    'Սառը խմիչքով ու հետաքրքիր գրքով։',
  ),
  deskPair(
    'summer-late',
    'season_summer',
    'summer',
    'Sunset',
    'Թող ամառային զրույցդ երկար տևի։',
    'Երբ ավարտելու շտապողականություն չկա, {{firstName}}։',
  ),
  deskPair(
    'summer-street',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, թող ամռանը սիրելի նոր անկյուն գտնես։',
    'Բացօթյա սեղան, որտեղ հաճույքով կնստես։',
  ),
  deskPair(
    'summer-cold',
    'season_summer',
    'summer',
    'Sun',
    'Թող հաջորդ պաղպաղակդ հատկապես համեղ լինի։',
    'Ծանոթ համով կամ համարձակ նոր ընտրությամբ, {{firstName}}։',
  ),
  deskPair(
    'summer-window',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, թող ամառդ իր լավ երգերն ունենա։',
    'Որ հետո լսելիս այս օրերը հիշես։',
  ),
  deskPair(
    'summer-slow',
    'season_summer',
    'summer',
    'Sunset',
    'Ամառային մի կեսօր՝ առանց ծրագրերի։',
    'Թող այդպիսի ազատ ժամեր էլ բաժին հասնեն քեզ, {{firstName}}։',
  ),
  deskPair(
    'summer-outside',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, մի հաճելի ամառային զբոսանք եմ մաղթում։',
    'Այգու նստարանն ու լավ տեսարանն էլ բավական են։',
  ),
  deskPair(
    'summer-peach',
    'season_summer',
    'summer',
    'Sun',
    'Ամառը հասած ծիրանի համ էլ ունի։',
    'Թող ամենաքաղցրը քեզ բաժին հասնի, {{firstName}}։',
  ),
  deskPair(
    'summer-light-clothes',
    'season_summer',
    'summer',
    'Sun',
    '{{firstName}}, թող ամառային ծրագրերդ հեշտ ստացվեն։',
    'Ու հիշելու լավ պահեր շատ լինեն։',
  ),
  deskPair(
    'summer-gather',
    'season_summer',
    'summer',
    'Smile',
    'Ամառվա մի լավ սեղան՝ ընկերներով։',
    'Կիսելու համեղ բան ու պատմելու շատ լուրեր, {{firstName}}։',
  ),
  deskPair(
    'summer-horizon',
    'season_summer',
    'summer',
    'Sunset',
    '{{firstName}}, թող կանգ առնելու արժանի տեսարան բացվի։',
    'Փոքրիկ ամառային հիշողություն՝ թեկուզ տնից ոչ հեռու։',
  ),
  deskPair(
    'summer-keep',
    'season_summer',
    'summer',
    'Sun',
    'Թող ամառից մի սիրելի բան պահես։',
    'Լուսանկար, կատակ կամ նոր հասցե, {{firstName}}։',
  ),

  deskPair(
    'autumn-favourite',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, թող աշունը նոր սիրելի բան բերի։',
    'Գիրք, վայր կամ սովորություն, որ կմնա քեզ հետ։',
  ),
  deskPair(
    'autumn-pages',
    'season_autumn',
    'autumn',
    'BookOpen',
    'Թող աշնան երեկոներիդ լավ գիրք գտնվի։',
    'Այնպիսին, որ սպասես հաջորդ էջին, {{firstName}}։',
  ),
  deskPair(
    'autumn-colour',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, մի քիչ աշնան գույն քեզ։',
    'Թող առօրյայիդ մեջ էլ գեղեցիկ բան նկատես։',
  ),
  deskPair(
    'autumn-comfort',
    'season_autumn',
    'autumn',
    'Leaf',
    'Աշնան փոքրիկ հաճույքներից քեզ էլ բաժին։',
    'Թե որն է քոնը, դու ավելի լավ գիտես, {{firstName}}։',
  ),
  deskPair(
    'autumn-lamp',
    'season_autumn',
    'autumn',
    'Lightbulb',
    '{{firstName}}, մի հարմարավետ աշնան երեկո եմ մաղթում։',
    'Սիրելի բազկաթոռով ու հետաքրքիր պատմությամբ։',
  ),
  deskPair(
    'autumn-pocket',
    'season_autumn',
    'autumn',
    'Leaf',
    'Թող աշունը փոքրիկ անակնկալ ունենա։',
    'Գուցե վերարկուիդ գրպանում մոռացված բան գտնես, {{firstName}}։',
  ),
  deskPair(
    'autumn-return',
    'season_autumn',
    'autumn',
    'BookOpen',
    '{{firstName}}, գուցե աշնանը մի հին գրքի վերադառնաս։',
    'Թող այս անգամ նոր բան էլ գտնես էջերում։',
  ),
  deskPair(
    'autumn-kitchen',
    'season_autumn',
    'autumn',
    'Coffee',
    'Աշնան խոհանոցից մի համեղ բան քեզ։',
    'Ընտանեկան բաղադրատոմսով կամ հաջող նոր փորձով, {{firstName}}։',
  ),
  deskPair(
    'autumn-walk',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, թող աշնան գույները վայելելու առիթ լինի։',
    'Տուն գնալիս մի փոքր շրջանցումն էլ գուցե արժենա։',
  ),
  deskPair(
    'autumn-evening',
    'season_autumn',
    'autumn',
    'Sunset',
    'Աշնան մի երեկո՝ լավ ֆիլմով։',
    'Որ հետո ընկերներիդ էլ խորհուրդ տաս, {{firstName}}։',
  ),
  deskPair(
    'autumn-layer',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, թող աշնան առավոտդ հարմարավետ սկսվի։',
    'Սիրելի սվիտերով ու մի տաք բաժակով։',
  ),
  deskPair(
    'autumn-quiet',
    'season_autumn',
    'autumn',
    'BookOpen',
    'Թող աշնան համար հետաքրքիր ընթերցանություն գտնես։',
    'Որ ամեն երեկո հաճույքով շարունակես, {{firstName}}։',
  ),
  deskPair(
    'autumn-market',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, թող շուկայում մի համեղ գտածո լինի։',
    'Աշնան բարիքներից՝ սիրով տուն տանելու համար։',
  ),
  deskPair(
    'autumn-story',
    'season_autumn',
    'autumn',
    'MessageCircle',
    'Աշնան մի հանդիպում՝ վաղուց չտեսած ընկերոջ հետ։',
    'Թող իրարից պատմելու շատ բան ունենաք, {{firstName}}։',
  ),
  deskPair(
    'autumn-gold',
    'season_autumn',
    'autumn',
    'Leaf',
    '{{firstName}}, թող աշունը սիրելի լուսանկար թողնի։',
    'Նայես ու մի լավ օր հիշես։',
  ),
  deskPair(
    'autumn-keep',
    'season_autumn',
    'autumn',
    'Leaf',
    'Թող աշունը կրկնելու հաճելի սովորություն բերի։',
    'Ամենշաբաթյա զբոսանք կամ թեյի սիրելի տեղ, {{firstName}}։',
  ),

  deskPair(
    'winter-warmth',
    'season_winter',
    'winter',
    'Coffee',
    '{{firstName}}, ձմռան մի քիչ ջերմություն քեզ։',
    'Տաք ուտեստն ու լավ ընկերակցությունը հաճելի սկիզբ են։',
  ),
  deskPair(
    'winter-bright',
    'season_winter',
    'winter',
    'Sparkles',
    'Թող ձմեռային օրդ մի բան ջերմացնի։',
    'Գուցե հաղորդագրություն մեկից, ում լսելը միշտ հաճելի է, {{firstName}}։',
  ),
  deskPair(
    'winter-table',
    'season_winter',
    'winter',
    'Coffee',
    '{{firstName}}, ձմռան մի ջերմ սեղան եմ մաղթում։',
    'Տաք ուտելիքով ու հաճելի զրուցակցով։',
  ),
  deskPair(
    'winter-light',
    'season_winter',
    'winter',
    'Lightbulb',
    'Մի հարմարավետ երեկո՝ տանը, {{firstName}}։',
    'Այն ֆիլմով, որ վաղուց էիր ուզում դիտել։',
  ),
  deskPair(
    'winter-coat',
    'season_winter',
    'winter',
    'Smile',
    '{{firstName}}, թող ձմեռն իր փոքրիկ հաճույքներն ունենա։',
    'Սիրելի շարֆ, տաք սենյակ ու հարազատ ձայն։',
  ),
  deskPair(
    'winter-broth',
    'season_winter',
    'winter',
    'Coffee',
    'Թող տաք սպասդ հատկապես համեղ լինի։',
    'Թող ձմռան համար համով բաղադրատոմս գտնես, {{firstName}}։',
  ),
  deskPair(
    'winter-early',
    'season_winter',
    'winter',
    'Sunset',
    '{{firstName}}, հաճելի ձմեռային երեկո եմ մաղթում։',
    'Սեղանի խաղն ու լավ ընկերներն էլ հիանալի ծրագիր են։',
  ),
  deskPair(
    'winter-message',
    'season_winter',
    'winter',
    'MessageCircle',
    'Թող այս ձմռանը ընկերոջիցդ լուր առնես։',
    'Ու երկար խոսելու ժամանակ լինի՝ հեռավորությունից անկախ, {{firstName}}։',
  ),
  deskPair(
    'winter-window',
    'season_winter',
    'winter',
    'Sparkles',
    '{{firstName}}, ձմռան մի փոքր երազանք քեզ։',
    'Գուցե մի վայր, ուր կուզենաս հարմար առիթով գնալ։',
  ),
  deskPair(
    'winter-return',
    'season_winter',
    'winter',
    'Coffee',
    'Ձմռանը տաք տուն վերադառնալն ուրիշ հաճույք է։',
    'Թող լավ թեյ էլ սպասի քեզ, {{firstName}}։',
  ),
  deskPair(
    'winter-slow',
    'season_winter',
    'winter',
    'BookOpen',
    '{{firstName}}, թող ձմռանը լավ գիրք ընկերակցի քեզ։',
    'Այնպիսին, որ ամեն անգամ սիրով բացես։',
  ),
  deskPair(
    'winter-company',
    'season_winter',
    'winter',
    'Smile',
    'Թող ձմեռային մի հանդիպում հաջողվի։',
    'Թեկուզ պարզ ճաշ՝ կարոտած մարդու հետ, {{firstName}}։',
  ),
  deskPair(
    'winter-citrus',
    'season_winter',
    'winter',
    'Sparkles',
    '{{firstName}}, ձմռան մի քիչ քաղցրություն քեզ։',
    'Օրինակ՝ մի իսկապես համեղ մանդարին։',
  ),
  deskPair(
    'winter-quiet',
    'season_winter',
    'winter',
    'Leaf',
    'Թող ձմեռային մի կեսօր քոնը լինի։',
    'Մի քիչ ժամանակ սիրածդ զբաղմունքի համար, {{firstName}}։',
  ),
  deskPair(
    'winter-glove',
    'season_winter',
    'winter',
    'Hand',
    '{{firstName}}, թող ձմռան օրը ջերմ բարև ունենա։',
    'Հաճելի է, երբ քեզ տեսնելիս ուրախանում են։',
  ),
  deskPair(
    'winter-keep',
    'season_winter',
    'winter',
    'Coffee',
    'Ձմռան մի նոր սիրելի բան քեզ, {{firstName}}։',
    'Ուտեստ, ֆիլմ կամ տեղ, ուր նորից կուզենաս գնալ։',
  ),
] as const;
