import { deskPair } from './desk-line-pair';

export const DESK_LINE_EVERYDAY_B = [
  deskPair(
    'everyday-unexpected-colour',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, hope something catches your eye today.',
    'A lovely colour combination or a particularly good shop window.',
  ),
  deskPair(
    'everyday-two-minutes',
    'everyday',
    'pleasure',
    'Coffee',
    'Here’s to two unhurried minutes.',
    'Long enough for the first sip to count, {{firstName}}.',
  ),
  deskPair(
    'everyday-kind-mirror',
    'everyday',
    'kindness',
    'Smile',
    '{{firstName}}, may someone meet you kindly today.',
    'Even a small, ordinary courtesy would do.',
  ),
  deskPair(
    'everyday-map-unfolds',
    'everyday',
    'detour',
    'Compass',
    'A new place to try, {{firstName}}?',
    'Hope you find somewhere you’d happily go back to.',
  ),
  deskPair(
    'everyday-name-remembered',
    'everyday',
    'kindness',
    'Hand',
    'It’s lovely when someone remembers you, {{firstName}}.',
    'Wishing you a warm welcome somewhere today.',
  ),
  deskPair(
    'everyday-clean-thought',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, wishing you one of those ‘of course!’ moments.',
    'When an idea suddenly seems much simpler than it did.',
  ),
  deskPair(
    'everyday-shared-silence',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, here’s to feeling comfortable in good company.',
    'Whether the conversation flows or you just enjoy being there.',
  ),
  deskPair(
    'everyday-street-music',
    'everyday',
    'music',
    'Music',
    'Hope you hear something you want to save.',
    'An unexpected song in a café can do that, {{firstName}}.',
  ),
  deskPair(
    'everyday-good-crumb',
    'everyday',
    'pleasure',
    'Smile',
    '{{firstName}}, wishing you a delicious little discovery.',
    'Something you’d order again before you’ve even finished it.',
  ),
  deskPair(
    'everyday-story-seed',
    'everyday',
    'story',
    'MessageCircle',
    'Hope someone tells you a story worth hearing.',
    'One you’re still thinking about on the way home, {{firstName}}.',
  ),
  deskPair(
    'everyday-right-tool',
    'everyday',
    'clarity',
    'Lightbulb',
    '{{firstName}}, hope a useful little tip finds you.',
    'The kind that makes you wonder why nobody mentioned it before.',
  ),
  deskPair(
    'everyday-open-window',
    'everyday',
    'curiosity',
    'Compass',
    'Here’s to finding something interesting by chance.',
    'One link leading to a very good read, perhaps, {{firstName}}.',
  ),
  deskPair(
    'everyday-warm-hello',
    'everyday',
    'kindness',
    'Hand',
    '{{firstName}}, hope you hear from someone you’ve missed.',
    'Even a quick hello can make the distance feel smaller.',
  ),
  deskPair(
    'everyday-half-smile',
    'everyday',
    'humour',
    'Smile',
    'A very silly joke might be just the thing.',
    'Hope someone has a good one for you, {{firstName}}.',
  ),
  deskPair(
    'everyday-fresh-air',
    'everyday',
    'pleasure',
    'Sprout',
    '{{firstName}}, wishing you a pleasant moment outdoors.',
    'A little change of scenery can be lovely.',
  ),
  deskPair(
    'everyday-puzzle-click',
    'everyday',
    'clarity',
    'Lightbulb',
    'Hope you remember that thing you nearly had.',
    'The name, the word, the tune — there it is, {{firstName}}.',
  ),
  deskPair(
    'everyday-good-company',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, here’s to people you can be yourself around.',
    'Hope there’s a chance for a proper catch-up.',
  ),
  deskPair(
    'everyday-saved-song',
    'everyday',
    'music',
    'Music',
    'An old playlist might have a surprise for you.',
    'Hope you rediscover a song you still love, {{firstName}}.',
  ),
  deskPair(
    'everyday-small-invite',
    'everyday',
    'forward',
    'Smile',
    '{{firstName}}, hope a lovely invitation comes your way.',
    'Something that makes you think, ‘Yes, that sounds good.’',
  ),
  deskPair(
    'everyday-lost-and-found',
    'everyday',
    'surprise',
    'Sparkles',
    'Here’s to finding something you thought you’d lost.',
    'Especially if it turns up in the first place you look, {{firstName}}.',
  ),
  deskPair(
    'everyday-neat-ending',
    'everyday',
    'clarity',
    'Compass',
    '{{firstName}}, wishing you a satisfying answer today.',
    'The kind that leaves you with one less thing to wonder about.',
  ),
  deskPair(
    'everyday-kind-weather-inside',
    'everyday',
    'kindness',
    'Smile',
    'Hope you meet a little patience today, {{firstName}}.',
    'Someone taking the time to listen can make a difference.',
  ),
  deskPair(
    'everyday-new-route',
    'everyday',
    'detour',
    'Compass',
    '{{firstName}}, here’s to a slightly different route.',
    'Same destination, better scenery.',
  ),
  deskPair(
    'everyday-notebook',
    'everyday',
    'curiosity',
    'BookOpen',
    'Hope you come across an idea worth keeping.',
    'Something you’ll be glad you wrote down, {{firstName}}.',
  ),
  deskPair(
    'everyday-shared-table',
    'everyday',
    'pleasure',
    'Coffee',
    '{{firstName}}, here’s to a meal with good conversation.',
    'The sort where you’re happy to stay a little longer.',
  ),
  deskPair(
    'everyday-light-remark',
    'everyday',
    'humour',
    'Smile',
    'Hope someone makes you smile with one sentence.',
    'A perfectly timed comment can do a lot, {{firstName}}.',
  ),
  deskPair(
    'everyday-hidden-door',
    'everyday',
    'curiosity',
    'Compass',
    '{{firstName}}, there might be a new favourite nearby.',
    'Hope you find a little place that feels like a good discovery.',
  ),
  deskPair(
    'everyday-steady-hand',
    'everyday',
    'kindness',
    'Hand',
    'Wishing you a helping hand when it’s useful.',
    'Someone who knows just where to start, {{firstName}}.',
  ),
  deskPair(
    'everyday-bright-object',
    'everyday',
    'surprise',
    'Sparkles',
    '{{firstName}}, hope you spot something worth a photo.',
    'Even if you only keep it for yourself.',
  ),
  deskPair(
    'everyday-good-pause',
    'everyday',
    'pleasure',
    'Sunset',
    'A moment to enjoy the view would be nice.',
    'Hope there’s a good one somewhere in your day, {{firstName}}.',
  ),
  deskPair(
    'everyday-echo',
    'everyday',
    'conversation',
    'MessageCircle',
    '{{firstName}}, hope you feel understood today.',
    'It’s lovely when someone knows exactly what you mean.',
  ),
  deskPair(
    'everyday-later-smile',
    'everyday',
    'story',
    'Smile',
    'Here’s to a moment you’ll smile about later.',
    'Something worth remembering from an otherwise ordinary day, {{firstName}}.',
  ),
] as const;
