#!/usr/bin/env bash
#
# NBOS Cloud Agent install (idempotent).
#
# Prepares a fully usable local dev environment:
#   - system packages (PostgreSQL + Redis) when missing,
#   - PostgreSQL role/database,
#   - .env.local with local dev secrets (only when absent),
#   - workspace dependencies + Prisma client,
#   - database schema (prisma db push) and base seed data.
#
# Safe to run repeatedly. Assumes Node 22 + pnpm are already on PATH (provided by
# the base image / Corepack).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

PG_USER="nbos"
PG_PASSWORD="nbos"
PG_DB="nbos"
PG_HOST="127.0.0.1"
PG_PORT="5432"

log() { printf '\n\033[1;34m[install]\033[0m %s\n' "$1"; }

# ── 1. System packages ───────────────────────────────────────────────
if ! command -v psql >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
  log "Installing PostgreSQL and Redis"
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    postgresql postgresql-contrib redis-server
fi

# ── 2. Start PostgreSQL (needed to create role/db and push schema) ────
log "Starting PostgreSQL cluster"
PG_VERSION="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -n1 || true)"
if [ -n "$PG_VERSION" ]; then
  sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
fi

# Wait for PostgreSQL to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

# ── 3. PostgreSQL role + database ────────────────────────────────────
log "Ensuring PostgreSQL role and database"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${PG_USER}'" \
  | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE ${PG_USER} LOGIN PASSWORD '${PG_PASSWORD}' CREATEDB;"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${PG_DB}'" \
  | grep -q 1 \
  || sudo -u postgres createdb -O "${PG_USER}" "${PG_DB}"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${PG_DB} TO ${PG_USER};" >/dev/null

# ── 4. .env.local (dev-only; never committed) ────────────────────────
if [ ! -f .env.local ]; then
  log "Creating .env.local with generated dev secrets"
  gen() { openssl rand -base64 36 | tr -d '/+=' | cut -c1-44; }
  cat > .env.local <<ENV
# NBOS local development environment (generated by .cursor/scripts/cloud-install.sh)
NODE_ENV="development"

APP_URL="http://localhost:3000"
AUTH_URL="http://localhost:3000"
NEXTAUTH_URL="http://localhost:3000"
BACKEND_URL="http://localhost:4000"
NEXT_PUBLIC_BACKEND_URL="http://localhost:4000"
CORS_ORIGIN="http://localhost:3000"

DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}"
DIRECT_URL="postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}"
DB_TOTAL_CONNECTION_BUDGET=100

AUTH_SECRET="$(gen)"
JWT_SECRET="$(gen)"
CREDENTIALS_ENCRYPTION_KEY="$(gen)"
AUTH_REFRESH_COOKIE_NAME="nbos_refresh"
AUTH_REFRESH_TOKEN_PEPPER="$(gen)"
SCHEDULER_API_KEY="$(gen)"

PORT=4000
REDIS_URL="redis://localhost:6379"

ADMIN_EMAIL="admin@nbos.local"
ADMIN_PASSWORD="Admin1234!"
ENV
fi

# ── 5. Dependencies + Prisma client ──────────────────────────────────
log "Installing workspace dependencies"
pnpm install --frozen-lockfile

log "Generating Prisma client"
pnpm db:generate

# ── 6. Schema + seed data ────────────────────────────────────────────
# `db push` is used instead of `migrate deploy`: the committed migration history
# has an enum value added and used in the same transaction, which fails a fresh
# `migrate deploy` on modern PostgreSQL. `db push` syncs the schema; the base
# system Roles/Departments (normally seeded inside migrations) are added by
# db-bootstrap.sql, then RBAC + admin seeds run on top.
log "Syncing database schema (prisma db push)"
pnpm db:push

log "Seeding base roles/departments"
PGPASSWORD="${PG_PASSWORD}" psql -h "${PG_HOST}" -U "${PG_USER}" -d "${PG_DB}" \
  -v ON_ERROR_STOP=1 -f .cursor/scripts/db-bootstrap.sql

log "Seeding RBAC permissions"
pnpm --filter @nbos/database seed:rbac

log "Seeding admin user"
pnpm --filter @nbos/database seed:admin

log "Install complete"
