import { UPLOAD_SESSION_TTL_MS } from '../drive-upload.constants';

export const ARTIFACT_OPERATION_TTL_MS = UPLOAD_SESSION_TTL_MS;

export const ARTIFACT_OPERATION_MAX_RECOVERY_ATTEMPTS = 8;

export const ARTIFACT_OPERATION_ACTIVE_STATUSES = [
  'PREPARED',
  'UPLOAD_PENDING',
  'OBJECT_UPLOADED',
  'OBJECT_VERIFIED',
  'FAILED_RETRYABLE',
] as const;

export const ARTIFACT_OPERATION_TERMINAL_STATUSES = [
  'COMPLETED',
  'FAILED',
  'CANCELLED',
  'EXPIRED',
] as const;

export const ARTIFACT_OPERATION_CLEANUP_STATUSES = ['FAILED', 'CANCELLED', 'EXPIRED'] as const;
