/** Mirrors API `bonus-policy-templates` (display-only in web). */
export const BONUS_POLICY_TEMPLATE_SALES_COMPANY_RATES = 'SALES_COMPANY_RATES';

export const BONUS_POLICY_TEMPLATE_MANUAL_ONLY = 'MANUAL_ONLY';

export const BONUS_POLICY_TEMPLATE_DELIVERY_PROPORTIONAL_FUNDING = 'DELIVERY_PROPORTIONAL_FUNDING';

export const BONUS_POLICY_TEMPLATE_MARKETING_MANUAL_PLANNED = 'MARKETING_MANUAL_PLANNED';
