import {
  BarChart3,
  Bell,
  Boxes,
  Bug,
  Building2,
  Calendar,
  CircuitBoard,
  Code,
  Contact,
  CreditCard,
  Database,
  FileText,
  Globe,
  KeyRound,
  Languages,
  Layers,
  Layout,
  Library,
  LineChart,
  Palette,
  Repeat,
  Search,
  Server,
  Shield,
  ShoppingCart,
  Store,
  Truck,
  UserCircle,
  Warehouse,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import { DELIVERY_FUNCTION_ICON_ALLOWLIST } from '@nbos/shared';

const ICONS: Record<(typeof DELIVERY_FUNCTION_ICON_ALLOWLIST)[number], LucideIcon> = {
  CreditCard,
  Warehouse,
  Building2,
  Contact,
  Library,
  Database,
  Truck,
  ShoppingCart,
  Languages,
  Search,
  UserCircle,
  Shield,
  Store,
  Calendar,
  Repeat,
  BarChart3,
  KeyRound,
  Bell,
  Globe,
  LineChart,
  Server,
  Layout,
  Palette,
  Code,
  Bug,
  Wrench,
  FileText,
  Layers,
  Boxes,
  CircuitBoard,
};

export function CatalogFunctionIcon({ iconKey }: { iconKey: string }) {
  const Icon = ICONS[iconKey as keyof typeof ICONS] ?? Layers;
  return <Icon size={20} aria-hidden className="text-foreground" />;
}
